### ISSUE TITLE
UnusedBaselineEntry error not showing on error free codebase

### ISSUE THREAD

**Issue by wickedOne** [vimeo/psalm#10001]
it seems that when having the `findUnusedBaselineEntry` config option set to true, the `UnusedBaselineEntry` error only shows when other issues are found and disappears when there are none.

[here](https://github.com/wickedOne/psalm-test) is a minimal standalone project to illustrate the issue (instructions for reproduction over [here](https://github.com/wickedOne/psalm-test/blob/a6bfc79414af2c217c28825f16a6ed868e4a00e1/src/Foo.php#L9-L12)).

**Comment by ygottschalk** [comment]
Looking at this, the fix itself is the easy part.
However, I'd consider this a BC breaks, because a project with no "real" issues will start reporting UnusedBaseline issues, where it had not before. This might break some CI/CD pipelines.

I would either
- introduce a new config option (my fav choice, though I know ppl here think we already have too much of those options)
- wait with the merge for v6.x since we do change the default value for the setting in that release anyway...

**Comment by wickedOne** [comment]
personally i'm fine with waiting until v6.x

just ran into it while deprecating a homebrew ci pipeline job which validates the baseline, in favour of the config setting so i thought i'd report it...

**Comment by ygottschalk** [comment]
@orklah what do you think? Config option vs release v6.x

**Comment by orklah** [comment]
I'm not sure about the BC break

It seems weirder to me to have no error and suddeny adding one error makes a few other appears.

Also, people are expecting SA tools to add errors when we change version (even in minor) so I'm not too annoyed by fixing that on a minor version
