### ISSUE TITLE
How to define yield return type condition on param

### ISSUE THREAD

**Issue by xpader** [vimeo/psalm#10015]
There's a function return a yielded type Promise<array|string>, the TValue type depends on one input params, like:

https://psalm.dev/r/a7af24c139

psalm alway think yield value is array or string, can it get the real type by input param?

![WX20230711-180237](https://github.com/vimeo/psalm/assets/8629617/d9cc8ec6-7b34-4336-888d-9b72c15fdefe)

**Comment by ygottschalk** [comment]
Something like this https://psalm.dev/r/a8a4eb576c or that https://psalm.dev/r/ea0f6140c5 ?

We have conditional return types https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/ for such cases. For psalm to recognise them, a `( ... )` is required.

But the error psalm reported in your given example was about the types did not match because psalm has typed the return type of `json_decode(..., true)` as `mixed` and the type of `$json` in your example is `'{.....}` a literal string which is not as general as string.

Adding the types inside the function will make the issues disappear.

**Comment by xpader** [comment]
That's strangy we need to mark type for this `$json = '{"a":"Hello World"}';`, json is definitely a string type.

And why `Promise<string|array>` is not identical `Promise<string>|Promise<array>`?

I think these are something that can be improved.

**Comment by ygottschalk** [comment]
> And why `Promise<string|array>` is not identical `Promise<string>|Promise<array>`?

Lets look at the differences of `array<string>|array<int>` vs `array<string|int>`.
```
$array1 = $condition ? ['a', 'b'] : [1, 2]; // array<string>|array<int>
$array2 = ['a', 2]; // array<string|int>
```
Checking the type of the first element of `$array1` will give information about the type of every element in the array. This is not the case with `$array2`. 
You could say that `array<string>|array<int> => array<string|int>` but not `array<string>|array<int> <= array<string|int> ` and that is why they are not identical.



> That's strangy we need to mark type for this `$json = '{"a":"Hello World"}';`, json is definitely a string type.

As it turns out, we do not need to. I thought we need to because the type `string` is more general than the literal string type `'{"a":"Hello World"}'`.
But psalm can generalise that on its own as I just realised: https://psalm.dev/r/fded631454



So the root of the problem you encountered was, that `json_decode`'s return type is typed as `mixed`. So the best you could do is to check what `json_decode` returned and handle the error if there was maleformed json input: https://psalm.dev/r/1a54e0871e

**Comment by xpader** [comment]
Thanks, I'm now understand `array<string>|array<int>` is identical to `array<string|int>`, but not when reverse, I think that reason is array can have multiple values, `array<string>|array<int>` means array values is all string type or all int type, but `array<string|int>` means array values can have string and int types both, that's different.

But Promise has only one value, that is string or int, so I think `Promise<string|array>` can identical `Promise<string>|Promise<array>` each other.

**Comment by weirdan** [comment]
`json_decode()` can indeed return various types, even with `$associative = true`: https://3v4l.org/fEhM9

> `@psalm-return ($parseJson is true ? FakePromise<array> :  FakePromise<string>)`

This is the way (in this case).
