### ISSUE TITLE
[Help needed] PropertyTypeCoercion errors

### ISSUE THREAD

**Issue by vlakarados** [vimeo/psalm#10045]
https://psalm.dev/r/bafba43992

I'm not sure how to fix this, tried hinting ```@return Table<T>``` for `getAttributes()` method, but no success as well.

This is a simple Repository / Entity pattern with Table attribute as definition, stripped down to bare minimum for simplicity sake.

**Comment by ygottschalk** [comment]
Psalm can not guarantee / see what class is inside the attribute constructor and therefore not guarantee that the `T` of type `Repository<T>` is the same `T` you used to construct the attribute.
This might show more clear what I want to point out: https://psalm.dev/r/5a0e227833

The main problem you are facing is, that half of the problem is in the generic type annotation (not available at runtime) and the other half is in the attribute (not available at analysis on type level (as far as I know)).

A solution might be to pass the class-string in the constructor. That way psalm should be able to infeer the generic type.

**Comment by vlakarados** [comment]
@ygottschalk thank you, but that breaks the whole point of using attributes in this case, surely the constructor is much more provisioned in real code with instances of PDO etc.

I might rework the code to have a repository factory to pass the class string to the constructor, but would that remove the problem, might check.

**Comment by vlakarados** [comment]
Seems to work with no issues:

https://psalm.dev/r/c10628e537

Thank you! I will check if that works in real case scenario as well.

**Comment by ygottschalk** [comment]
You might run into a similar problem.
I think the main issue is, that psalm does not know about the value passed to the attributes constructor. Consider this:
```
/** @extends Repository<SomeEntity> */
#[Table(OtherEntity::class)]
final readonly class SomeEntityRepository extends Repository {}
```
I believe it will be hard for you to come around that.

I really like the idea of having some attributes do all the work, but with that approach it will be hard to use static analysis to check for correct instanciation. I would likely go for something like this: https://psalm.dev/r/2b8457876d

**Comment by vlakarados** [comment]
As I couldn't refactor it to have a factory (needs abstract factory, but not possible(not preferable) in my case) I went away with presenting a variable and forcing a type on it.

https://psalm.dev/r/22d0de3cb5

@ygottschalk thank you very much for assistance, I do not yet understand all the implications and nuances of psalm, but got a bit clearer. I wonder why can't you import a template without extends/implements.
