### ISSUE TITLE
Allow `isset` check for property of interface types

### ISSUE THREAD

**Issue by tuqqu** [vimeo/psalm#10245]
We can use the `isset` language construct to check whether a certain object property exists or not.

However, currently psalm reports such usages for interface types:
https://psalm.dev/r/b12099047e

**Comment by tuqqu** [comment]
Consider the following code: https://psalm.dev/r/91d2ef2f58
```php
interface I {}

function takes_object(object $o): void
{
    if (isset($o->prop)) {
        print gettype($o->prop);
    }
}

function takes_i(I $i): void
{
    if (isset($i->prop)) {
        print gettype($i->prop);
    }
}
```

Psalm will emit an error for the second function, but not for the first one, even though the argument of `takes_i` function is also always an `object`.
In other words having more information about the argument can be detrimental.

**Comment by orklah** [comment]
I agree that's weird, but the way I'd solve that is rather going the other way, making stdClass the only universalObjectCrate and making any isset on object an error. The line between those two was always blurry but it doesn't need to be anymore now that we can actually typehint those correctly. 

Let's leave the issue open so that it can gather more opinion if people are interested, but my two cents on that is that it's opening a can of worms with very little gain

**Comment by danog** [comment]
Yeah I don't like this either, let's not do this.
