### ISSUE TITLE
Misparse of enums in list{}

### ISSUE THREAD

**Issue by bwoebi** [vimeo/psalm#10669]
https://psalm.dev/r/04fcfb0955

While `@return A::X|A::Y` standalone works, putting it in a `list{}` will misinterpret the first part of the expression up to the first colon as array key of the list instead of recognizing the enum value.

**Comment by danog** [comment]
Just wrap the parts: https://psalm.dev/r/61d2d0ec1c

**Comment by bwoebi** [comment]
@danog That seems rather like a workaround than a fix? I see no particular parse conflict here, why it should not be possible to parse that?

**Comment by danog** [comment]
Yeah that can be fixed!

**Comment by weirdan** [comment]
The reason for not allowing constants in list keys seems to be somewhat technical. Our type AST for keyed arrays uses native php types (int/string) to represent shape keys (they become actual array kes of `TKeyedArray::$properties`) rather than Psalm types. Thus, we cannot differentiate between `A::B` and `"A::B"` - they both have the same string representation, and we cannot reliably resolve constant values during the scanning phase as referenced classes may not have been scanned yet. And we won't be ever able to use standalone constants (e.g. PHP_VERSION) in shape _keys_ using current syntax as it's ambiguous.  

But we should be able to support constants in list _value_ types by backtracking and reinterpreting the part being parsed, as a value type, the same way we can do it currently with `list{1}`.
