### ISSUE TITLE
resource is not a reserved word

### ISSUE THREAD

**Issue by gmazzap** [vimeo/psalm#10939]
Consider following snippet:

```php
class resource {}

new \resource();
```

https://psalm.dev/r/28d550f321

Psalm complains about "resource" being a reserved word, but it is not.

See how it is a valid class name since forever, basically: https://3v4l.org/1miXE

**Comment by orklah** [comment]
Yeah but that's pretty much unavoidable. Psalm need to know what the symbol references and juggling with what may be a class resource and sometimes a normal resource would be very complex for something that is probably used by 10 codebases (and probably should not be used at all)

**Comment by gmazzap** [comment]
Not really understand. A real/normal `resource` can not use the word `resource` in PHP. If you find that word in PHP code it is _always_ a class name, and _never_ a real resource.

Anyway, it is an edge case for something I working on, I met once in 20 years and will probably not meet it again, so if you say it can't be fixed, you can close this issue.

**Comment by orklah** [comment]
Yeah but Psalm uses more than code to analyze project. It uses a lot of phpdoc. And 99.99% of cases, when you have a `@param resource $a`, we're talking about the meta type `resource` of php, and not a possible class.

Chances are, even for a project that does have a class resource in the main namespace, a phpdoc that says `resource` could still be a file handler rather than the class

So yeah, we're not going to bother too much on this one
