### ISSUE TITLE
Interface-declared complex param type is not inherited

### ISSUE THREAD

**Issue by sserbin** [vimeo/psalm#1100]
Test case:
```php
<?php
interface I {
  /**
  * @param int[] $data
  */
  function foo(array $data) : void {}
}
class C implements I {
  public function foo(array $data) : void {
  	strlen($data);
  }
}
```

Expected: array<mixed,int>
Actual: array<mixed,mixed>

fwiw, happens also with:
```
array{k1:string,k2:int}
array<string,int>
```
_Primitive types are inherited properly however_

https://getpsalm.org/r/c406a946b1

**Comment by weirdan** [comment]
That's typehints interfering: https://getpsalm.org/r/abfa05aee9

**Comment by sserbin** [comment]
That's true, although even with `array` typehint still doesn't work with
```
array{k1:string,k2:int}
array<string,int>
```

**Comment by muglug** [comment]
While Psalm supports it in some situations (where there's _no_ type given), I think inheriting documentation for params is less than ideal, because it makes it more confusing to work on the function in question.

If you feel strongly and still want that change, I'd accept a PR as long as it doesn't make Psalm's analysis slower.

**Comment by muglug** [comment]
Adding `@inheritDoc` is a workaround here
