### ISSUE TITLE
Passing Closure to usort callable param end up with unexpected MixedArgumentTypeCoercion 

### ISSUE THREAD

**Issue by cseufert** [vimeo/psalm#11146]
https://psalm.dev/r/be92d17a1b

I am not sure if the is a problem with the signature of usort, or something else.

**Comment by adamkoppede** [comment]
psalm uses the return type specified in the function signature (which is just `\Closure`) instead of the more concrete `\pure-Closure(int, int):int` type (which it infers from the `return` statement in the actual function body), when analyzing the `\usort` call. However, variables of type `\Closure` cannot be passed into `\usort` because it expects `callable(T,T):int` where T is the type of array items.

Specifying the more concrete `\Closure(int, int):int` type as the return type of `makeSort()` via PHPDoc makes it compatible with the `\usort()` call: https://psalm.dev/r/f88d6d5c4a (Comparision: https://psalm.dev/r/90cb12b664)

Removing the native `\Closure` return type hint generates an error that exposes the type psalm inferred from the `return` statement of the function body: https://psalm.dev/r/fa5967cfc0 _[MissingReturnType](https://psalm.dev/050) - 3:10 - Method makeSort does not have a return type, expecting pure-Closure(int, int):int_

The behavior is the same for `array` types for example: https://psalm.dev/r/cd1859b34f.

-----

Using only the less concrete return type from the function signature instead of the more concrete return type inferred from the function body makes at least sense for calls across API boundaries. Image the following setup:

```php
<?php

// LIBRARY v1.0.0

function makeVehicle():array {
    return [
        "axles" => 2,
        "wheels_per_axle" => 1,
    ];
}

// APPLICATION

foreach (makeVehicle() as $property => $value) {
    echo "Property {$property}: {$value}";
}
```

If we were to use the return type inferred from the `makeVehicle()` function body in the application code, the application code would be valid for this version of the library. But what if the library wants to add support for vehicles with three wheels without breaking its API. From its view, it only declares `array<array-key, mixed>` as return type, so it should be able to just change the entire structure. But since the application is build upon knowledge internal to the library, it'll become invalid:

```php
<?php

// LIBRARY v1.1.0

function makeVehicle():array {
    return [
        "axles" => [
            [
                "wheels" => 1,
            ],
            [
                "wheels" => 2,
            ],
         ],
    ];
}

// APPLICATION

foreach (makeVehicle() as $property => $value) {
    // This breaks because array cannot be assigned to string
    echo "Property {$property}: {$value}";
}
```

**Comment by cseufert** [comment]
OK, this makes more sense, thanks for clearing that up. I thought it was the inheritance chain for the callable -> closure that it was getting tripped on, on the parameter list.
