### ISSUE TITLE
Ignore undefined classes with names ending in XYZ

### ISSUE THREAD

**Issue by luckyraul** [vimeo/psalm#1225]
I am trying to adjust psalm to a Magento based module. 
There are auto generated classes, which are not exist in the module. 
for ex ```\Magento\Catalog\Model\ResourceModel\Product\Attribute\CollectionFactory```, but there is  ```\Magento\Catalog\Model\ResourceModel\Product\Attribute\Collection``` class

How to skip classes names ending with Factory?

**Comment by muglug** [comment]
I've just added a change to allow you to ignore classes based on a pattern e.g.

```xml
<issueHandlers>
  <UndefinedClass>
    <errorLevel type="suppress">
      <referencedClass="Magento\Catalog\Model\*Factory" />
    </errorLevel>
  </UndefinedClass>
</issueHandlers>
```

**Comment by agorbulin** [comment]
Hi guys.
Actually it will not be working:
```
<issueHandlers>
  <UndefinedClass>
    <errorLevel type="suppress">
      <referencedClass name="*Factory" />
    </errorLevel>
  </UndefinedClass>
</issueHandlers>
```
because [here](https://github.com/vimeo/psalm/blob/c195e8fd21a197a783f2d2bdb310ce6e03fd49f0/src/Psalm/Config/FileFilter.php#L262) must be strict check (e.g. if (strpos($class_name, '*') !== false))
After applying fix, *Factory classes were disappeared from the error report.

**Please add fix to the code, who can contribute.**
