### ISSUE TITLE
array shapes & array_shift()

### ISSUE THREAD

**Issue by SignpostMarv** [vimeo/psalm#1255]
Is it within the scope of psalm's purpose to keep track of array modification with funcs like array_shift()?

https://getpsalm.org/r/632db6aee8
```php
<?php
declare(strict_types=1);

/**
* @return array{0:string, 1:int}
*/
function foo() : array {
  return ['foo', 1];
}

function bar(int $val) : void {
  echo (string) $val, "\n";
}

$foo = foo(); // $foo is array{0:string, 1:int}
$str = array_shift($foo); $foo is now array{0:int}: https://3v4l.org/slCsu
echo $str; // just here to get the psalm playground to not make noise about an unused variable
bar($foo[0]); // psalm thinks that $foo[0] is string|int, but if array_shift() were tracked, psalm would know it was an int.
```

**Comment by muglug** [comment]
What I really need here, I think, is to use `array{string, int}` to mean a special `TTuple` type that extends `ObjectLike`.

It'd work like this:
```php
/**
 * @param array{0:string, 1:int} $arr
 */
function takesUnordered(array $arr) : void {}
/**
 * @param array{string, int} $arr
 */
function takesOrdered(array $arr) : void {}

takesUnordered([0 => "hello", 1 => 5]); // works
takesUnordered([1 => 5, 0 => "hello"]); // works
takesOrdered([0 => "hello", 1 => 5]); // works
takesOrdered([1 => 5, 0 => "hello"]); // fails
```

Then the `array_shift` etc. logic could be applied safely.

cc @TysonAndre who persuaded me to keep the `array{string, int}` shorthand

**Comment by TysonAndre** [comment]
Another approach I've been thinking about would be to have a different notation for array types that are exclusively limited to those keys. I can't think of a good name, `tuple` only works for consecutive int keys

This is useful when APIs expect a limited set of fields (e.g. to catch typos)

- Unfortunately, the *order* of the keys might be an orthogonal check, so that might not work here. I guess consecutive keys starting from 0 could be a special case.

---

- Uppercase ARRAY would be confusing 
- Extra symbols such as `array*{0:string,1:int}` would also be confusing
- `strict-array{0:string,1:int}` would warn if extra keys were used (e.g. `['zero',1,2]`, `array{0:string,1:int,2?:int}`, etc

**Comment by muglug** [comment]
I'm happy with `strict-array{...}`

**Comment by muglug** [comment]
The alternative (though this would be a breaking change) is that all `array`s become strict, and denote an array that can have extra fields is denoted by
`array{foo: string, bar: int, ...}`

**Comment by SignpostMarv** [comment]
@muglug mimic `declare` and require config-level or file-level docblock comment to require strict arrays?

**Comment by olleharstedt** [comment]
How would this interact with PHP's `list`?

**Comment by olleharstedt** [comment]
Ah, seems like it works already. Awesome! https://psalm.dev/r/0ae9c56b41

**Comment by muglug** [comment]
This mostly works with `array{string, int}`

**Comment by egst** [comment]
Was the `strict-array` idea abandoned?
