### ISSUE TITLE
Asserts on array offsets have no effect on array type

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#1367]
https://getpsalm.org/r/cb15686874
```php
<?php
  function data(): array {
    return [];
  }

  /** @return array{0:Exception,1:Exception} */
  function f(): array {
    $ret = data();
    assert($ret[0] instanceof Exception);
    assert($ret[1] instanceof Exception);
    return $ret;
  }
```
**Expected**: no issues
**Actual**:
```
Psalm output (using commit 348b8ee): 

INFO: MixedTypeCoercion - 11:5 - The type 'array<array-key, mixed>' is more general than the declared return type 'array{0:Exception, 1:Exception}' for f

INFO: MixedTypeCoercion - 6:7 - The declared return type 'array{0:Exception, 1:Exception}' for f is more specific than the inferred return type 'array<array-key, mixed>'
```
**Workaround**:
```php
    return [$ret[0], $ret[1]];
```
https://getpsalm.org/r/56fd02d4e4

So it appears offset types are inferred, but not propagated to the containing array.

**Comment by muglug** [comment]
After about four hours' work I've fixed for the special case where the array is `array<array-key, mixed>` (i.e. no further types).

Beyond that, it's a hard problem as Psalm only has two ways of representing arrays - generic (`array<foo, bar>`) and objectlike (`array{somefoo:bar,otherfoo:bar}`). Objectlike arrays decompose to generic arrays whenever they're combined with generic arrays:

```
objectlike + objectlike => objectlike
objectlike + generic => generic
generic + generic => generic
```

In order to support the following, more refined example:

```php
/**
 * @param array<int, Exception> $ret
 * @return array{0:InvalidArgumentException,1:InvalidArgumentException}
 */
function foo(array $ret): array {
    assert($ret[0] instanceof InvalidArgumentException);
    assert($ret[1] instanceof InvalidArgumentException);
    return $ret;
}
```

https://psalm.dev/r/6ce308f46c

I'd have to allow `objectlike` types to also have generic parameters, and that logic would be _super_ convoluted, so I'd really rather not.

**Comment by weirdan** [comment]
Thanks for the explanation.
