### ISSUE TITLE
Support @psalm-type in stubs

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1386]
If `@psalm-type` exists in a stub, it should be available globally. Ref #1373 for documentation and @juanfernandoe for the idea

**Comment by mholubowski** [comment]
@muglug Myself and our team (and a couple other teams) are wondering what the current best practice is for creating a "project-wide" @psalm-type?

In the latest version of Psalm, is it still per file?

**Comment by klesun** [comment]
Note, in phpstan there is a [config option](https://phpstan.org/writing-php-code/phpdoc-types#type-aliases) that allows declaring global typedefs in their yaml-ish config file, maybe it could be adopted here as well?

**Comment by muglug** [comment]
This has been superseded by `@psalm-import-type` IMO, closing.

**Comment by rzvc** [comment]
Given that `@psalm-type / @psalm-import-type` come with some very inconvenient constraints, there's a very wide range of situations where `@psalm-type` definitions are simply not available, forcing you to either turn to `@psalm-suppress`, or rewrite the code in a less desirable way for that particular problem.

Can you please reconsider some form of global `@psalm-types`? Lacking a `@psalm-global-type`, that can be defined anywhere, defining them as a stub is the next best thing.

Also, even assuming that `@psalm-import-type` might eventually work from any context (it doesn't right now), I still think there's great value in the idea of a stub for these types, because it addresses a different way of doing things.
