### ISSUE TITLE
False unused variable when initialized before try, set in try, and referenced in finally

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#1464]
https://psalm.dev/r/8b3d850bbf

**Comment by mpesari** [comment]
Here's another example (without `finally`): https://psalm.dev/r/07b24e2393

**Comment by weirdan** [comment]
> Here's another example (without finally): https://psalm.dev/r/07b24e2393

This one doesn't look like a bug to me (but message could be improved). Basically you have useless assignment (which Psalm reports as unused variable), since `$foo` is unconditionally overwritten later (also there's no exceptions thrown).

What you have there boils down to https://psalm.dev/r/d4a5e6d835

**Comment by mpesari** [comment]
Here's an updated version: https://psalm.dev/r/c84a13b086
