### ISSUE TITLE
Cannot access private method __construct from context

### ISSUE THREAD

**Issue by neanton** [vimeo/psalm#1532]
I'm seeing and issue with an ability to override a singleton. Sure this is not a good overall class design, but our legacy project is moving to Psalm integration and right now I don't get why this error is triggered.

https://psalm.dev/r/5772a0c6fb

**Comment by weirdan** [comment]
Cutting it down further, Psalm seem to consider `__construct` in the wrong context when it analyzes property initializations (https://psalm.dev/r/71f46539fa)
```php
<?php
namespace NS;

class Base
{
    /**
     * @var \Exception
     */
    protected $a;

    private function __construct()
    {
      $this->a = new \Exception();
    }
  
    public static function getInstance(): self { return new static; }
}

class Concrete extends Base {}
```

**Comment by muglug** [comment]
Yeah, this happens because, in the process of analyzing whether the property is initialized, Psalm makes a synthetic constructor for `Concrete` that calls `Base::__construct`

Should be a straightforward fix, but I likely won’t get to it until Sunday evening. You should be able to supppress the error for now.
