### ISSUE TITLE
`@psalm-suppress` not picked up on typed property declarations

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1683]
Possibly due to bleeding edge AST stuff, but `@psalm-` specific docblocks on properties don't seem to affect nodes that declare types on properties:

```php
<?php

class A
{
    /** @psalm-suppress UndefinedClass */
    public ?IDoNotExist $property;
}
```

https://psalm.dev/r/0d712baf1c : 

```
Psalm output (using commit 9fb9679):

ERROR: UndefinedClass - 6:13 - Class or interface IDoNotExist does not exist
```

**Comment by muglug** [comment]
It's also a problem on regular `@var` docblocks: https://psalm.dev/r/886d4017b0.

I think those sorts of `UndefinedClass` issues should be suppressed at the class or config level (where you can specify with `<referencedClass name="..." />`, not at the individual docblock level (because they inevitably bleed into other places.
