### ISSUE TITLE
False positive on simple-cache psr exceptions

### ISSUE THREAD

**Issue by Taluu** [vimeo/psalm#1856]
Can't really reproduce on the psalm.dev playground, as it's from the [simple-cache psr](https://github.com/php-fig/simple-cache/blob/master/src/CacheException.php) : This (base) interface exception doesn't extend `Throwable`, so when we try to catch an exception based on this interface (e.g the `InvalidArgumentException` interface which extends this one in the psr package), we have a report stating that the exception cannot be caught because it doesn't extend `Throwable` or `Exception`.

This must be because of a relic from php 5.6, where you didn't have the `Throwable` interface.

Ignoring it from the start would be awesome IMO. Or maybe documenting it ?

**Comment by muglug** [comment]
Adding this to your config should fix:

```xml
<InvalidThrow>
  <errorLevel type="suppress">
    <referencedClass>Psr\SimpleCache\InvalidArgumentException</referencedClass>
  </errorLevel>
</InvalidThrow>
```

**Comment by Radiergummi** [comment]
@muglug I'm sorry but where am I supposed to add this? Directly below `<psalm>`? That causes PHPStorm to complain about a schema violation.

**Comment by Radiergummi** [comment]
Nevermind, a little trial and error brought me there. Your code example should (probably) be
```xml
<issueHandlers>
    <InvalidThrow>
        <errorLevel type="suppress">
            <referencedClass name="Psr\SimpleCache\InvalidArgumentException"/>
        </errorLevel>
    </InvalidThrow>
</issueHandlers>
``` 

Would it make sense to add this to the issue page (https://psalm.dev/133) instead? The PSR Simple Cache exceptions are a really prominent reason where fixing the issue is simply not possible, so maybe the appropriate escape hatch should be documented right where the error output leads you to.
