### ISSUE TITLE
Add config for sinks and sources

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#1977]

**Comment by muglug** [comment]
Two issues:

When running the analysis on Vimeo's codebase, there are places where a certain sink (`echo`) isn't a problem, e.g. when printing to stdout in a cron.

I think we could use something like

```xml
<taintSources>
  <sourceMethod name="Foo\Bar::baz" />
</taintSources>

<taintSinks>
  <sinkFunction name="echo" argument="1">
    <ignoreFiles>
      <directory name="cron" />
    </ignoreFiles>
  </sinkFunction>
</taintSinks>
```

cc @paragonie-scott

**Comment by weirdan** [comment]
Just a note: you need to be very very sure that the output is going be handled in a safe way. For example, if cron stdout is saved to a file (as is often the case) that someone may later `cat` to their terminal, you need to make sure you escape ANSI escape sequences. Otherwise, [nasty things may happen](https://www.proteansec.com/linux/blast-past-executing-code-terminal-emulators-via-escape-sequences/#exploitation).

**Comment by muglug** [comment]
yeah, I've mentioned the possibility of bad shell stuff here: https://github.com/vimeo/psalm/issues/1990
