### ISSUE TITLE
Non-array types confuse docblock validation

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#2021]
It seems `array` has special logic concerning docblock validation, see

https://psalm.dev/r/d2720d6775 :+1: (expected 1 issue, got 1)
https://psalm.dev/r/77a7897003 :-1: (expected 2 issues, got 1)
https://psalm.dev/r/0e63536d9c :-1: (expected 1 issue, got 0)

**Comment by ro0NL** [comment]
i think https://psalm.dev/r/5788c8d9fe shows the inconsistency more clear

**Comment by muglug** [comment]
Yeah, I agree there are some slightly inconsistent rules. The purpose is to avoid too much noise - I'm not sure that removing a property (but keeping its `@param` docblock) should be a problem for Psalm, as Psalm can just ignore the corresponding `@param`.

**Comment by ro0NL** [comment]
Understood, not sure what the point of `InvalidDocblockParamName` still is then :/ removing it would be less noise even ;)

**Comment by muglug** [comment]
I've added more documentation in https://github.com/vimeo/psalm/commit/8228a0f9a5d0e145b25df2cb6327834238ad38dc

It's because an `array` type for a param generally lacks information (i.e. the key/value types), so the check is triggered. It's also triggered if no type is given: https://psalm.dev/r/bc09ec5191
