### ISSUE TITLE
class-string doesn't work with strings

### ISSUE THREAD

**Issue by iluuu1994** [vimeo/psalm#2086]
```php
/**
 * @param class-string $className
 * @psalm-suppress UnusedParam
 */
function foo($className): void {}

foo(\stdClass::class);
foo('\stdClass');
```

> ERROR: ArgumentTypeCoercion - 10:5 - Argument 1 of foo expects class-string, parent type string(\stdClass) provided

https://psalm.dev/r/50ce862c07

Is this intentional? If it is, please don't bother to add support for this. The `::class` notation is cleaner anyway. And this can easily be automated.

**Comment by weirdan** [comment]
It's intentional. You may want to use [`allowCoercionFromStringToClassConst`](https://github.com/vimeo/psalm/blob/master/docs/running_psalm/configuration.md#allowcoercionfromstringtoclassconst) config attirubute to adjust what kind of issue is generated (but _some_ kind of issue is always generated).

**Comment by muglug** [comment]
Yup, what he said :)
