### ISSUE TITLE
Psalm throws InvalidArgument with wrong expected param type

### ISSUE THREAD

**Issue by nicolopignatelli** [vimeo/psalm#2087]
I'm not sure this is a mistake in my annotations, but I couldn't find any and still I get different outcomes whether I call `get_some_or_fail()` with an explicit param or the return value of `result()` 

https://psalm.dev/r/ce9944489e

**Comment by weirdan** [comment]
I think it's because your `Result` is _invariant_ generic, meaning `Result<Child>` is not treated as compatible with `Result<Parent>`, even though `Child` extends `Parent`. To make it work that way you want to declare your `Result` as _covariant_ generic (using `@template-covariant` annotation): https://psalm.dev/r/7e1d15f403

**Comment by weirdan** [comment]
@muglug it seems documentation for `@template-covariant` is missing.
