### ISSUE TITLE
UndefinedVariable seems to be affected by whether or not InvalidScalarArgument is emitted

### ISSUE THREAD

**Issue by TysonAndre** [vimeo/psalm#243]
Observed: if InvalidScalarArgument is emitted, UndefinedVariable is also emitted for $x
Expected: InvalidScalarArgument should be emitted, UndefinedVariable should not be (this isn't using strict_types)

```
<?php

class C { 
    public function get_two(int $x) : array {
        return [6, $x];
    }   

    private function _foo(int $x) : int { return $x*$x; }

    public function test_two() {
        list($x, $y) = $this->get_two("4");
        return $this->_foo($x);
    }   
}

```

There are multiple issues for the code, but only the below shouldn't be emitted:

```
ERROR: UndefinedVariable - src/undefined.php:12:28 - Cannot find referenced variable $x                                                              
        return $this->_foo($x);      
```

**Comment by muglug** [comment]
Fixed in https://github.com/vimeo/psalm/commit/38c8a1d9cfa798ff36391aea0a6c547511f0a609 (pls ignore hastily-reverted serialisation changes)

**Comment by muglug** [comment]
And on the `declare(strict_types=1)` front, I don't like that whole thing.

Having read [ajf's rationale](https://wiki.php.net/rfc/scalar_type_hints#why_both), it seems like a lot of the caution was due to the lack of decent static analysis tools for native PHP at the time of writing. Obviously, with Phan, Psalm and others, that point is much less of an issue, and Psalm operates on the assumption that all code should be strictly-typed (whether or not the `declare` is present).

I've also seen calls to make `declare(strict_types=1)` the default in upcoming (minor) versions of PHP, which I'd definitely be in favour of.
