### ISSUE TITLE
Template param constrained to an union type incompatible with empty

### ISSUE THREAD

**Issue by ShiraNai7** [vimeo/psalm#2435]
https://psalm.dev/r/6acbc4bf73

Removing `as array-key` or changing it to `as string` prevents the error.

**Comment by weirdan** [comment]
Empty untyped array cannot provide types to specialize the `Map`. Where generic types cannot be inferred you would have to declare them yourself with a `@var` docblock: https://psalm.dev/r/0822b5ef09

@muglug why `new Map([])` is inferred to be `Map<array-key, empty>` instead of `Map<array-key,mixed>` here? It 'breaks' usage of mutating methods: https://psalm.dev/r/321ae06ba8 which IMO should be allowed.

**Comment by muglug** [comment]
inferring an empty array as `array<empty, empty>` makes array addition type calculation simple:

````
[] + [1, 2, 3]
=
array<empty, empty> + array<int, int>
=
array<empty | int, empty | int>
=
array<int, int>
```

whereas typing it to mixed would spoil the types:

```
array<array-key, mixed> + array<int, int>
=
array<array-key | int, mixed | int>
=
array<array-key, mixed>
```

**Comment by muglug** [comment]
This would be fixed if generics were supported in the language - you'd do

`new Map<string, int>([])`. Until then, you have to use a `@var` docblock
