### ISSUE TITLE
UndefinedDocblockClass when using template in static method

### ISSUE THREAD

**Issue by jenschude** [vimeo/psalm#2571]
While trying to create factory methods I found out that templates are not correctly recognized in static methods.

```php
<?php
  
/**
 * @template T
 */
abstract class Foo {
  /**
   * @psalm-param T $data
   */
  public static function bar($data) {
  }
}
```
See https://psalm.dev/r/6d29fb978b

**Comment by weirdan** [comment]
This is intentional: 797a059a84f86f66518c8b6c61870f165fcc27d1

Can you explain what you're trying to achieve? Most likely you want `@template` tag on the static method itself: https://psalm.dev/r/340c710984

**Comment by jenschude** [comment]
This was the minimum example which replicated the issue itself. But I was dealing with an abstract class which had a final factory method. The inheriting classes defined the type.

But yeah seems that I can solve it with your proposal. 👍

**Comment by staabm** [comment]
We experienced a similar peoblem in https://github.com/redaxo/redaxo/pull/4359 in which we wanted to template a trait with a single type across all its methods

**Comment by kamazee** [comment]
> Can you explain what you're trying to achieve?

I wanted to use a template on a param of a static method in Enum class from myclabs/php-enum. Template there defines a value type in a "enum"; template in expanded in child class; parent's `from` method gets a enum entry by value. Here is a commit where I though it would work: https://github.com/myclabs/php-enum/commit/a128308839cf931057943f833a91e8ae2fab84ba (full file can be seen from there; this is a one-class library).

Here is a minimal example if a file there is too big to read: https://psalm.dev/r/402a8f5b50

**Comment by orklah** [comment]
You can't mix class templates and static templates by design. Would you mind providing a more detailed reproducer (where usage of $value is visible) on a new Issue if you have questions?

**Comment by christian-kolb** [comment]
@weirdan @orklah Here is an example in my project where I need the behaviour you mentioned as being handled that way by design:

```php
/** @psalm-immutable */
abstract class Id implements \Stringable
{
    final public function __construct(
        protected readonly string $value,
    ) {
        if (!uuid_is_valid($value)) {
            throw new InvalidId($value);
        }
    }
}

/** @psalm-immutable */
class UserId extends Id
{
}

/**
 * @template T extends Id
 *
 * @template-implements \IteratorAggregate<int, T>
 */
abstract class IdList implements \IteratorAggregate, \Countable
{
    /** @var array<int, T> */
    public readonly array $ids;

    /** @param array<int, T> $ids */
    final public function __construct(
        array $ids,
    ) {
        $this->ids = array_values($ids);
    }

    /** @return class-string<T> */
    abstract public static function handlesIdClass(): string;
}

/** @extends IdList<UserId> */
final class UserIdList extends IdList
{
    public static function handlesIdClass(): string
    {
        return UserId::class;
    }
}
```

The only workaround I found for it is adding the following:
```php
/**
 * @template TT of T
 *
 * @return class-string<TT>
 */
abstract public static function handlesIdClass(): string;
```

But this then breaks PHPStan, because it interpretes the `@psalm` annontations.

What was the reason for disabling the template syntax for static methods? I only see the commit, but don't know why this was done. Would this be a valid example to reconsider the previous decision? 🙂

**Comment by orklah** [comment]
Based on your example, let's say I create a `class AdminUserId extends UserId`.

I then make sure to make an array of `AdminUserId` and I make a `new UserIdList($myArrayOfAdminUserId);`

I have a `UserIdList<AdminUserId>`. Let's say I call `handlesIdClass` on that. The docblock says it should return `AdminUserId::class` when in fact, it will return `UserId::class`.

What you did is not completely safe from a type POV. You lied on the template you're returning because the information you have on a static method is not enough to fully describe the template of what's inside your List. To be able to describe it accurately, you'd need to have access to the list itself, so you can only do that from an instance, not from a static method.

This is this kind of confusion that lead Psalm to stop allowing class level template on static methods.

I think this could be solved in two ways for your specific example:
- Psalm could understand that if UserId is declared final there is no risk of getting anything else and we could assume static methods are allowed to have insight on the template type because of that
- We could invent some way of declaring a template that specifically says you can't push childs into it (maybe a new keyword aside from `as` and `of`?) and again, because the template type is certain, we could allow static methods to know/use the template type

However, I don't have enough hindsight to know if it would be enough to solve the confusion for all situations here

**Comment by christian-kolb** [comment]
Thanks for your extensive reply. I'm not sure whether I can follow your logic 100%.

I like the example of yours but I think there are two relevant notes:

- When I want to store `AdminUserId` objects, I would create an `AdminUserIdList` with a `handlesIdClass` of `AdminUserId`.
- Even if I wouldn't create an `AdminUserIdList` but put `AdminUserId` objects into my `UserIdList`, they are technically also `UserId` objects. So the typing is still valid. It's less precise, but I might want that because I there might also be a `ManagerUserId` (extending `UserId`) objects in that same list.

You are correct, that using `UserIdList<AdminUserId>` would be incorrect. But isn't that simply a wrong annotation? I could also write the following

```php
/** @var int $test */
$test = 'bla';
```

and Psalm won't complain there.

At the moment I can't use Psalm to configure a valid behaviour.

Aren't there more cases where it is useful than harmful?

I don't know if it's relevant, but it is possible with PHPStan. It's not just possible, but it even reads Psalm annotations but handles them like PHPDoc would and therefore leads to false positives 😞

**Comment by orklah** [comment]
While trying to make a working example, I realized two mistakes I made:
- you didn't create a new template on UserIdList because you pushed UserId in the extends so `UserIdList<AdminUserId>`.I guess it would be a third way to hint at Psalm that the class knows the type of T.
- Your example seems to work already: https://psalm.dev/r/dc8b18bcbd I'm confused, I'd have expected Psalm to raise an error on using T on the static method here

**Comment by christian-kolb** [comment]
Wow that is strange, it actually seems to work on `@return`. Maybe it always did and I found it on `@param` and just assumed it's the same for `@return`. I adapted the example, the problem is when using it with `@param`: https://psalm.dev/r/56b205a8cd

Would you see the same kind of issues? Shouldn't this be a valid case even when using `AdminUserId` and `ManagerUserId` objects on it?
