### ISSUE TITLE
Template with scalars

### ISSUE THREAD

**Issue by Nyholm** [vimeo/psalm#2736]
Im not sure if this is a question or a feature request. I have a function that looks like this: 

```php
function xmlValueOrNull(\SimpleXMLElement $xml, string $type)
{
    if (0 === $xml->count()) {
        return null;
    }

    $value = $xml->__toString();

    // Return the correct type
    switch($type) {
        case 'int':
            return (int) $value;
        case 'bool':
            return (bool) $value;
        case 'string':
        default:
            return $value;
    }
}
```

The `$type` parameter decide how we should type cast the output. 

My first attempt was to do something lile: 
```php
    /**
     * @template T
     * @psalm-param class-string<T> $type
     *
     * @return T
     */
    final protected function xmlValueOrNull(\SimpleXMLElement $xml, string $type)
```

If `$type` was reference to a class that would be fine, but with scalars I get errors like: "string is a reserved word"

Is there a way to let psalm know what type my method return?

**Comment by Nyholm** [comment]
What a nice bot =)
Of course: https://psalm.dev/r/7ca374f4fa

**Comment by muglug** [comment]
It's definitely not a feature Psalm supports currently - `class-string<T>` applies only to objects, which is why it's not working for you.

I could support something like `type-string<T>` which would accept values from the `gettype` function, but that would mean you having to specify those exact strings - `"boolean"` instead of `"bool"` etc.

One (non-templated) alternative is just to have a bunch of different functions for different types – `intValueOrNull`, `boolValueOrNull` etc.

**Comment by Nyholm** [comment]
Thank you for the response. 

> I could support something like type-string<T> which would accept values from the gettype function, but that would mean you having to specify those exact strings - "boolean" instead of "bool" etc.

That would be awesome. 
I see you closed the issue, Should I create a new one if I want this feature request to be open?

**Comment by muglug** [comment]
Having thought about this a bit more, I think the most logical thing would be for you to write a Psalm plugin - extending the `FunctionReturnTypeProvider` hook.

The alternative (adding a new type) would introduce a lot of extra logic that I don’t think is warranted by this particular edge-case.
