### ISSUE TITLE
No errors found in Gitlab CI job running on Windows

### ISSUE THREAD

**Issue by FabianTe** [vimeo/psalm#2759]
Hi everyone,

when running psalm in a gitlab runner hosted on windows, there is no console output and no errors are found:

![image](https://user-images.githubusercontent.com/7669818/74030178-b51dfd00-49ae-11ea-917d-4c9c7143bbbe.png)

I use the exact same command on my local environment and it works. Why does this happen?

**Comment by FabianTe** [comment]
Nope, this does not relate to psalm itself but rather how I use it I guess.

**Comment by weirdan** [comment]
> Why does this happen?

Psalm checks the environment and adjusts options:
https://github.com/vimeo/psalm/blob/966336a475858d91e964d2929471b7c1bafc039f/src/psalm.php#L421-L431

**Comment by muglug** [comment]
@FabianTe does it work without `--threads=4`? That's incompatible with Windows, and should result in an early exit.

**Comment by FabianTe** [comment]
@muglug Nope, still behaves the same.

@weirdan Okay, the progress bar is disabled then, but then I'd still wonder why no errors are found (trust me there are a *lot* of errors to find :wink:)

The command is run from the same project root as locally and the cwd is the same. Is there a debug mode where I could check if the psalm config has been properly loaded?

**Comment by muglug** [comment]
You can run with `--debug`

**Comment by muglug** [comment]
And what happens if you use the path `vendor/vimeo/psalm/psalm` instead?

**Comment by someniatko** [comment]
@FabianTe this is because you have installed your composer dependencies under Linux (or MacOS), and composer therefore created a `vendor/bin/psalm` file as a UNIX symlink to the `../vimeo/bin/psalm`.

Windows OS does not understand UNIX symlinks, so it interprects it as a regular text file.

Therefore, you should either:
- install composer dependencies and run tests on the same system, then Composer will create valid symlinks
- OR run psalm directly like this: `php vendor\vimeo\psalm\psalm --threads=4 --show-info=false`

**Comment by FabianTe** [comment]
Thank you! Didn't think of that since I am using Linux for work for a relatively short time.
The "legacy" codebase I work with commits it's vendor folder :man_shrugging: and I can't install dependencies in the Gitlab Job :sob: 

For now I will go with `php vendor\vimeo\psalm\psalm --threads=4 --show-info=false`

Thanks for thinking into this @someniatko, I am actually you thought of this
