### ISSUE TITLE
Invalid MixedReturnStatement ( unable to replicate )

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#2861]
the code runs with no issues in psalm.dev : https://psalm.dev/r/2fafbd8ebf

however, the same is triggering a `MixedReturnStatement` locally and in CI.

Repostiroy : https://github.com/azjezz/psl
Pull Request : https://github.com/azjezz/psl/pull/15
CI Build : https://travis-ci.org/azjezz/psl/jobs/653660377#L2205

**Comment by weirdan** [comment]
@muglug 

I think there's a possible enhancement that could also help with this issue. Currently, Psalm only analyzes autoloaded functions in a limited way because it accesses them through reflection. Basically it ignores function docblocks (for autoloaded functions) altogether.

What it could do instead is either use the docblock information available through reflection, or figure out source files for those functions and add them to the list of files to be scanned. The latter may cause some performance penalty, especially when functions are included but not used. 

I tested the latter approach on `azjezz/psl` repo and it makes about a hundred issues to disappear (many are Mixed* false positives).

**Comment by azjezz** [comment]
@weirdan thanks for looking into this, currently this issue is making it really hard for me to continue working on the project as i can't really figure where the real issues are due to this.

**Comment by weirdan** [comment]
@azjezz you may try to add all those files containing functions as [stubs](https://psalm.dev/docs/running_psalm/configuration/#ltstubsgt), as a temporary workaround. As far as I can tell it should let Psalm know it should scan them.

**Comment by azjezz** [comment]
fixed in #3183

Thank you @weirdan :) I'm currently removing all function stubs from psalm configurations in azjezz/psl#32 and hopefully, with the help of #3768, this issue won't be encountered again 🎉
