### ISSUE TITLE
@method named as not allowed

### ISSUE THREAD

**Issue by AegirLeet** [vimeo/psalm#2881]
Psalm is currently reporting two issues in a Laravel project and I'm having a hard time figuring out why. Is there any way to find out why Psalm raises a certain issue and what Psalm thinks the relevant types look like at that point? I'd try setting some breakpoints, but with xdebug disabled by Psalm, that wouldn't work. I've also tried --debug and --debug-by-line but couldn't find any useful information.

In this case, the problem is some chained method calls raising PossiblyInvalidMethodCall/MixedMethodCall issues because Psalm assumes some weird (imo wrong) types. I've created a minimal reproduction [here](https://github.com/AegirLeet/psalm-issue). I just can't figure out where those types are coming from, since everything looks fine in PhpStorm.

Is there a recommended way to debug such cases?

**Comment by weirdan** [comment]
I'm getting the following:
```console
$ composer psalm
> psalm --config=psalm.xml --show-info=true --stats --no-progress

ERROR: PossiblyInvalidMethodCall - test.php:13:7 - Cannot call method on possible array<array-key, mixed> variable 
    ->namespace('')


ERROR: MixedMethodCall - test.php:14:7 - Cannot determine the type of the object on the left hand side of this expression
    ->group('');


------------------------------
2 errors found
------------------------------

Checks took 1.22 seconds and used 79.021MB of memory
Psalm was able to infer types for 95.2381% of the codebase
-----------------
95% test.php (1 mixed)

Script psalm --config=psalm.xml --show-info=true --stats --no-progress handling the psalm event returned with error code 1
```
1st reported issue is an issue with Psalm itself. It (incorrectly) thinks method called `as()` is invalid, and rejects the whole list of `@method` tags on `RouteRegistrar`. It only becomes apparent when you copy the file from `vendor` to your project folder, as many errors in `vendor` are not reported.

2nd issue is a consequence of the first one. Since psalm didn't know what type `->namespace()` is being called on, it figured out it may return anything (`mixed`). So `->group()` call on mixed is reported.

**Comment by muglug** [comment]
Yeah, reproduced here: https://psalm.dev/r/14e49516d2

**Comment by AegirLeet** [comment]
Ah, I see. Thanks for the quick fix.
