### ISSUE TITLE
doesn't see __construct() of subclasses created by class-string as used

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#2966]
https://psalm.dev/r/9d743cfcc4

I would expect psalm to know that `createFoo()` is instantiating a `Foo` and thus knows that `Foo::__construct()` is used. It's certainly called by PHP

**Comment by pilif** [comment]
(I'm so sorry - I'm totally spamming you with issues these days. I hope that eventually I get to know the depths of psalm well enough that I have a chance at producing PRs for issues like this - but right now I'm *so* stumped)

**Comment by muglug** [comment]
It was an easy fix! The `methodExists` method does double duty – it also tells Psalm that methods are used, and where they're used. The fix was to call it when processing variable calls of `new $templated_class`

**Comment by muglug** [comment]
Although _actually_ I just fixed the registration of `FooBar::__construct`. I don't think `Foo::__construct` should be registered – `new $templated_class` should only be allowed when the constructor is declared `final`, as it's otherwise impossible to reason about a number of things (like whether there are enough arguments passed to `__construct`)

**Comment by muglug** [comment]
A possible workaround for this would be a `@psalm-newable` annotation which would allow the constructor to be overridden, but would ensure the signature was correct. That annotation would allow your use-case above with no errors.
