### ISSUE TITLE
json_encode cannot return false if JSON_THROW_ON_ERROR is passed

### ISSUE THREAD

**Issue by iggyvolz** [vimeo/psalm#2996]
https://psalm.dev/r/5208d10bbe

If JSON_THROW_ON_ERROR is passed to json_encode's options, it is not able to return false and is suitable to be used in functions such as __toString.

Behaviour is described at https://www.php.net/manual/en/json.constants.php - may need to check for PHP version >7.3 and check that  JSON_PARTIAL_OUTPUT_ON_ERROR is not set (the wording is a bit ambiguous there)

**Comment by orklah** [comment]
Note: The original code doesn't produce issues anymore. Not because JSON_THROW_ON_ERROR was supported but because the `false` must have been handled as `ignorable`. This means it was not totally fixed (Psalm still think there can be false in there but don't bother reporting it depending on configs). The PR above should fix the core issue
