### ISSUE TITLE
Typed holes

### ISSUE THREAD

**Issue by marcosh** [vimeo/psalm#2998]
A nice feature of several functional languages are typed holes (for example, see https://wiki.haskell.org/GHC/Typed_holes), which allow developers to gain information about the type of something they still have to define.

It would be nice to have something similar using Psalm.

For example, if I have a function

```
/**
 * @template A
 * @psalm-param A $param
 * @psalm-return MyClass<A>
 */
function foo ($param) { ... }
```

and then I use it in a context where Psalm can infer that `A` is actually `int`, I would like to be able to get a message from Psalm telling me that the parameter should be an `int`.

One possibility would be just changing the error message when an undefined variable is passed. At the moment it is something like

```
UndefinedVariable - src/LinkedList.php:96:29 - Cannot find referenced variable $foo
```

It would be nice if it mentioned also the type that Psalm would infer for `$foo` if it was defined.

**Comment by muglug** [comment]
I had something similar, but I removed it because it was a bit of a maintenance burden.

Given https://psalm.dev/r/a1f73d1a99 it would tell you that the missing param type should probably be an `int`. I switched instead to tracking function argument usage, which turned out to be much simpler calculate (Psalm tracks all calls to `hasNoParamType`, and is thus able to suggest `int` as the type of `$u`.

**Comment by marcosh** [comment]
Thanks @muglug 

In you're example what gets returned is definitely enough.

I was looking more into the case where a template is restricted to be a specific type by its usage

**Comment by muglug** [comment]
Not going to implement this, sorry
