### ISSUE TITLE
Add unsigned types

### ISSUE THREAD

**Issue by vladyslavstartsev** [vimeo/psalm#3199]
There are scalar numeric types provided by php and psalm, such as:
* int
* float
* numeric
* numeric-string

What I'm requesting here, is `unsigned` types. You probably know them from other more typed languages (you can easily google for Rust/Haskell/C# unsigned types) and SQL, there they mostly provide you with less memory usage. PHP numeric types are all signed
But one of other features of it (unsigned types) is that you are sure that it's values is `>= 0`.
What I see is adding 4 extra types each starts with `unsigned-*`
* unsigned-int
* unsigned-float
* unsigned-numeric
* unsigned-numeric-string

I know that I should probably work with Value Objects instead, but some systems are still do not use VOs.

This can look like this 

```php
<?php

declare(strict_types=1);

    /**
     * @return unsigned-int
     */
    function unsignedIntNoError(): int
    {
        return 1;
    }

    /**
     * @return unsigned-int
     */
    function unsignedIntError(): int
    {
        return -1;
    }
```

This can also be done if there will be assertion expression syntax. It will look something like this
```php
<?php

declare(strict_types=1);

    /**
     * @psalm-assert-expression `$x >= 0` $x
     */
    function unsignedInt(int $x): int
    {
        return $x+1;
    }

    unsignedInt(1); // everything is ok
    unsignedInt(-1); // error because expression evaluates to -1 >= 0 which is false
```
use cases:
* catch signed values on SA level when working with DB (you will get error if you provide it)
* type some internal php function (I'm sure they exist, but I can't find it currently. I was looking at `bcscale` but it's unfortunately broken internally because it accepts negative scale without error. UPD: found some `time_nanosleep` accepts only positive `int`s; `json_encode` 3rd param can be only greater than zero)
* a step before creating VO (for example, `UnsignedInt.php`) in legacy applications

This way psalm type system will become more powerful.

**Comment by muglug** [comment]
I can see the benefit of this type, but the fact that it's tricky to infer makes it a poor candidate for Psalm's type system.

**Comment by vladyslavstartsev** [comment]
@muglug what should be done before to pave the road for this feature?

**Comment by muglug** [comment]
At a minimum PHP would need have an `is_unsigned_int` method - most other existing types can be simply inferred from those sorts of checks.

**Comment by muglug** [comment]
Another big factor for me in justifying the effort is whether _not_ having this means Psalm can miss a lot of runtime bugs in big PHP applications, and I’m not convinced of that

**Comment by vladyslavstartsev** [comment]
Sorry if I'm asking stupid questions. But why can't we use user land methods, for example something like this https://www.php.net/manual/en/function.is-int.php#93560 ?

**Comment by muglug** [comment]
It’s still not a builtin method, and certainly not one in frequent use in userland code

**Comment by still-dreaming-1** [comment]
As far as needing an is_unsigned_int() method, couldn't it just infer that if it was an int already, and you checked with `if ($int >= 0)` then it is an unsigned int? After that, it is already typed as an unsigned int, and could then be passed around to and returned from things needing an unsigned int without having to check that again.

As far as not being convinced this would help avoid runtime bugs, well I just don't get that. It seems obvious to me an unsigned int should be one of the core types offered by any language. It helps the creators and users of functions understand the contract/API that function has. If a function accepts an int, you don't know just by looking at the signature if it is okay to pass that function something smaller than zero or not. If a function returns an int, you don't know if it is supposed to return something smaller than zero or not. Many of the bugs in code come from edge cases not being well enough defined or tested. This would help these edge cases to be "tested" by the analyzer, because it could see if you are passing in something greater than zero or not. Then for something along the lines of unit testing, a tool could generate test data to feed into different functions and see if it passes all the contracts (within the function). If that tool could see the function accepted an unsigned-int, it would then only generate and feed into it ints larger than or equal to zero, it would not need to test the negative cases.

For the same reasons, I think there should also be a positive-int type, where it must be an int greater than zero. There are many cases where if code resulted in anything smaller than one, this would be a bug.

There could also be additional things statically derived with these options. If you multiple an unsigned-int by an unsigned-int, you know the result is still an unsigned-int. If a literal 0 is used, that is an unsigned-int. If a literal 1 is used, that is a positive-int.

The only reason this does not seem super helpful in most code bases is almost nobody thinks this way, because their languages, tools, and teachers never showed them the way. Most programs don't fully reason about the edge cases because it seems like too much to deal with, or they just don't know how. With features like this, Psalm can be a ground breaking, revolutionary type system for PHP programs, ushering in a new era of making it easy to write mostly bug free, edge case handled code, for those willing to use it that way.

I'm also wondering what could be done about the other side of these edge cases, how high of an int should a particular function be designed and tested to work? Could new Psalm types or expressions help with that?
