### ISSUE TITLE
Discussion: "beginner" friendly issues

### ISSUE THREAD

**Issue by zerkms** [vimeo/psalm#3230]
Some other projects practice it and a week ago I tweeted directly to Matt about it (https://twitter.com/zerkms/status/1251319105283448832) but it looks like it fell under their radar.

Anyway, how about introducing a special issue label to mark issues that are "beginner"-friendly (in the meaning of "people that don't know the project code well enough" not the "absolutely programming beginners").

So that people (like me) who sometimes have some time to contribute to the public projects, but don't know where to start.

**Comment by muglug** [comment]
Figuring out what constitutes a "beginner" issue, as there are many types of beginners – someone who knows about types, but not about Psalm is one sort of beginner, someone who knows neither is another sort.

Where the fix is easy I try to suggest people create a PR, pointing to the place that they could update.

**Comment by weirdan** [comment]
> Where the fix is easy I try to suggest people create a PR, pointing to the place that they could update.

Label is still useful, as someone reporting the issue is not necessarily the one who is able to fix it. I see it's added already.

The list of 'easy' open issues is here: https://github.com/vimeo/psalm/issues?q=is%3Aopen+is%3Aissue+label%3A%22easy+problems%22

**Comment by muglug** [comment]
I'm going to reopen this until I'm done labelling

**Comment by muglug** [comment]
I think this is done now
