### ISSUE TITLE
non-empty-list does not match the declared list?

### ISSUE THREAD

**Issue by EvgeniiR** [vimeo/psalm#3319]
Hello, here is code sample - https://psalm.dev/r/6afcdd642d . I think it should be correct, but psalm says it isn't.

Two things are unclear:
1. Why the inferred type for generic is non-empty-list, while there is also empty list return on line 35
2. Why inferred `non-empty-list` does not match declared `list`

**Comment by EvgeniiR** [comment]
UPD: Here's simplified sample: https://psalm.dev/r/0eccc06f15

**Comment by zakirullin** [comment]
That's clear that at line 40 we can only have <non-empty-list>s (due to previous return). The question is, why it didn't take into account an earlier return statement, where an empty-list is returned. So the resulting inferred type should be <list>

**Comment by zakirullin** [comment]
If you're going to swap things out - https://psalm.dev/r/4b3fa80a88 everything is working as expected

**Comment by weirdan** [comment]
Generics are invariant, unless you use `@template-covariant`. So it's not acceptable to return `Res<non-empty-list>` where `Res<list>` is declared as a return type.

Where you're getting too narrow generic type for a specific return statement it might be useful to constrain yourself to a single return point, so that generic construction accounts for all variants of its input parameters: https://psalm.dev/r/15c28e6091

**Comment by EvgeniiR** [comment]
> Generics are invariant, unless you use `@template-covariant`. So it's not acceptable to return `Res<non-empty-list>` where `Res<list>` is declared as a return type.
> 
> Where you're getting too narrow generic type for a specific return statement it might be useful to constrain yourself to a single return point, so that generic construction accounts for all variants of its input parameters: https://psalm.dev/r/15c28e6091

Got it, thanks, a little confusing imo, primarily because the inferred non-empty-list type, but if it's expected behavior, i think i might close this.
