### ISSUE TITLE
Annotating different func_num_arg count in tag name

### ISSUE THREAD

**Issue by othercorey** [vimeo/psalm#3341]
Looking at the new annotation syntax:
`@return (func_num_args() is 0 ? false : string)`

I was wondering if it's possible to bake this into the tag itself to reduce the size of these docblock comments:

```
@psalm-return-1 <type for func_num_args() is 1>
@psalm-return-2 ...
```

**Comment by othercorey** [comment]
https://psalm.dev/r/d5ae49b876

**Comment by muglug** [comment]
> I was wondering if it's possible to bake this into the tag itself to reduce the size of these docblock comments

I don't like the syntax you propose, because it removes a bunch of context that I think is useful for someone looking at the docblock.

Everything needs to be stored as a conditional return type internally for Psalm to work, but there could be some sort of pattern-matching shortcut (@ragboyjr and @Ocramius have suggested something similar):

```
/**
 * @psalm-overload returnsStuff2() : false
 * @psalm-overload returnsStuff2(mixed $str) : string
 */
function returnsStuff2() : mixed { ... }
```

But I'm also not massively keen on having to rival ways of doing things – a conditional return type most-accurately matches up to PHP's treatment of functions.

**Comment by othercorey** [comment]
Oh well. I thought it'd be more clear for anything other than the simple example scenario. But it's unlikely to commonly used.

**Comment by muglug** [comment]
closing for now, then
