### ISSUE TITLE
Psalm doesn't know that (string) DateInterval#days is numeric-string

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#3437]
https://psalm.dev/r/620b62d7c3

**Comment by weirdan** [comment]
`DateDiff::$days` is [documented](https://www.php.net/manual/en/class.dateinterval.php#dateinterval.props.days) as `false|int`. 
This can be fixed in [src/Psalm/Internal/PropertyMap.php](https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/PropertyMap.php)

"If created by DateTime::diff()" cannot be really expressed at the type system level though, so even when property type is fixed you'd still have the same error (because `(string)false` is not a `numeric-string`)
