### ISSUE TITLE
[Question] PHP Return type and @implements annotation clash with each other?

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#3480]
In [this case](https://psalm.dev/r/aa7a5439ba), since `3.11.3`, I do get LessSpecificImplementedReturnType inspection fired out, but [in case I omit the explicit return type](https://psalm.dev/r/ed5f046a01) I don't, and it seems Psalm relies its own type inference.

Just making sure both cases are intended and valid behavior. I would hope for a detailed explanation, if possible, thanks.

P.S. I know that I can annotate `@return` to work around this, but I love inference and don't like verbose writings :P

**Comment by weirdan** [comment]
I think it's best explained in historical context.

PHP 5 had no syntax for return types, so what people often did was that they declared return type in a docblock on interface and assumed that that definition is inherited by implementations (with or without explicit `@inheritdoc`), because according to LSP descendants should have the return type at least as narrow as the one defined in interface. There's a lot of code still in production looking like this:
```php
// framework code
interface I {
  /** @return int */
  public function method();
}
// application code
class C implements I {
  public function method() // assuming int because that's what interface defines
  { 
    return 42; 
  }
}
```
Then came PHP7, which introduced return types, but only allowed limited return type contravariance before PHP7.4. This means you had to use the same return type as interface defined and couldn't use a narrower type, even though it's valid under LSP, with one exception: if interface/parent did not have explicit return type, you could add any return type in descendant/implementation.  So what people did was that they kept the same type as interface declared, but provided correct narrower type in a docblock:
```php
// framework code
interface I {
  public function getError(): Exception;
}
// application code
class C implements I {
  /** @return RuntimeException */
  public function getError(): Exception // couldn't use RuntimeException here, as PHP would reject that
  { 
    return new RuntimeException;
  }
}
```
The exception I mentioned above is what allows your code to be run under PHP<7.4, as your interface lacks formal return type (as far as PHP sees it).

PHP 7.4 allows contravariant return types and you can write the above as follows:
```php
// framework code
interface I {
  public function getError(): Exception;
}
// application code
class C implements I {
  public function getError(): RuntimeException {
    return new RuntimeException;
  }
}
```
But there's a lot of inherited code written for different versions, often coexisting in the same codebase. And now Psalm adds generics on top of that, but has to account for all of those different approaches. Hope it makes it a bit clearer.

> I know that I can annotate `@return` to work around this

You can use `: Foo` as well, in this case.

**Comment by someniatko** [comment]
Thank you so much!
