### ISSUE TITLE
Crash when running with multiple threads

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#3627]
<img width="777" alt="Screen Shot 2020-06-22 at 9 37 45 PM" src="https://user-images.githubusercontent.com/279519/85272862-db14eb80-b4d0-11ea-98f5-2cf7d3028f43.png">

Using 3.11.6 in an ubuntu virtualbox image.
What info can I provide?

**Comment by weirdan** [comment]
Looking at the message, Psalm failed to allocate memory and was killed (by OOM killer?).

**Comment by leighman** [comment]
The VM has 3GB and it works with `--threads=1` so I'm not sure why it would be running out of memory

**Comment by muglug** [comment]
> The VM has 3GB and it works with --threads=1 so I'm not sure why it would be running out of memory

`--threads` > 1 will fork processes. Each process should share memory, but in heavily resource-constrained VMs (where the number of virtual cores is 1 or 2) memory appears not to be shared across those forked processes.

Psalm will default to `--threads=1` in those environments, so this error only appears when it's explicitly overridden.

**Comment by leighman** [comment]
@muglug It fails with the same error without an explicit `--threads` override.

**Comment by muglug** [comment]
Hmm... is it executing in parallel with anything else? How much memory does a single-threaded run take up?

**Comment by leighman** [comment]
`psalm --threads=1 --config=psalm-ci.xml --no-cache`
`Checks took 343.47 seconds and used 620.668MB of memory`

**Comment by weirdan** [comment]
Also:
* do you have swap enabled (`sudo swapon`) ?
* do you have overcommit enabled (`cat /proc/sys/vm/overcommit_memory`) ?

**Comment by leighman** [comment]
`cat /proc/sys/vm/overcommit_memory` returns `0`

**Comment by leighman** [comment]
`sudo swapon` shows no output and it still failed after running it

**Comment by weirdan** [comment]
This basically means that every virtual memory page have to be backed by a physical page (overcommit=0) and that page have to reside in RAM (because you have no swap). I suspect that CoW might be automatically disabled under such configuration, to ensure that forked process can access copied memory.

I would suggest to experiment with enabling overcommit. Ideally you want some swap space as well, to put unused or rarely used (but still occupied) memory pages on disk.
