### ISSUE TITLE
[enhancement] template request Partial<T>

### ISSUE THREAD

**Issue by douggr** [vimeo/psalm#3815]
Hello! Would be great to have something like TypeScript's [Partial&lt;T>](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialt).

https://psalm.dev/r/fa070766a7

**Comment by muglug** [comment]
Sorry, not going to add this to Psalm. TypeScript needs those types because its type system is structural – Javascript objects can be composed together in a way that PHP objects cannot. I understand you're asking for this on arrays, but I'm really hesitant on making arrays as powerful in Psalm's type system as objects are in TypeScript's.
