### ISSUE TITLE
[Q] Iterating over explicit array<mixed> generates MixedAssignment

### ISSUE THREAD

**Issue by amberovsky** [vimeo/psalm#3849]
Hello,

The `MixedAssignment` is generated in the following example https://psalm.dev/r/c1342ae444
Given that the type `mixed` is explicitly provided for the array elements - could you please explain what is the rationale to generate the error?

**Comment by orklah** [comment]
Mixed errors are the most strict and unforgiving type of errors. When you enable them, they'll raise an error for each usage of a mixed variable because they're a blind spot for Psalm. Anything could be in a mixed variable and Psalm can't guarantee it won't cause issues.
Feel free to disable mixed issues https://psalm.dev/docs/running_psalm/configuration/#reportmixedissues if you don't wish this level of strictness.

**Comment by amberovsky** [comment]
If a function parameter is _explicitly_ `mixed` and all the places the parameter is used in have _explicit_ `mixed` typehint then `mixed` has exactly the same sense as any other possible types (or speaking more generally - it is just a template type `T`).
What kind of issues `mixed` can cause in such cases?

**Comment by orklah** [comment]
Wherever you'll use the mixed value in the end is a possible source of error. Feel free to use something like scalar|object|resource|null instead. If there is no new error reported by Psalm, congratulations, your code was error proof with mixed issues. If not, then you have your answer on what errors you'd have missed.

**Comment by muglug** [comment]
Yeah this is inconsistent given that https://psalm.dev/r/32f82a0a05 generates no errors

**Comment by ygottschalk** [comment]
Actually it is consitent given that https://psalm.dev/r/53d7c66962 generates an error while https://psalm.dev/r/dc3c8d48f6 does not.

**Comment by muglug** [comment]
Yeah ok, I agree – just suppress the issue
