### ISSUE TITLE
RedundantCondition error while not redundant after use of array_shift

### ISSUE THREAD

**Issue by tvbeek** [vimeo/psalm#3941]
A check on the emptiness of the array is marked redundant while it can be empty after the use of array_shift.

I provided a small example to demonstrate the issue.

https://psalm.dev/r/a33f3347d3

**Comment by weirdan** [comment]
If I make it a bit more realistic by accepting the `$data` as a parameter the error goes away: https://psalm.dev/r/b252603667
In your example, however, Psalm marks `if (empty($data))` as redundant and not the check after `array_shift()` (which is of course is redundant as well) because it's seen `$data` initialized to empty array.

**Comment by tvbeek** [comment]
@weirdan thanks for the feedback.

My code example was stripped to much, sorry about that. I created a new example that shows that it gives the error on the second check.

https://psalm.dev/r/2a936893f0

**Comment by muglug** [comment]
Sorry, I think this is also a regression
