### ISSUE TITLE
Automatically detect immutable classes / mutation free getters

### ISSUE THREAD

**Issue by iquito** [vimeo/psalm#4034]
Defining immutable classes with `@psalm-immutable` like in https://psalm.dev/r/257706575b is a great feature, but after adding these annotations to many of my classes I was wondering if Psalm would not be able to automatically detect and imply at least `@psalm-mutation-free` for simple getter methods, like in https://psalm.dev/r/ef463a24c5:

```php
class Number
{
    private ?int $validTill = null;
    
    public function __construct(?int $validTill)
    {
        $this->validTill = $validTill;
    }
    
    /** @psalm-mutation-free */
    public function getValidTill(): ?int
    {
        return $this->validTill;
    }
}

$number = new Number(5);

if ($number->getValidTill() !== null) {
    echo \date('Y-m-d H:i:s', $number->getValidTill());
}
```

With `@psalm-mutation-free` Psalm correctly identifies that between the first `$number->getValidTill()` and the second `$number->getValidTill()` the value could not have changed, but as soon as I remove that annotation (see https://psalm.dev/r/90e677d9cb) Psalm thinks a change might have been possible, even though the method only returns the value of a property. Because a getter and returning a class property is such a common pattern it might be helpful for Psalm to add `@psalm-mutation-free` automatically to methods such as these, as this would improve the accuracy for Psalm in general and fewer explicit annotations would be necessary.

**Comment by someniatko** [comment]
@iquito Automatic inference you suggest will face some issue when it comes to child classes. E.g., consider this example:

```php
class Parent
{
    public function getValidTill(): ?int { return 1; }
}

class Child extends Parent
{
    private ?int $cache = null;

    public function getValidTill(): ?int
    {
        return $this->cache ??= parent::getValidTill();
    }
}
```

Let's assume `Parent#getValidTill()` method got `@psalm-mutation-free` annotation automatically inferred. What then comes next?
- Should Psalm now complain about `Child#getValidTill()` method violating the pureness?
- Or should it de-infer the annotation from the Parent's method? This variant is already impossible, because the Parent may have been extended in another package.

So this leads to contradiction, at least for non-final methods. This may work for final classes, though, but I don't think it does worth it.

**Comment by muglug** [comment]
This is not possible during inference (as @someniatko mentions) but would be possible in a separate step: https://github.com/vimeo/psalm/issues/4036
