### ISSUE TITLE
MixedAssignment: Psalm unable to determine type of value when iterating array after array_unshift

### ISSUE THREAD

**Issue by caugner** [vimeo/psalm#4048]
Given a `list<array{0: list<string>, 1: array<string, array|string>}>`.

When that list is non-empty and I `array_unshift` an element (of type `array{0: list<string>, 1: array<string, array|string>}`) with destructuring (i.e. one variable being `list<string>`, the other being `array<string, array|string>`), Psalm is unable to determine the type of the value when iterating over that last array.

https://psalm.dev/r/d6a182516e

PS: I have a typo in the JSON, but that shouldn't matter.

**Comment by muglug** [comment]
This is not a bug – this is a simpler version: https://psalm.dev/r/4f728517b4

You can fix by providing an array type: https://psalm.dev/r/77c1b96115

**Comment by caugner** [comment]
Hm, `array<string>|string` is not exactly the right type for `$value`, because `$array` could be nested more. I used `array` merely to workaround the type being actually recursive:

```
array<string, array<X>|string>
      ~~~~~~~~~~~~~~~~~~~~~~~ = X
```

If I reduce the example with `array<string, array|string>`, I no longer get the `MixedAssignment`, even though I don't specify the inner `array`:

https://psalm.dev/r/3d7420635f

Maybe the following example is more understandable:

https://psalm.dev/r/e74663e55c

Again, if I replace the two-element array by its second value, I no longer get a `MixedAssignment` either:

https://psalm.dev/r/9b005e1526

Similarly, if I replace `while` and `array_shift` by `foreach` (ignoring that it would break the code), without changing the type annotations, the `MixedAssignment` issue appears as well.

**Comment by muglug** [comment]
The problem is that you're writing to `$items` inside the loop with a type that's more mysterious than the one Psalm knew beforehand. Commenting out that assignment fixes all the examples you've given.

What you really have, it seems, is the following:

Given 

```
type RecursiveArray = array<string, RecursiveArray|string>
```

`$items` has type `list<array{0: list<string>, 1: RecursiveArray}>`

If Psalm supported recursive types it would be able to infer that the type of `$value` is always `RecursiveArray` after subtracting the `string` type.

But Psalm doesn't support recursive types (and likely never will), so Psalm just knows that `$value` is an `array`, and therefore the type of `$items` is made more general by that loop assignment, which leads to the `MixedAssignment` issue you're seeing.
