### ISSUE TITLE
Forcing @psalm-immutable in child classes without explicit annotation

### ISSUE THREAD

**Issue by thunderer** [vimeo/psalm#4075]
Psalm reports a [MissingImmutableAnnotation](https://psalm.dev/docs/running_psalm/issues/MissingImmutableAnnotation/) error whenever an implementation of an immutable interface does not have an explicit `@psalm-immutable` annotation.

I have hundreds of commands which implement a single `CommandInterface` empty marker interface. How can I force all "child" classes to inherit the `@psalm-immutable` annotation without specifying it there explicitly? If it's not possible right now, is it a good idea to introduce in the library, as a default behavior, issue handler configuration, or another annotation, like `@psalm-immutable-children`?

**Comment by muglug** [comment]
I much prefer that each class have an explicit annotation (even though I know that's a bit of a bore).

**Comment by bdsl** [comment]
Should a child of an immutable class have to be immutable itself?

I think for Liskov Substitution purposes it's valid for a circle with changable radius but fixed centre to extend from an immutable point on a plane. It's just the fields of the parent class that may not be mutated.

**Comment by thunderer** [comment]
@muglug @bdsl I understand that there may be varying approaches and preferences. A new annotation could enable the immutability check on a given class if any of its ancestors has it present. This could pave a way to other annotations "trickling down" on their childred.

**Comment by muglug** [comment]
Yeah, I don't like that implied immutability, sorry.

@bdsl it's an LSP issue for sure – see here: https://psalm.dev/r/c5013d5d24

**Comment by bdsl** [comment]
@muglug In the case you showed LSP is violated because `D` mutates `C::i`, violating the immutability of `C`. If it simply added an separate field and mutated that the problem wouldn't arrive. I don't know if there's an way for an SA tool to enforce immutability of an interface without requiring implementers to be immutable in all aspects.

My example of the point and the circle is from the [wikipedia page](https://en.wikipedia.org/wiki/Liskov_substitution_principle) on LSP: "_Fields added to the subtype may however be safely modified because they are not observable through the supertype methods. Thus, one can derive a circle with fixed center but mutable radius from immutable point without violating LSP._"

**Comment by muglug** [comment]
@bdsl no, `D` only mutates its own member

**Comment by bdsl** [comment]
Perhaps technically only classes should be declarable as mutable or immutable. Since an interface doesn't declare any state there's nothing to mutate or not mutate.

**Comment by bdsl** [comment]
@muglug OK, but that member shadows one from `C`. I don't know if it's possible to statically check that a class obeys the LSP history constraint, so what Psalm is doing now may well be the best option.

**Comment by weirdan** [comment]
> OK, but that member shadows one from C. 

Can you elaborate? `D` is not extending `C`, so how could it possibly shadow anything?

**Comment by bdsl** [comment]
@weirdan you're quite right. I completely misread @muglug's code example. Will re-read and reassess.

**Comment by bdsl** [comment]
I might be straying from the topic of issue #4075 but I think this is an interesting discussion.

I'd start by asking what it means for an interface or class to be immutable. I would expect it to mean that any consumers **of that interface or class** may safely assume that an instance of it never changes state, and therefore they can safely share or give away references to that instance without worrying about whether it will change.

That doesn't mean that the instance won't mutate, only that it won't affect the consumer. A mutation that they can't detect doesn't affect them, and so they can still treat the instance as immutable, and freely give out references to or work with references they have been passed without having to care about any chance of it mutating.

The interface `Im` that @muglug showed doesn't provide any way to access its state:
```php
/**
 * @psalm-immutable
 */
interface Im {
    function add(int $x) : self;
}
```
So there's no way for a client of that interface to really tell whether its immutable or not. Returning the `$this` reference is generally not useful for immutable objects but that doesn't itself violate immutability.

To make immutability meaningful we need to provide a away to read the state, e.g.:

```php
/**
 * @psalm-immutable
 * @property int $value
 */
interface Im {
    function add(int $x) : self;
}
```

Then a consumer of the interface can read `$im->value` once and be assured by the immutability that it won't change. Similar would apply if it has a getter method.

But according to LSP it should be legitimate to implement the interface like so:

```php
class E implements Im {
    public int $i = 0;
    public int $j = 0;
    public function __construct(int $i) {
        $this->i = $i;
    }
    public function add(int $x) : self
    {
         return new self($this->i + $x);
    }
}
```

Or even like:


```php
class F implements Im {
    public int $i = 0;
    public int $j = 0;
    public function __construct(int $i) {
        $this->i = $i;
        $this->j++;
    }
    public function add(int $x) : self
    {
         return new self($this->i + $x);
    }
}
```

The `$i` property should never be mutated because it's guaranteed immutable as part of the `Im` interface, but the `$j` property could be safely mutated. I suppose what I'm thinking of as immutable is effectively what you get by just annotating every property of the class individually as `@psalm-readonly`, but I don't think you can do that for an interface at the moment. I also don't have a current use case for a mutable class extending a mutable one.
