### ISSUE TITLE
Constructing an impure lambda is still pure

### ISSUE THREAD

**Issue by olleharstedt** [vimeo/psalm#4077]
Sorry for opening the same issue again, but I didn't see a good argument for why the other got closed.

The following snippet should type-check: https://psalm.dev/r/65d07cb31c

Following the definition of purity from Wikipedia:

1. Its return value is the same for the same arguments (yes, it returns the same callable, always)
2. Its evaluation has no side effects (also yes, the impure callable is not executed)

The current implementation of `@psalm-pure` does not get laziness right.

About the error:

> ERROR: ImpureFunctionCall - 9:7 - Cannot call echo from a mutation-free context

Maybe "mutation-free context" should not be inherited from the parent scope? What are the pros/cons behind this behaviour?

**Comment by olleharstedt** [comment]
Or maybe I should discuss this on stackoverflow to get some other feedback too. :thinking:

**Comment by weirdan** [comment]
> Its return value is the same for the same arguments (yes, it returns the same callable, always)

It depends on what's your definition of 'same'. If we're talking about identity (`===`) then objects (closures) returned from the function are not the same: https://3v4l.org/0IbQu

**Comment by olleharstedt** [comment]
> > Its return value is the same for the same arguments (yes, it returns the same callable, always)
> 
> It depends on what's your definition of 'same'. If we're talking about identity (`===`) then objects (closures) returned from the function are not the same: https://3v4l.org/0IbQu

Indeed. So pure won't work with data transfer objects, or data value objects? E.g. wrapping a string in an `Email` class.

**Comment by weirdan** [comment]
As I said, it depends. @muglug sidestepped this issue in his [article on immutability and pureness](https://psalm.dev/articles/immutability-and-beyond) by using less technical definition of pureness:
> A pure function is one whose output is completely deterministic given its input, and which has no side effects.

**Comment by olleharstedt** [comment]
> A pure function is one whose output is completely deterministic given its input, and which has no side effects.

Well, from this definition alone, the implementation is not correct, IMO.

**Comment by olleharstedt** [comment]
Physical equality breaks referential transparency:

> It should be noted that an equality operator like (===) above breaks referential transparency, so adding it to Haskell would ruin many of the nice properties that Haskell has and would make many program transformations invalid. 

From: https://wiki.haskell.org/Physical_equality

**Comment by muglug** [comment]
OK, you're right, I'm wrong. The recent `pure-callable` PR, and my work earlier this week on purity tracking means this is now possible.

**Comment by muglug** [comment]
With this fix Psalm now always keeps track of a closure's purity so we can decide whether or not the argument type is invalid.

**Comment by olleharstedt** [comment]
Hooray! :partying_face: Thanks!

**Comment by still-dreaming-1** [comment]
> Hooray! 🥳 Thanks! With this fix and wrapping side-effects in promises, it will be possible to do 100% pure business code. 😃

Actually that sounds like it might be what I have been looking for. What exactly do you mean by promises? I realize I'm commenting on a not super relevant comment within an already closed/fixed issue, but that might be exactly what I need. Can you point me to an example of clean code using Psalm to verify purity that does this?

Any other way I can think of to allow impure code to hook into pure code in PHP would cause Psalm to say none of it is pure. In something like Kotlin you can make all your classes data classes and use events to make all your impure code bubble out to the fringes, out of your "business code" as you say. That is legit because pure code is not responsible for what event listeners do (I don't remember if events is exactly the right term or not anymore, I did write a program using a similar technique in Kotlin once but it was a while back). In PHP and Psalm, I can't just call an impure interface method from a pure function and pretend that is okay because it's like an event. I mean, I guess I could and suppress the Psalm issue, but I'm looking for something cleaner than that. I also can't just pass in an impure closure or callable and call it from a pure function.

**Comment by olleharstedt** [comment]
Highly non-idiomatic code, but check this reddit thread: https://old.reddit.com/r/PHP/comments/ifnrvu/effect_types_in_php_using_psalm_and_amphp/

Another way to make more code pure, inspired by tagless-final pattern: http://olleharstedt.github.io/programming/2022/03/22/one-universal-mock-to-rule-them-all.html
