### ISSUE TITLE
[feature-request] @psalm-pure-if {type} $param

### ISSUE THREAD

**Issue by azjezz** [vimeo/psalm#4145]
I would like to see a new annotation added to psalm that allows defining functions as "pure" depending on their argument type.

example:

### before

```php
/**
 * @psalm-template Tk of array-key
 * @psalm-template Tv
 *
 * @psalm-param list<Tv>                    $values
 * @psalm-param (pure-callable(Tv): ?Tk)    $key_func
 *
 * @psalm-return array<Tk, list<Tv>>
 *
 * @psalm-pure
 */
function group_by(array $values, callable $key_func): array
{
    $result = [];
    foreach ($values as $value) {
        $key = $key_func($value);
        if (null === $key) {
            continue;
        }

        $result[$key]   = $result[$key] ?? [];
        $result[$key][] = $value;
    }

    return $result;
}
```

### after

```php
/**
 * @psalm-template Tk of array-key
 * @psalm-template Tv
 *
 * @psalm-param list<Tv>            $values
 * @psalm-param (callable(Tv): ?Tk)	$key_func
 *
 * @psalm-return array<Tk, list<Tv>>
 *
 * @psalm-pure-if (pure-callable(Tv): ?Tk) $key_fun
 */
function group_by(array $values, callable $key_func): array
{
    $result = [];
    foreach ($values as $value) {
        $key = $key_func($value);
        if (null === $key) {
            continue;
        }

        $result[$key]   = $result[$key] ?? [];
        $result[$key][] = $value;
    }

    return $result;
}
```

## Why?

In my case, in PSL, there's a lot of functions that work on arrays, almost all of them are defined as "pure", some take `callable` as an argument.

previously these functions were not considered pure as there was no way to guarantee that the callable itself is pure, however, after #4066, they switched to using `pure-callable`.

but this raises another problem, where the functions cannot be used in a non-pure context, but sometimes their functionality might be needed, and the developer is okay with the call resulting in mutation as their application is not mutation-free.

## Problem

I have a list of users I just fetched from the database, I wanna group these users by their status, but currently, I'm unable to use `Psl\Arr\group_by` as it only works in a mutation-free context where the callable I'm passing is not pure ( e.g fetches the user status from the database? ).

## Solution

`@psalm-pure-if (pure-callable(Tv): ?Tk) $key_fun` helps avoid this issues as it would be okay to pass a non-pure callable to `group_by`, but psalm would consider that call non-pure.

but if you were to pass a pure-callable, psalm would consider the function `group_by` to be pure, and it is okay to use in a pure context.

**Comment by azjezz** [comment]
This would also allow expending the parameter type as `group_by` would be able to take an `iterable` instead of `array` and act `pure` only if an `array` is passed 😃 so its a win-win.

**Comment by azjezz** [comment]
If this feature is implemented as specified, this should pass without any errors: https://psalm.dev/r/e40e70d90f

**Comment by azjezz** [comment]
@Ocramius would love to hear your opinion on this :)

**Comment by Ocramius** [comment]
Disclaimer: the following are thoughts formed while jumping through multiple tasks, so they aren't well-formed into something actionable.

Discussed in chat with @azjezz: the need for this kind of functionality certainly there, but we disagree on how it is to be delivered.

Some code can become pure/impure based on input parameters, which is very problematic to avoid duplication of anything that composes purely or impurely depending on arguments.

IMO, purity is more of a composed type of following inputs:

 * `psalm-immutable&array`
 * `psalm-immutable&object`
 * `psalm-immutable&callable`
 * `psalm-immutable&mixed`

These three are the types that can intersect with `psalm-immutable`, as far as I know.

Given the above, it may be possible to declare the return type as pure or not via `@psalm-return psalm-pure&T`.

I don't have a well formed mental model of how all this can work, but I think `@psalm-pure` is actually `@psalm-return psalm-pure&mixed` (implicitly), so that shifts purity from the declaration to the return statement.

Note that `@psalm-return psalm-pure&mixed` does not mean `@psalm-return psalm-immutable&mixed`.

My fear is that we start adding complex conditionals to the type system, whereas #3005 already implements conditional return types. If we managed to squish purity and immutability into parameters and return type declarations, we could match on the parameter types to use existing functionality  to build the output type.

**Comment by azjezz** [comment]
so in conclusion, the two options are:


## solution `a` ( proposed by @azjezz ):

```php
/**
 * @psalm-template Tk of array-key
 * @psalm-template Tv
 *
 * @psalm-param iterable<Tv>        $values
 * @psalm-param (callable(Tv): ?Tk)	$key_func
 *
 * @psalm-return array<Tk, list<Tv>>
 *
 * @psalm-pure-if (pure-callable(Tv): ?Tk) $key_fun
 * @psalm-pure-if array<array-key, Tv> 	   $values
 */
function group_by(array $values, callable $key_func): array
{
    $result = [];
    foreach ($values as $value) {
        $key = $key_func($value);
        if (null === $key) {
            continue;
        }

        $result[$key]   = $result[$key] ?? [];
        $result[$key][] = $value;
    }

    return $result;
}
```

- `group_by` is conditionally pure if `$key_fun` is of type `pure-callable`, and `$values` is `array<array-key, Tv>`
- `group_by` is safe to use in a pure context when an array and a pure callable are passed.
- `group_by` is safe to use in a non-pure context when any iterable/callable is passed.

### Solution `b` ( proposed by @Ocramius )


``` php
/**
 * @psalm-template Tk of array-key
 * @psalm-template Tv
 *
 * @psalm-param pure<iterable<Tv>>          $values
 * @psalm-param pure<(callable(Tv): ?Tk)>	$key_func
 *
 * @psalm-return array<Tk, list<Tv>>
 */
function group_by(array $values, callable $key_func): array
{
    $result = [];
    foreach ($values as $value) {
        $key = $key_func($value);
        if (null === $key) {
            continue;
        }

        $result[$key]   = $result[$key] ?? [];
        $result[$key][] = $value;
    }

    return $result;
}
```

- `group_by` is conditionally pure if `$key_fun` is pure, and `$values` is pure ( can be an iterator that is immutable )
- `group_by` is safe to use in a pure context when a pure iterable and a pure callable are passed.
- `group_by` is safe to use in a non-pure context when any iterable/callable is passed.

**Comment by muglug** [comment]
I feel like this is just a little too confusing. Pure functions are easy to understand if you have some FP experience (and they're discussed in Psalm's documentation). _Conditionally_ pure functions don't exist in other languages, far as I'm aware.

**Comment by muglug** [comment]
Yeah, I don’t see this landing in Psalm anytime soon, partly due to the complexity of verifying  this conditional purity.
