### ISSUE TITLE
Suppress InvalidScope via config

### ISSUE THREAD

**Issue by quisse** [vimeo/psalm#4168]
I want to suppress the InvalidScope error via config.

```
    <issueHandlers>
        <InvalidScope>
            <errorLevel type="suppress"/>
        </InvalidScope>
    </issueHandlers>
```

This doesn't work because `Psalm\Config` lacks support for it. `InvalidScope` extends from `CodeIssue` which is not checked
https://github.com/vimeo/psalm/blob/6d8641ac09cc4b1b2726639d09eb06f90eacea1f/src/Psalm/Config.php#L1393-L1433

I am willing to create a PR, adding the CodeIssue check to L1452-L1464 but I first want to check with the contributors if it will get accepted.

Reproducer: https://github.com/storefront-bvba/psalm-invalidscope-issue

**Comment by quisse** [comment]
@psalm-github-bot No, but I've added a reproducer repo.

**Comment by weirdan** [comment]
> InvalidScope extends from CodeIssue which is not checked
It should be handled by this `if`: https://github.com/vimeo/psalm/blob/6d8641ac09cc4b1b2726639d09eb06f90eacea1f/src/Psalm/Config.php#L1414-L1416

**Comment by weirdan** [comment]
This is not a bug. There are two types of suppression you can use in `psalm.xml`.
1. Suppress the issue everywhere:
    ```xml
        <InvalidScope errorLevel="suppress"></InvalidScope>
    ```
2. Suppress the issue in some file/dir/method/property/class/etc (`InvalidScope` can be suppressed on file/dir level only):
    ```xml
        <InvalidScope>
		<errorLevel type="suppress">
			<file name="bad.phtml" />
		</errorLevel>
        </InvalidScope>
    ```

But schema, unfortunately, does not require any specific tag as `<errorLevel>` content, so that also allow you to use
```xml
        <InvalidScope>
	    <errorLevel type="suppress"/>
        </InvalidScope>
```
which is useless, as it means 'suppress InvalidScope nowhere'.
