### ISSUE TITLE
Magic methods not recognized properly in plugin

### ISSUE THREAD

**Issue by mpesari** [vimeo/psalm#4190]
We have a magic method provider plugin which stopped working some time after the release 3.14.2 and was not fixed by 3.16.

I combed down the problematic commit to 9935f647abbbdbcb118cec5792fc22dfb64c1288, and have put some reproducable code into another repository: https://github.com/mpesari/psalm-issue-method-exists

I hope this helps find out what's going on.

**Comment by Daeroni** [comment]
Actually the provider we have (I work with @mpesari ) only returns false in doesMethodExist when the method name is `__call` as we have normal/native methods in our classes, and the provider must return null for those to allow Psalm to check for those. If we don't return false for `__call`, Psalm will not notice any method calls our `__call` method doesn't handle.

It seems the commit 9935f64 / 09abf46 added some checks for the `__call` method, maybe related?

Also https://github.com/vimeo/psalm/blob/8c7423505a4282d1cdd38f3ff9552b911cbd5fa9/src/Psalm/Internal/Analyzer/Statements/Expression/Call/Method/AtomicMethodCallAnalyzer.php#L527 gets different value after the commit for the magic methods.

Here is a bit modified code reproducing the issue: https://github.com/Daeroni/psalm-issue-method-exists

**Comment by mr-feek** [comment]
Ah I have just run  into this exact same issue and was about to report it, I also narrowed it down to the same commit. This is why the laravel plugin's tests are failing. cc @muglug 

In my case, I believe it is because the class we have a provider for does not have an `__call` method (although I have not double checked yet).

failing test: https://github.com/psalm/psalm-plugin-laravel/runs/1278277175#step:4:106
provider file: https://github.com/psalm/psalm-plugin-laravel/blob/master/src/AppInterfaceProvider.php

**Comment by mpesari** [comment]
Solved this by using the EventHandlerInterfaces. Nice example at [https://github.com/vimeo/psalm/blob/4.4.0/tests/Config/Plugin/Hook/FooMethodProvider.php](https://github.com/vimeo/psalm/blob/4.4.0/tests/Config/Plugin/Hook/FooMethodProvider.php)
