### ISSUE TITLE
Expand psalm-internal functionality

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#4218]
Right now, ``psalm-internal`` allows namespace-limited access. Can we have fine-tuning it to class, or even method? Class-limited access is very similar to concept of [friends](https://wiki.php.net/rfc/friend-classes), method limited access is even better.

Overly simplified example:

```php
class User
{
    /**
    * @internal
    * @psalm-internal Payment::__construct
    */
    public float $balance = 0;
}

class Payment
{
    public function __construct(User $user, float $amount)
    {
        $user->balance += $amount;
    }
}
```

Any access to ``User::balance`` outside of ``Payment::__construct`` would trigger error.

---

This is also useful for factory pattern that allow easy setup just by implementing interface:

```php
interface UserCreateInterface
{
    public function setDefault(User $user): void;
}

class UserFactory
{
    /** @var UserCreateInterface[] */
    private array $taggedServices;
    
    public function create(): User
    {
        $user = new User();
        // each tagged service would set something like default access role, balance etc...
        foreach($this->taggedServices as $modifier) {
            $modifier->setDefault($user);
        }
        
        return $user;
    }
}

/** @psalm-suppress PropertyNotSetInConstructor */
class User
{
    /**
    * @internal
    * @psalm-internal UserFactory::create
    */
    public function __construct()
    {
    }
}
```

**Comment by muglug** [comment]
cc @bdsl for thoughts

**Comment by bdsl** [comment]
Interesting ideas. The use cases are not completely clear to me at the moment though.

Why would you limit a class property to access only within one method? Isn't that what a local variable is for?

The UserFactory seems like a useful pattern, but why not just make a namespace for the User and UserFactory classes to live in together?

Otherwise I wonder if a new `@friend` annotation would be a good solution. Maybe a friend would be allowed to override all `@internal` / `@psalm-internal` restrictions. 

I do think it would make sense for it to make something `@internal` to a class - that's just a slight extension to the concept of being internal to a namespace, especially if you think a namespace is nothing but the beginning of one or more FQCNs, but beyond the fact that it makes sense as a concept I didn't really see a use case for it. We already have the keyword `private` for things that are internal to a class.

On the other hand using `@psalm-internal` instead of `private` might have advantages in a few cases. Perhaps you want to allow yourself to suppress the warning and access internal stuff from outside the class in a few special cases and you don't want to have to bother with reflection to do it. And it would be much more useful if we had the `@friend` annotation to go with it.

**Comment by zmitic** [comment]
>Interesting ideas. The use cases are not completely clear to me at the moment though.

>Why would you limit a class property to access only within one method? Isn't that what a local variable is for?


Let me explain the first example better:

```php
class User
{
    /**
    * @internal
    * @psalm-internal Payment::__construct
    */
    public float $balance = 0;
}

class Payment
{
    public function __construct(User $user, float $amount)
    {
        $user->balance += $amount;
    }
}
```

The idea of limiting access to specific method is because ``balance`` is increased **only** when new ``Payment`` is created; it would be irrelevant **where** that Payment instance is created. It could be from [form](https://symfony.com/doc/current/form/use_empty_data.html#option-2-provide-a-closure), controller, some factory service... 

Because it is public property, it would be easy to make a mistake and access it directly; with protection like in this example, such mistake would be spotted.

Better example would be method like ``addAmountToBalance(float $amount)`` instead of property but it is basically the same; that is why I put simpler example. And it is isn't something wrong in such architecture; I found more than 100+ ``@internal`` annotations in /vendor (PHPStorm stops at 100).

---

>but why not just make a namespace for the User and UserFactory classes to live in together?

Because that would force me to structure code around this limitation. In this particular case, I use ``App\Entity\User`` and ``App\Repository\UserRepository`` (not exactly like that but close). One is an entity, other is service and entity folder is excluded from compiler analysis (speed reasons).

>And it would be much more useful if we had the @friend annotation to go with it.

Totally agree, I just didn't want to make things more complex. Also; ``friend`` exposes **all** properties/methods, my suggestion would be to make precise definitions.

**Comment by zmitic** [comment]
One more example for targeting specific property/method. If I delete ``Payment``, I also need to decrease balance:

```php
class Payment
{
    /** @PreRemove */
    public function reduceBalanceOnRemoval(): void
    {
        $this->user->balance =- $this->amount;
    }
}
```

This is Doctrine's event. So User becomes:

```php
class User
{
    /**
    * @internal
    * @psalm-internal Payment::__construct
    * @psalm-internal Payment::reduceBalanceOnRemoval
    */
   public float $balance = 0;
}
```

Thus aggregate column cannot be modified by anyone else, except by ``Payment``.

**Comment by zmitic** [comment]
[Fixed](https://psalm.dev/r/687c3da72a), thank you.
