### ISSUE TITLE
ignoreFiles must exists to run psalm

### ISSUE THREAD

**Issue by MaxBoeh** [vimeo/psalm#4238]
Our psalm configuration contains a directory that should be ignored:
```xml
   <projectFiles>
       <ignoreFiles>
           <directory name="tests/_support/_generated" />
        </ignoreFiles>
    </projectFiles>
```

In our CI environment we get this error message and exit with status code 1 (breaks the build):

> Problem parsing /builds/\<my-project\>/psalm.xml:
>   Could not resolve config path to /builds/\<my-project\>/src/\*/\*/tests/_support/_generated/

The reason is, that the tests are run in another job, so the generated support classes are not visible to psalm.
We can not remove the ingoreFiles-directive, as we need it in our dev environment.

Is there a way that psalm does not die when a folder, which it should ignore anyway, does not exist?

Might be related to #4025

**Comment by ddeboer** [comment]
This is essential for Symfony projects as well. Since [5.1.6](https://symfony.com/blog/symfony-5-1-6-released) Symfony [generates a `.preload.php` file](https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading), which Psalm seriously chokes on (probably because of an infinite recursion). The problem is that `.preload.php` file will only exist after clearing the Symfony cache, so if you run Psalm before that (e.g. on CI) the file will not exist yet.
