### ISSUE TITLE
False positive on Exception::getCode

### ISSUE THREAD

**Issue by pattisahusiwa** [vimeo/psalm#4295]
Only `PDOException` can return a `string` error code, everything else will return `int`.

https://www.php.net/manual/en/class.pdoexception.php
```php
PDOException extends RuntimeException {
    /* Properties */
    public array errorInfo;
    protected string code;
    
    /* Inherited properties */
    protected string message;
    protected int code;
```

https://www.php.net/manual/en/class.exception.php
```php
Exception implements Throwable {
    /* Properties */
    protected string message ;
    protected int code ;
```

**Code to reproduce**
https://psalm.dev/r/e785986fc0

**Expected result**
No Error. Psalm should distinguish `PDOException` from others.

Related commit: 53cd878694d680fb32be4a8d5be35c8eb21c2c64

**Note:**
How to solve this conflict?
https://psalm.dev/r/b44df0b0e1

Another side effect:
https://3v4l.org/Ya32I

**Comment by morozov** [comment]
Another relevant example that uses `Throwable::getCode()`: https://psalm.dev/r/902effb53d.

**Comment by muglug** [comment]
@morozov but `PDOException` is a `Throwable`, so that's not wrong

**Comment by morozov** [comment]
My point is that Psalm incorrectly determines the return type of `Throwable::getCode()` which (unlike `Exception`) is [documented](https://www.php.net/manual/en/throwable.getcode.php#refsect1-throwable.getcode-description) as `int`. Although now I see that the documentation is ambiguous.

**Comment by hrs-o** [comment]
I also think this is a bug.
Will there be a fix?

It is clearly stated that Exception::getCode will return int.
`final public Exception::getCode(): int`
https://www.php.net/manual/en/exception.getcode.php

https://psalm.dev/r/e9a0196ef3


--

```php
<?php

$e = new PDOException("a", 1);
var_dump($e->getCode());

/**
int(1)
 */
```


```php
<?php

$e = new PDOException("a", "a");
var_dump($e->getCode());

/**
Fatal error: Uncaught TypeError: Exception::__construct(): Argument #2 ($code) must be of type int, string given in /src/tmp/test.php:3
Stack trace:
#0 /src/tmp/test.php(3): Exception->__construct('a', 'a')
#1 {main}
thrown in /src/tmp/test.php on line 3
 */
```

**Comment by weirdan** [comment]
> It is clearly stated that Exception::getCode will return int.

Or it's clearly stated that

> Return Values 
> Returns the exception code as int in Exception but possibly as other type in Exception descendants (for example as string in PDOException).

Depending on what section you're looking at, on that same page.

**Comment by hrs-o** [comment]
@weirdan thank you.

Thanks.
I understand that several Exceptoin such as PDOException return a string, but is that more standard for that case?

At least the \Exception class will not return a String in getCode.

MyException is clearly int, but InvalidScalarArgument is output.
I understand that it is int|string depending on the stub.

https://psalm.dev/r/fe62209c12

**Comment by niconoe-** [comment]
I encountered this for the first time today and it took me a while to understand why Psalm says my variable from `$code = $exception->getCode();` could be a string while it's definitly an int (my exception is not a PDOException nor child of it). 

I think Psalm should be able to determine which is the good type depending on the kind of Exception object, but I honestly have no idea how to help in providing this behavior.

**Comment by orklah** [comment]
@niconoe- The original example is indeed a bug. LogicException is a known Exception and `LogicException::getCode` is documented in Callmap as an `int`, so it shouldn't return `int|string`.

However, this: https://psalm.dev/r/eb45611005 is a normal issue because Psalm can hardly know the type of `$e`.

To solve the latter issue, I see 2 solutions:
- create a stub for Exception that declare `Exception::getCode` can only return int. This is not recommended for projects that use PDO for obvious reasons
- implement a new module in Psalm that will analyse `@throws` docblock for every called method/function in a Try{} block, make a combination of every Exception and call `getCode` on that. If there's no `PDOException` and no `Exception` in the mix, it should return int. It requires a pretty good @throws coverage that can be achieved through `checkForThrowsDocblock` config

**Comment by niconoe-** [comment]
Ok, I understand. Thinking about basic cases like those is trivial but working with functions/methods calls in a try{} block that could throw anything is a little bit harder. 

I actually decided to ignore this error as my case is a little bit more complex actually, but I'm fine with ignoring it due to the complexity of this "bug" I wasn't aware of.

Nevertheless, maybe this module you're talking about could be part of Psalm itself, as even the decision to set the return value of `Exception::getCode()` to `int|string` is actualy wrong.

Here is an example of `Exception::getCode()` being executed for every types I could (excluding `resource` or special objects like `Generators`) and as you can imagine, its return could be anything: https://3v4l.org/36m23

Psalm version: https://psalm.dev/r/d421cb861a

With Psalm trace, you can see that `$code` is wrongly defined to `int|string` as it is actually a lot more.
Maybe `int|string` covers 99.9999% of the cases because everyone is using `int` or `string` for Exception's codes, but in a purely technical point of view, it's `mixed`. Probably because even if PHP says `Exception::getCode(): int` in the docs, it's actually not the case as `PDOException::getCode(): string` and `MyCustomException::getCode(): mixed` are all valid: PHP is lying about the return type of `Exception::getCode()` and it's internally probably not typed (a.k.a mixed).

That's why my opinion on this is Psalm should either consider the return of `Throwable::getCode()` to `mixed` or try to infer the actual type of `Throwable::getCode()` based on the possible exceptions that might be thrown in a try{} block (and also intersected with types of the `catch` argument's `getCode`). Like you module proposition should do.

What do you think about?

Of course, it could be even better if PDO could stop using strings for codes and provide a specific dedicated property instead... (and better: an RFC in PHP to force `int` return type for `Throwable::getCode()`).

**Comment by orklah** [comment]
Wow, your example is actually pretty weird, you bypassed type checks for Exception::code by not using parent::__construct($code) (https://3v4l.org/tJ2sn) and by redefining the property instead. I wish PHP would have added a check here as well but this was probably not possible to accomodate PDOException weirdness. This is however a big edge case and purely designed to bypass such checks...

IIRC, the reason why PDO use strings sometimes is because it have to return sql errors that are not purely integer based. Seems unlikely to change.

The module I talked about would be a lot of work and complexity compared to benefits, not sure it's worth it just to restrict the type of getCode...

**Comment by niconoe-** [comment]
This is not about the parent checks actually. Look at: https://3v4l.org/N9jWG.

I just used a promoted constructor to store the property `$code` at `MessyCodeException` level, not using it at `LogicException`, or `Exception`, or `Throwable` level.

Like I said, I'm pretty sure the `Throwable::getCode()` method is not well documented [here](https://www.php.net/manual/en/class.throwable.php) for instance, as it is not `Throwable::getCode(): int` but either `Throwable::getCode(): mixed` or `Throwable::getCode()` (probably because of PDOException). Therefore, Psalm, by default, should not be able to infer the return type to `int|string`.

And, as Psalm shouldn't be able to infer the return type, adding this complex parsing rule would make it learn to infer the actual return type as expected.

But I also understand your concern as this is really edge cases, so maybe the best way to clean this up is to provide an RFC to PHP internals and actually force `Throwable::getCode(): int`.

> IIRC, the reason why PDO use strings sometimes is because it have to return sql errors that are not purely integer based. Seems unlikely to change.

I heard about this too, and I don't think that's only a short term issue: PDOException and children could have a property `protected string $sqlCode` and a method `::getSQLCode()` (names are to determine), and leave the `int $code` to PHP Core and stop overriding it. It could be done accross several versions with communications and deprecations, but even if it takes 4~5 years to finally get rid of this behavior, it would clean both PDO and PHP Core.

**Comment by VincentLanglet** [comment]
This issue is more important now because phpstan infer the `getCode` return type since https://github.com/phpstan/phpstan-src/commit/e04cc8dfb8f6b3a2c4ac399232a6691baed1d162

Which means that if you cast to int to please psalm, you ends with a phpstan error "useless cast", but if you don't do it, you ends with a psalm error about `int|string`.

You can see here https://phpstan.org/r/1192e2bc-3506-41e8-ab1d-08c4faf77961
that PHPStan consider that
`\Exception` and `\Throwable`  can return int|string but extending them is restricting the type to `int`
`\PDOException` and extensions are returning `string`
Everything else is returning `int`.

What would be the easiest way to introduce this behavior to psalm @orklah ?

**Comment by orklah** [comment]
@VincentLanglet can you give me an example of code where PHPStan emits an useless cast and where Psalm return int|string?

**Comment by VincentLanglet** [comment]
> @VincentLanglet can you give me an example of code where PHPStan emits an useless cast and where Psalm return int|string?

Sure, https://phpstan.org/r/d0a810ac-3cbb-4997-a73d-dfc42c4c0caa (useless cast with strict-rules)
vs https://psalm.dev/r/1ba5a34259

**Comment by orklah** [comment]
Ok, I see. So every child of Exception has a getCode that returns int even though Exception::getCode returns int|string. That's a bit unorthodox but it could work.

I think a ReturnTypeProvider for 'Exception' should work, the only caveat is that it must distinguish Exception from childs of Exception (and also PDOException)

**Comment by VincentLanglet** [comment]
> I think a ReturnTypeProvider for 'Exception' should work, the only caveat is that it must distinguish Exception from childs of Exception (and also PDOException)

I can try, if I understand correctly, it should be
```
public static function getClassLikeNames() : array
{
    return ['Throwable'];
}
```
I can check that `$event->getMethodNameLowercase() === 'getcode', 
and then how do I check the class/interface it's call on ?

I need to know
- If it's PDOException or a child of PDOException -> string
- If it's exactly Exception or Throwable -> int|string
- Else -> int

**Comment by orklah** [comment]
exactly :)

**Comment by VincentLanglet** [comment]
> how do I check the class/interface it's call on ?

Do you know how can I do this check ?

**Comment by orklah** [comment]
getCalledFqClasslikeName in the event should give you the correct class I believe
