### ISSUE TITLE
Getting InvalidPropertyAssignmentValue instead of MissingDocblockType 

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#4448]
These both should be MissingDocblockType:

```php
trait ExampleTrait
{
    /** @var array */
    private $list;

    function __construct(array $list)
    {
        /** @var $this Example */
        $this->list = $list;
        
        /** @var $foo Example */
    }
}

class Example 
{
    use ExampleTrait;
}
```

Yet: https://psalm.dev/r/a873d01130

```
ERROR: InvalidPropertyAssignmentValue - 10:23 - $this->list with declared type 'array<array-key, mixed>' cannot be assigned type 'Example&static'

ERROR: MissingDocblockType - 12:0 - Misplaced variable
```

**Comment by weirdan** [comment]
Should it though? `$this` is also a valid type (most commonly used with `@return $this`), and Psalm does not require variable name for `@var` docblocks on expressions. And `Example` there might just be a textual descriptions.

**Comment by sanmai** [comment]
How about this explanation:
- If I'd receive `MissingDocblockType`, I would immediately notice what is the problem. 
- Fixing the docblock type [fixes the problem](https://psalm.dev/r/8a2fdbe1cb).
- `InvalidPropertyAssignmentValue` is downright confusing in this situation.

**Comment by sanmai** [comment]
> Psalm does not require variable name for `@var` docblocks on expressions.

Yet there's `MissingDocblockType` isn't it?

**Comment by weirdan** [comment]
> Yet there's MissingDocblockType for clauses like /** @var $foo Example */ isn't it?

That's because `$foo` is not a type, but `$this` is.

This can be solved only by forbidding using `$this` as a type in `@var` docblocks, which seems to be rather arbitrary limitation.

**Comment by weirdan** [comment]
Having thought about this for a while I don't think this needs to be changed.

**Comment by sanmai** [comment]
Right, how about changing the error message a bit?
```diff
-$this->list with declared type 'array<array-key, mixed>' cannot be assigned type 'Example&static'
+$this->list with declared type 'array<array-key, mixed>' cannot be assigned type '$this'
```
Then it'll be much more obvious. What do you think?

**Comment by weirdan** [comment]
Well, the message itself is something like this: `%s with declared type '%s' cannot be assigned type '%s'`. I'm not sure how hard it is to preserve the original `$this`.

Alternatively, though, Psalm could warn about ambiguous (not to the Psalm itself, but for human readers) `@var` docblocks. Something along the lines of:
```
Ambiguous off-label @var docblock, assuming $this->list is '$this' (Example&static), not 'Example'.
```

**Comment by orklah** [comment]
Sorry, this is technically complicated (we're not going to create a new issue for this and `MissingDocblockType` is pretty specific in Psalm because it's highly related to parsing issue so simply changing the wording of this instead seems out of the question).

The benefit is too small for the added complexity and as far as I can tell, there was no other complaints for this in years so I don't see this changing anytime soon.
If you still feel strongly about this, feel free to suggest a PR fixing the issue.

**Comment by sanmai** [comment]
Things are what they are, that's not a problem. Do y'all have plans to document `$this` in traits? Or is this a done deal?

**Comment by AndrolGenhald** [comment]
@sanmai You can use [`@psalm-require-extends`](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-require-extends) and [`@psalm-require-implements`](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-require-implements). Otherwise, you can do `get_class($this) === SomeClass::class` checks inside the method.

**Comment by orklah** [comment]
Also, we have an undocumented @psalm-scope-this (https://github.com/vimeo/psalm/blob/b49682a4853803f72996fbd6664b5e69a75472ae/tests/TypeReconciliation/ScopeTest.php#L196) but I'm not sure if it can be used in traits
