### ISSUE TITLE
Spaceship operator returns -1|0|1

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#4478]
https://psalm.dev/r/23ba9a3dd1

**Comment by weirdan** [comment]
I think this could be easily fixed in https://github.com/vimeo/psalm/blob/724b25b9184afbc6ef9339f8868d0a62b384366d/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php#L163-L164 and https://github.com/vimeo/psalm/blob/62e79fb7ea18419817af918072a9deffb9890478/src/Psalm/Internal/Analyzer/Statements/Expression/SimpleTypeInferer.php#L102-L104
