### ISSUE TITLE
@inheritdoc not being respected for array types

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#4504]
https://psalm.dev/r/8c7cf07380

Adding the PHPDoc for `$arr` in `Bar::__construct()` does solve the issue, but it feels like the `@inheritdoc` should pull the exact array type from `Foo`.

**Comment by orklah** [comment]
@inheritdoc is considered at some level, but for most cases, it's not even needed because it's the default behavior. In fact, your example works if you change the name of the method.

However, __construct has a special case in Psalm. The signature of a constructor is not preserved, unless the class is flagged with a `@psalm-consistent-constructor`. This flag will make Psalm check if __constructor are coherent and then it will allow  inheriting the signature.

Here's the fix for your example: https://psalm.dev/r/18cde61d9c
