### ISSUE TITLE
Problem with IteratorIterator and @template

### ISSUE THREAD

**Issue by thomasvargiu** [vimeo/psalm#4513]
https://psalm.dev/r/ea5148ab32

Probably related issues:
- #2761
- #3353

**Comment by muglug** [comment]
I think this has to be a `wontfix`, due to the lack of generics in the actual language (in TypeScript, Hack etc. you could explicitly call the constructor with `new MyIterator<int, string, Traversable<int, string>>($arr)` but that's not possible here. It's out of Psalm's scope to infer the nested `TIterator` type (as sometimes the inference must run the other way).
