### ISSUE TITLE
PropertyNotSetInConstructor for Symfony entities 

### ISSUE THREAD

**Issue by marcu87** [vimeo/psalm#4677]
So we are using php 7.4 + Symfony 5.1; and we have an entity as this:

```
class Foo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $name;

    /**
     * @ORM\Column(type="string")
     */
    private string $email;
```

Problem is Psalm is saying `ERROR: PropertyNotSetInConstructor` for all the fields, because they don't have any default value, neither we have a Constructor where we define that. 

So, one posible solution is to just ignore the error:

`@psalm-suppress PropertyNotSetInConstructor`

and that's a fair solution, but we were thinking if there is another better aproach, instead of just ignoring the error.

here an example: https://psalm.dev/r/630449e3a0

Anybody using Symfony with php 7.4 and had this kind of issue?

Thanks!

**Comment by zmitic** [comment]
@marcu87 I am using Symfony. My guess here is that you bind entities to forms and that is why you don't have ctor, right?

If so, use ``empty_data``. I am sure you don't want to use this suppression, there are no guarantees that setters will be called; psalm should not fix this issue.

Also; fixtures.

---

Or try this bundle temporarily: https://github.com/hitechcoding/strict-form-mapper-bundle/blob/master/docs/factory.md

No problems with it but I making even better one. Same API so a simple replace will do the job once finished.

**Comment by DanielBadura** [comment]
Well this issue is not bound to symfony. You cannot access properties without setting a value to it. So psalm is reporting here this issue which is true since you cannot be sure that the value is set since the ctor doesnt exist. See this here as an example: https://3v4l.org/YOMLO

If you want to be safe and fix this issue you will need to add a ctor which needs the properties or you set default values (this can be done in ctor or at the property itself). 

The last issue you will encouter is that your id for the entity is not decided by the application but by the database so this will get a little bit tricky.

**Comment by zmitic** [comment]
>The last issue you will encouter is that your id for the entity is not decided by the application but by the database so this will get a little bit tricky.

```php
public function getId(): int
{
    return $this->id ?? throw new RunTimeException('Save your entity first');
}
```

---

Better solution is to use ``uuid`` and assign immediately in ctor (solves some other problems as well):

```php
    public function __construct()
    {
        $this->id = Uuid::uuid4();
    }

    public function getId(): UuidInterface
    {
        return $this->id;
    }
```

**Comment by hutnikau** [comment]
Would be great to have possibility to suppress this error message. 
Especially with generated values, such as identifiers, current datetime, etc. In doctrine such values set after entity saved, so you must not specify them in the constructor.

**Comment by DanielBadura** [comment]
You have already 3 options to ignore this error.

1. Add it in the `psalm.xml` to ignore `PropertyNotSetInConstructor`
2. Add the ignore at the postion in the code where the violation is with `@psalm-suppress PropertyNotSetInConstructor`
3. Add the message to your `baseline.xml`

For more information look here: https://psalm.dev/docs/running_psalm/dealing_with_code_issues/

But i would really recommend to fix the problem itself instead of ignoring it.

**Comment by orklah** [comment]
The issue reported here is legit. Howevver, please make sure you have psalm doctrine plugin installed. If anything, this kind of specific handling should me made by the plugin.

If after installing the plugin, you still observe those issues, feel free to create an issue there.

Otherwise, as @DanielBadura said, Psalm allow multiple ways to suppress issues

**Comment by hutnikau** [comment]
@orklah @DanielBadura thank you for quick response!
Both solutions works for me.

**Comment by ThomasLandauer** [comment]
Just initialize all nullable fields with `null` - that's enough :-)
In your example:
```php
private ?int $id = null;
private ?string $name = null;
private string $email; // no change
```

**Comment by orklah** [comment]
I believe this was fixed in the plugin today: https://github.com/psalm/psalm-plugin-doctrine/commit/b9dc2484b8bc1d43dc6e5c4305efa251624cb174

If some of you can try the change on 2.x branch, I'll make a new release there
