### ISSUE TITLE
MixedAssignment Error on $reflectionClass->getAttributes() with errorLevel="1"

### ISSUE THREAD

**Issue by simon-schubert** [vimeo/psalm#4779]
When i run the code https://psalm.dev/r/b235a94073 with errorLevel="1"

I get an MixedAssignment error. I think the main problem is, that psalm cannot infer the result of
```php 
$reflectionClass->getAttributes(HttpApi::class)
```

The exact error output is:

```sh
ERROR: MixedInferredReturnType - src/HttpApi/HttpApiReader.php:24:46 - Could not verify return type 'TerryApiBundle\HttpApi\HttpApi' for TerryApiBundle\HttpApi\HttpApiReader::read (see https://psalm.dev/047)
    public function read(string $className): HttpApi


ERROR: MixedAssignment - src/HttpApi/HttpApiReader.php:29:73 - Unable to determine the type that $attribute is being assigned to (see https://psalm.dev/032)
            foreach ($reflectionClass->getAttributes(HttpApi::class) as $attribute) {


ERROR: MixedReturnStatement - src/HttpApi/HttpApiReader.php:30:24 - Could not infer a return type (see https://psalm.dev/138)
                return $attribute->newInstance();;


ERROR: MixedMethodCall - src/HttpApi/HttpApiReader.php:30:36 - Cannot determine the type of $attribute when calling method newInstance (see https://psalm.dev/015)
                return $attribute->newInstance();;
```

Is there any way I could annotate it or is this a bug?

**Comment by simon-schubert** [comment]
I'm using "version": "4.3.1"

**Comment by weirdan** [comment]
Are you running this on PHP 8?

It looks very similar to the test failure we have on AppVeyor (PHP 8) builds: https://ci.appveyor.com/project/muglug/psalm/builds/36655342#L615

The failing test is this:
https://github.com/vimeo/psalm/blob/4a0e2f543e4921820e547774c2503fa7f7ada630/tests/AttributeTest.php#L206-L226

**Comment by simon-schubert** [comment]
I get the same behavior on PHP 7.4 and PHP 8.0. E.g. in CI its running under PHP 7.4: https://github.com/simon-schubert/terry-api/pull/97/checks?check_run_id=1501055982

And yes, it looks like the problem that causes this test to fail could be the same one. Thanks!

**Comment by weirdan** [comment]
My theory about what is happening here is that it's basically two different things with similar (but not the same) effect.

### Running on PHP 8

Psalm tries to figure out the minimum PHP version your project supports (see [`\Psalm\Config::getPHPVersionFromComposerJson()`](https://github.com/vimeo/psalm/blob/3f155792a778f0c215fe242bdc5e4202e2d137be/src/Psalm/Config.php#L2141)), and that appears to be lower than 8. When it gets to loading the [`ReflectionClass` stub](https://github.com/vimeo/psalm/blob/3f155792a778f0c215fe242bdc5e4202e2d137be/stubs/CoreGenericClasses.phpstub#L2103), it sees [`getAttributes()`](https://github.com/vimeo/psalm/blob/3f155792a778f0c215fe242bdc5e4202e2d137be/stubs/CoreGenericClasses.phpstub#L2151) as absent (because it's annotated with `@since 8.0`). But when it gets to the call analysis, it sees `getAttributes()` via reflection. But reflection does not provide the generic annotation Psalm needs, and so it infers `ReflectionClass::getAttributes()` return value to be `array<array-key, mixed>`.

### Running on PHP 7

Here Psalm is not smart enough to detect that `if (\PHP_VERSION_ID >= 80000)` makes its body essentially unreachable code. So it goes there, sees a call to unknown method and infers it's result as `mixed`.

It doesn't fail on psalm.dev because there default PHP version [is set to 8.0](https://github.com/psalm/psalm.dev/blob/ea137f32b81e87919b11d546db412eafcaccfd4a/views/check.php#L52), even though Psalm runs on 7.3 there.

### Conclusion

Try experimenting with setting PHP version to 8.0 either in `psalm.xml` or with the cli switch.

**Comment by simon-schubert** [comment]
your assumptions seem to be correct, changing phpVersion to 8.0 solves the issue on 7.4 and 8.0:

7.4: https://github.com/simon-schubert/terry-api/pull/97/checks?check_run_id=1502772437
8.0: https://github.com/simon-schubert/terry-api/pull/97/checks?check_run_id=1502772447

Thank you very much!
