### ISSUE TITLE
Input param not traced when covariance changes

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#4803]
Example: https://psalm.dev/r/0f0ce4be1e

#### Explanation 

Just by changing return type of ``CovariantUserBuilder::create``, psalm doesn't trace ``$data`` param correctly.

**Comment by weirdan** [comment]
Simplified a bit: https://psalm.dev/r/fc69cedcb9

**Comment by muglug** [comment]
This is a very buggy bug

**Comment by orklah** [comment]
If you need some more example, I believe there is a similar issue in phpDocumentor codebase with last psalm release. I could try to dig it out.

**Comment by muglug** [comment]
The fix, for now, is to use the same param types as would be evaluated when calling the method externally.

Because you're defining a different return type from the one you inherited, that means `$data` is now typed to `mixed`.

This follows the rule introduced in 4.2.0: a function signature (parameter and return types) can only come from one method. If you redefine either a parameter type or a return type in a child method, that method must also provide local param types.

**Comment by zmitic** [comment]
>that means $data is now typed to mixed

I set ``reportMixedIssues="true"``; does this mean the fix will report problems?

**Comment by muglug** [comment]
You get a `MissingParamType` issue instead

**Comment by muglug** [comment]
Actually this code will be allowed just fine, sorry, false alarm.
