### ISSUE TITLE
Allowed memory size of 536870912 bytes exhausted (tried to allocate 40960 bytes)

### ISSUE THREAD

**Issue by mrbenosborne** [vimeo/psalm#4844]
Hi all,

I have run the command:

```
./vendor/bin/psalm --set-baseline=psalm-baseline.xml --use-ini-defaults
```

But Psalm is ignoring my memory_limit set in php.ini.

If I run the following command to check my .ini file:

```
php -i | grep "memory"
```

It shows the correct memory:

```
memory_limit => 2048M => 2048M
```

Can someone help with this?

**Comment by mrbenosborne** [comment]
Can not be reproduced on https://psalm.dev.

**Comment by orklah** [comment]
I had this error a lot when I started using Psalm. Turns out I had set_memory_limit() calls outside classes that were included with autoloading. PHP was executing them and immediately crashed because I was already above the limit.

Maybe that's your case too. They are pretty tricky to find, you could use --debug-by-line but the analysis may crash several files after the function.

**Comment by mrbenosborne** [comment]
Hey @orklah ,

Thanks, let me give that a go and I'll let you know :+1:

**Comment by mrbenosborne** [comment]
You were correct @orklah there was one ini_set line floating around in the code base!

Apologies! Thanks :+1:  works like a charm now.
