### ISSUE TITLE
Incorrect type inference for generator

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#4852]
If first yield expression meets after new expression then psalm treats closure as regular closure, not generator:

https://psalm.dev/r/8453609ca7

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/bb45612e15

**Comment by orklah** [comment]
I'm working on something around that. Just in case I end up giving up on it and forget this, this issue can be fixed by adding `|| $node instanceof PhpParser\Node\Expr\New_` here: 
https://github.com/vimeo/psalm/blob/64df00baba61af63af4cf42ab1489cc43a959974/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php#L346
