### ISSUE TITLE
Not ignoring `@phpstan-param`

### ISSUE THREAD

**Issue by patrickkusebauch** [vimeo/psalm#4867]
Kind of relates to https://github.com/vimeo/psalm/issues/4866

Since Psalm is not able to provide additional info, I want to use `@phpstan-param` to add the info specifically to PHPStan, however, Psalm won't let me: https://psalm.dev/r/640ca7dde0. 

What is worse, Psalm won't even let me suppress the problem. IMHO Psalm has no business taking into account any `@phpstan-*` annotation.

**Comment by orklah** [comment]
I looked into it, and it seems hard to ignore docblock issues only for phpstan tags. Psalm combine all phpdoc source (@param, @phpstan-param, @psalm-param) in this order before trying to parse the content. Once we parse it, we don't know the source anymore to ignore it.

I was surprised however that psalm couldn't take advanced array syntax in callable. Turns out it can, what it can't is reading a callable when the name of the argument is specified AND there is advanced arrays.

I guess the parser could be improved but in the meantime, you could avoid specifying the argument, and psalm will accept it:
https://psalm.dev/r/23c336ba53

**Comment by jasverix** [comment]
Is it possible to look into this? I am getting a lot of errors from Monolog now because of @phpstan annotations. There is a reason for using a prefix. I really do not understand why psalm should read those at all.

Psalm just got completely unusable until Monolog fixes their annotations, or you add a possibility to prevent @phpstan annotations (but the error is clearly on psalms part).

**Comment by orklah** [comment]
Prefixes exist to differentiate static analysis tools from classic Phpdoc. Unfortunately, as there is no common annotation between SA tools, each tool is forced to read annotation from the other. PHPStan does this as well for Psalm annotations and it leads to the same kind of issues.

It doesn't make sense for Psalm to have a config to stop reading PHPStan annotation because you can't control every vendor, so there is a high probability for new errors to appear if Psalm is forced to revert back to standard phpdoc instead of interpreting PHPStan's annotations.

There are two solutions here:
- either the parser is improved in order to read the specific notation in the original snippet
- either we manage to make Psalm understand that if there is a psalm annotation, it shouldn't report issues in PHPStan ones (while still reading them if there's no Psalm one)

I lack time for the moment to look into this but you're more than welcome to contribute and propose a PR: https://psalm.dev/docs/contributing/

**Comment by weirdan** [comment]
The original issue is no longer reproducible: https://psalm.dev/r/640ca7dde0
