### ISSUE TITLE
Multiple Classes in the same File

### ISSUE THREAD

**Issue by simonbethke** [vimeo/psalm#4981]
I have this sketch:
https://psalm.dev/r/226b4245a6

Problem is, that it seems as if psalm is only analyzing the first instance of
private $firstChild;
in the file dom_c.php. The problem seems to be, that doc_c.php contains multiple classes and later on in the class DOMElement, the private field firstChild should be of type DOMElement... however, psalm thinks it is DOMNode, which is the first declaration in the file.

**Comment by weirdan** [comment]
Can you elaborate? What files are you referring to?

**Comment by simonbethke** [comment]
The file I am referring to is "doc_c.php". The important portions in this file are:

`class DOMNode  {
    /** @var DOMNode|null */
    public $firstChild;
}
class DOMElement extends DOMNode implements DOMParentNode, DOMChildNode {
    /** @var DOMElement|null */
    public $firstChild;
}`

In the sample code, the instance is of type DOMElement, but psalm thinks that DOMElement has the public member firstChild of type DOMNode.

**Comment by weirdan** [comment]
> The file I am referring to is "doc_c.php"

This file it certainly not in the Psalm's codebase, but you make it sound like it is and we're supposed to know what's in there. Is part of your project?

**Comment by orklah** [comment]
I think he makes reference to https://github.com/JetBrains/phpstorm-stubs/blob/f6c4570f4933813024621040a5647418fcfcd0cf/dom/dom_c.php

But if it is, we'll need a lot more context as to why you're trying to analyse a stub file

**Comment by simonbethke** [comment]
Yes, I am making reference to this file. But also, I already pasted all relevant content. Also I am not trying to analyse a stub file, just look at https://psalm.dev/r/226b4245a6. It contains the entire problem. It even is able to reference the classes from dom_c.php to generate the same issue.

I would be really happy to answer questions which are open.

**Comment by orklah** [comment]
Psalm does not use PHPStorm's stubs so they're not causing this issue.

If I understood correctly, you're saying that Domelement::firstChild should not return ?DomNode but ?DomElement

Psalm use this file to know property types:
https://github.com/vimeo/psalm/blob/master/dictionaries/PropertyMap.php

As you can see here, the property DomNode::$firstChild return ?DomNode. The property is not overrided in DomElement and because DomElement extends DomNode, DomElement::$firstChild returns ?DomNode.

This seems coherent with documentation: https://www.php.net/domelement

Now, documentation is sometimes wrong. Do you have code we could run (on 3v4l.org for example) to show that DomElement::$firstChild can sometimes return a DomElement?

It would be useful to know when it returns ?DomElement instead of ?DomNode (is it always, is it depending on the parsed xml?)

**Comment by simonbethke** [comment]
Thanks for this clarification!

You are right and so is psalm :) The issue seems to be, that the stubs in PhpStorm are outdated and not aligned with the current PHP documentation anymore.

**Comment by orklah** [comment]
If you have concrete examples, they usually welcome PR with fixes here:
 https://github.com/JetBrains/phpstorm-stubs/
