### ISSUE TITLE
Exception always thrown by private method isn't picked up

### ISSUE THREAD

**Issue by ciaranmcnulty** [vimeo/psalm#4992]
In this case it's guaranteed that either an `int` is returned or an exception is thrown, but psalm complains that the method can return `int|null`
https://psalm.dev/r/38f7593be3

If the exception-throwing method is inlined, all is well:
https://psalm.dev/r/470ec590b8

**Comment by muglug** [comment]
Add `@psalm-return never-return`: https://psalm.dev/r/2500ca5a10

**Comment by ciaranmcnulty** [comment]
Was reporting because couldn't Psalm infer this?

**Comment by orklah** [comment]
Psalm will usually limit itself to analyzing the phpdoc and signature of a called method

For example:
https://psalm.dev/r/cf05c10c80

I voluntarily made a mistake here and declared the function return an int but it really returns a bool.

Psalm detects the error when it analyse the function itself but it will still say that returnBool returns an int when you use it (because on usage, it will only look at phpdoc and signature).

This is the same for @never-return. Psalm could probably suggest to add @never-return for your method (and it would be reaaally cool), but if you don't have the annotation, it won't know your function never returns on analysis

**Comment by ciaranmcnulty** [comment]
Hm, thanks. I've inlined rather than add psalm-specific annotations (for now)
