### ISSUE TITLE
Static variables are always marked as mixed

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#5005]
https://psalm.dev/r/3a8d5db5c4

**Comment by orklah** [comment]
Maybe Psalm could reuse loop flow here? `[]` would be the value initalized and then consider the rest of the function body as a loop to infer every value possible for the array (because the body will modify the content of the variable, probably more than one time)

For this example: https://psalm.dev/r/73c150b10d
Psalm would infer `array{'a'|1}`

This is quite convoluted for such a small gain though. I usually add a `/** @var type $var */` above those

**Comment by muglug** [comment]
Add a `@var` docblock above – that will ensure the static type is not broken elsewhere in your function: https://psalm.dev/r/bb1b5184c8
