### ISSUE TITLE
Types of static constants are not recognised

### ISSUE THREAD

**Issue by ndench** [vimeo/psalm#505]
It would be great if psalm could infer the type of any defined constant. Take the following example which produces an "Argument 1 of A::doBar cannot be mixed, expecting string" error on `$this->doBar` call (line 7):

```
<?php
class A {
  public const FOO = "this is a string";
  
  public function doFoo(): string
  {
    return $this->doBar(static::FOO);
  }
  
  private function doBar(string $x): string
  {
    return $x."bar";
  }
}

$a = new A();
$a->doFoo();
```

Verified on [getpsalm.org](https://getpsalm.org).

We use constants quite a lot, especially for tests and fixtures.

**Comment by muglug** [comment]
Firstly, sorry - this is a lapse in Psalm's understanding.

Psalm will never be able to reliably type `static::SOME_CONSTANT` because of situations like:
```php
abstract class A {
  public function doFoo(): string
  {
    return static::FOO;
  }
}

class B extends A {
  const FOO = "this is a string";
}
```

This can be run in PHP (though Hack disallows, FWIW).

You can stop the issue a couple of ways – by adding a `(string)` cast before the constant, or by changing `static` to `self` (though this may break your program).

**Comment by ndench** [comment]
Ah ok, that makes sense. Thanks for workarounds, I hadn't considered using `self` instead of `static`.

**Comment by muglug** [comment]
Great – just as long as you know that it's not a straightforward replacement e.g.

```abstract class A {
  const FOO = "this is a string";
  
  public function doFoo(): string
  {
    return self::FOO;
  }
}

class B extends A {
  const FOO = "never returned";
}

echo (new B)->doFoo();
```

**Comment by ndench** [comment]
Yep, I'm aware of that. Thanks 👍
