### ISSUE TITLE
Could not get storage for stdclass

### ISSUE THREAD

**Issue by wildlyinaccurate** [vimeo/psalm#5099]
Hi there! I saw a couple of issues related to this: #2826 and #1016. My issue seems to be slightly different though - it happens when a property on a stdClass object is accessed more than once, and it only seems to happen with results from PDO:

```php
<?php

$db = new PDO('');
$q = $db->prepare('');
$q->execute();
$o = $q->fetch(PDO::FETCH_OBJ);
$o && ($o->p || $o->p); // Uncaught InvalidArgumentException: Could not get class storage for stdclass
```

Here's the failing case on psalm.dev: https://psalm.dev/r/816787d4b3
Here's a passing case with only one `$o->p` access: https://psalm.dev/r/1918607874
Here's a similar chunk of code using a plain `stdClass` constructor: https://psalm.dev/r/0d6d9aae0a

**Comment by ohader** [comment]
PR #5100 does not solve it, but shows one aspect - using `object` instead of `stdClass` as type.

https://github.com/vimeo/psalm/blob/f9fccb2b2dafacc83bf6c43c24d09aa8a589446c/src/Psalm/Internal/Provider/ReturnTypeProvider/PdoStatementReturnTypeProvider.php#L95

Replacing with `TObject` seems to be working - however, I don't know why `stdClass` explicitly was taken in the first place.
```
-                        new Type\Atomic\TNamedObject('stdClass'),
+                        new Type\Atomic\TObject(),
```

**Comment by ohader** [comment]
Awesome! Thanks @muglug 👍
