### ISSUE TITLE
Phpdoc for promoted properties

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#5102]
Why psalm ignore phpdoc for promoted properties? Unimplemented functionality?
https://psalm.dev/r/55db9ae205

php supports this kind of phpdoc from 8.0: https://wiki.php.net/rfc/constructor_promotion#reflection

**Comment by still-dreaming-1** [comment]
Am I understanding this correctly that none of the docblocks that would work for properties work for promoted properties? I am having a hard time getting any use out of promoted properties because of this even though they would be really nice for reducing duplication and avoiding setting each property.

**Comment by weirdan** [comment]
@still-dreaming-1 you are correct

**Comment by Cryszon** [comment]
You can use `@param` as a workaround for now.
https://psalm.dev/r/11a5c18efc

**Comment by iquito** [comment]
@Cryszon That is not a workaround for describing the properties, where the problems come from in all my cases (leading to `ArgumentTypeCoercion` errors when using the properties).

**Comment by still-dreaming-1** [comment]
> @Cryszon That is not a workaround for describing the properties, where the problems come from in all my cases (leading to `ArgumentTypeCoercion` errors when using the properties).
> 
> EDIT: Just tried it out, surprisingly it actually does work - psalm then also uses the `@param` value for the property. I thought I tried that and it didn't work - thanks for the tip!

I'm also almost 100% sure I tried that and it didn't work, but now I'm trying it again and it is working for me too. So at least we can get Psalm specific types in our properties. I also tried `@readonly` and that is also working...

**Comment by orklah** [comment]
Psalm now supports @param and @var for promoted properties. The initial example however emits an error because of the use of @var (for properties) in combination with a signature type. I'm not sure this is the behaviour we want. If someone want to change that, feel free to open a PR to describe the behaviour we should follow

**Comment by vudaltsov** [comment]
@orklah , thank you very much, great news!
