### ISSUE TITLE
Internal Psalm error on for loop

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#5108]
A super basic for loop:
https://psalm.dev/r/b82fa3082e

causes:
Internal Psalm error on line 1148 - /vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Analyzer.php: non-empty node_type expected

**Comment by weirdan** [comment]
Curiously, this is only reproducible when `$x` is `0`.

**Comment by orklah** [comment]
You don't even need to have an increment. Only a condition involving the variable and a variable that starts at 0 is enough.
https://psalm.dev/r/ce8407da1b

**Comment by orklah** [comment]
Weird, I could not reproduce locally.

I'm pretty sure it was caused by the last commit: https://github.com/vimeo/psalm/commit/06240988657c656b02f2b45f910b194206c2c32f It changes the format of getId() which return get sent to the exception we're seeing. If getId() somehow return an empty-string, it crashes

**Comment by muglug** [comment]
Yup, it's because of a good-ol' `if (!$node_type)` check where `$node_type` is the string `0`, which gets evaluated to false

**Comment by orklah** [comment]
I'm a moron, I thought this had to be an empty string as in `""` and not as in `"0"` not sure why I couldn't reproduce though.
