### ISSUE TITLE
Typed variadic as array validator not allowed?

### ISSUE THREAD

**Issue by ZealJared** [vimeo/psalm#5118]
I often use typed variadic function arguments to catch possible bad input. For example, suppose I have a JSON array that should contain only strings, but might be malformed:

https://psalm.dev/r/1294de36f1

I don't want to type-hint the array like `/** @var array<int,string> */` because that may not be true, that's what the typed variadic is for. If I go ahead and type-hint it that way, Psalm will let me use the array as if that type-hint is true, which is misleading. Is this an issue? Should I suppress the error and move on, or is there something else I'm missing?

**Comment by weirdan** [comment]
So basically your expected use case for that function **is** to pass `mixed[]`, but use the array as `string[]` after the call, because if passed anything else the function will throw. You can describe this with assertion: https://psalm.dev/r/9a16b236d4

You may want to take a look at `webmozart/assert` library - it's a full package of various useful assertions, compatible with Psalm. Or you could just use it as an inspiration.

**Comment by ZealJared** [comment]
Thanks! I didn't know about `@psalm-assert`. That actually helps me with several other places in my code where throwing an exception upon type mismatch isn't registering with psalm as a type guarantee.
