### ISSUE TITLE
is_subclass_of transform its first argument to mixed if used with get_class

### ISSUE THREAD

**Issue by chapa** [vimeo/psalm#5192]
Using `is_subclass_of()` seems to transform the type of its first parameter to `mixed` in the "successful branch", but only when this parameter is the return value of `get_class()`.

An example to better understand: https://psalm.dev/r/10d7e4cecf

**Comment by orklah** [comment]
This is due to get_class returning a very special type named `TDependentGetClass`. This is probably used for resolution purposes.

However, the `isa-` assertion generated by is_a or is_subclass_of is coded to work against object types or string (including class-string).

This is done in AssertionReconciler::handleIsA. We would need to look at how TDependentGetClass is resolved into a class and then it's just a matter of replicating the behaviour when a string is found.

**Comment by weirdan** [comment]
Original snippet doesn't produce any errors now.

**Comment by weirdan** [comment]
https://psalm.dev/r/e9e056e3e5
