### ISSUE TITLE
Modifier to disallow non-documented keys from array shape

### ISSUE THREAD

**Issue by ntzm** [vimeo/psalm#5299]
I would like to be able to do the following:

https://psalm.dev/r/cdf24c2204

The current behaviour is obviously wanted in most cases, but I would like a modifier that disallows non-documented keys from array shapes, something like `array-shape-strict{foo: string}` or `array!{foo: string}`

**Comment by muglug** [comment]
This was slightly poor design on my part.

We could add a config that would make `array{a: int, b: string}` strict and `array{a: int, b: string}&array` the flexible version. In v5 that config could become the default.

**Comment by ntzm** [comment]
That would work for me

**Comment by AndrolGenhald** [comment]
I've been thinking the best way to do this would be to do something like TypeScript's [index signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) (and maybe eventually [mapped types](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html)) for keyed arrays. Unsealed arrays (I'm say "sealed" and "unsealed" because that's what Psalm [currently calls it](https://github.com/vimeo/psalm/blob/c90cffd382bb7a5d390387d4ad2a02a4935fba5c/src/Psalm/Type/Atomic/TKeyedArray.php#L46). Sealed means no extra keys, unsealed means extra keys are `mixed`.) are currently the default, but in Psalm 5 (or probably 6 at this point) we could have a breaking change and say unsealed arrays must be represented as `array{a: int, [array-key]: mixed}`. We could also think about providing a tool to ease the transition by automatically changing `array{a: int}` to `array{a: int, [array-key]: mixed}`.

@ondrejmirtes I know we want to make sure Psalm and PHPStan are in agreement on this since it's such an important feature. I saw you had some proposals [here](https://github.com/vimeo/psalm/issues/4700#issuecomment-870369305), but I'm not much of a fan of `array{foo: Bar, []}`. I think if we want unsealed arrays to remain the default, a better option would be either `strict-array{foo: Bar}` or `array{foo: Bar, [array-key]: never}`, and I'm leaning towards the second option. Maybe we could have a config option for whether arrays are sealed or unsealed by default? That way `array{foo: Bar}` would use that config option, `array{foo: Bar, [array-key]: mixed}` would always be unsealed regardless of config, and `array{foo: Bar, [array-key]: never}` would always be sealed regardless of config.

If we want to go with index types, there are couple of things to consider.

I think it's fine to remove the name (eg `array{foo: Bar, [array-key]: mixed}` rather than `array{foo: Bar, [key: array-key]: mixed}`). It seems not to matter for normal index signatures, and while it's useful for mapped types I think we can add syntax for that later while remaining backwards compatible.

Overlapping types: `array{a: int, [lowercase-string]: lowercase-string, [string]: string, [int]: int}`. Is the type valid? Do earlier keys take precedence? TypeScript [requires](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgJLIN4Chm+XALmRAFcBbAI2gBoc8BtAayIGcwpQBzAXVfa9oBfANxA) that defined keys match the index signature, but if we want `array{a: int, [array-key]: never}` to work I think we have to be more lax. I think actual keys should always take precedence, but I'm not sure what to do about multiple index signatures. Should we limit it to a single index signature to start out, and improve it from there?

**Comment by danog** [comment]
I'm working on a [PR](https://github.com/vimeo/psalm/pull/8395)  that adds support for explicitly `sealed-*` types, even though even with sealed types enabled some checks don't work as planned (as also mentioned in a separate comment by @orklah in the PR): https://github.com/vimeo/psalm/issues/8397

**Comment by weirdan** [comment]
This is now the default behaviour: https://psalm.dev/r/19e15d40ad

Old-style, unsealed shapes can be expressed using `array{T1,T2,T3,...}` syntax.

**Comment by muglug** [comment]
This is all on me, but I pushed for this to be clarified in Psalm 5.

Both [Phan](https://phan.github.io/demo/?code=%3C%3Fphp%0A%0A%2F**%0A+*+%40param+array%7Bid%3A+string%2C+name%3A+string%7D+%24user%0A+*+%40return+array%7Bid%3A+string%2C+name%3A+string%7D%0A+*%2F%0Afunction+takesUserData%28array+%24user%29%3A+array+%7B%0A++%24user%5B%27extra_data%27%5D+%3D+new+stdClass%28%29%3B%0A++return+%24user%3B%0A%7D%0A%0A%24foo+%3D+%5B%27id%27+%3D%3E+%27DP42%27%2C+%27name%27+%3D%3E+%27Douglas+Adams%27%5D%3B%0Aecho+implode%28%27%27%2C+takesUserData%28%24foo%29%29%3B) and [PHPStan](https://phpstan.org/r/4a61d13c-74f0-46d3-9bad-f3a61dd1d172) have unsound behaviour.

In both cases you were following Psalm’s lead, but unsound behaviour is bad and wrong.

The correct behaviour here, IMO, is for array shapes to be sealed by default. I did not want to release another major version with unsound behaviour, and I didn’t want to have everyone start adding `sealed-array` annotations everywhere, because that looks horrible.

**Comment by ondrejmirtes** [comment]
I wasn’t aware of any changes because three weeks ago we agreed with orklah that array shapes by default shouldn’t change because of the impact on the ecosystem https://github.com/vimeo/psalm/pull/8395#issuecomment-1303995033 and only sealed/strict variants should have the stricter behaviour. That’s what PHPStan will continue to do.

**Comment by muglug** [comment]
It's not "stricter" behaviour, though — it's unsound. And, unlike other unsound stuff in typecheckers (like array keys being converted to ints in some cases) this is unsound behaviour introduced by the typecheckers themselves.

Psalm has led the way when it comes to preventing unsound behaviour (e.g. making `mixed` issues a thing years before anyone else) and this will be another example.

My guilt is that it was an unsoundness _introduced_ by Psalm. This is a chance to remedy that, at the expense of some friction for users.

**Comment by muglug** [comment]
Psalm also still supports (actually also incorrectly-thought-out) array annotation `array{a: Foo, b: Bar}&array` for unsealed array shapes. That annotation is a no-op in PHPStan.

For users who encounter this issue who want their docblocks to work as-is in both tools, adding `&array` for unsealed array shapes is the smallest possible change.

**Comment by ntzm** [comment]
Nice, thank you everyone :)

**Comment by ondrejmirtes** [comment]
I'll eventually adopt this too, but I'm not gonna hurry, because I can already foresee the amount of support this change will generate for me for several months in a row :)

**Comment by bendavies** [comment]
An optional bleeding edge or phpstan-strict-rules rule would be great. I'm
always after more strictness!
