### ISSUE TITLE
Invalidate keys in Codebase classes in server mode

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#531]
When modifying a file, some data needs to be removed from `ClassLikes`

**Comment by TysonAndre** [comment]
It looks like this has been completed for classes on a branch of vimeo/psalm, but there's other tasks left for Language Server Protocol support

I skimmed over that branch(server?) and may have missed some things. File issues for anything that seems appropriate:

Since I don't see any other issues: Does this work for global functions, global constants/define('constname', 'value'), and closures? (I only see removeClassLike)

How does psalm handle duplicate classes right now?

- Is the FQSEN in the Codebase object different from the FQSEN in the file storage representation? If the FQSENs are different, handling the edge case of duplicate classes (probably unimportant) may require a different approach, such as a dedicated UndoTracker object.

Does this pick up a deletion if a file gets deleted in server mode? (Doesn't seem like it)

Other recent changes to a similar implementation of server mode that may be of use:

- publishDiagnostics(uri, []) should be called from Server\TextDocument->didClose() so that the issue messages go away when the currently open file is switched to a different file, or a tab is closed
- https://github.com/phan/phan/blob/e5d35c724ff17e430ba1dbd5a56e37a56e9ed1dd/src/Phan/LanguageServer/Protocol/TextDocumentSyncOptions.php allows explicitly disabling change notifications from the client, while continuing to receive the full document text in didSave (Useful because analysis during typing can be distracting or CPU intensive. See references to TextDocumentSyncOptions)
- https://github.com/phan/phan/commit/473af9ce95680440b819a992159b9b39eceaea92#diff-d924a25c35250c15757a629e10a86460 (E.g. readMessageGroup was used to avoid creating a backlog of messages, and fixed issues some clients were having on files. If there were multiple analysis requests for the same file, only the most recent one was acted upon)
- Various other changes and bug fixes to that pcntl-based server mode implementation

**Comment by muglug** [comment]
@TysonAndre yup still a host of things to do. I'm hacking on a LSP implementation atm, but it's more a proof-of-concept than a releasable thing (I've updated the `server` branch with a lot of confusingly-named commits).

> Does this work for global functions, global constants/define('constname', 'value'), and closures? (I only see removeClassLike)

When you save a file, you invalidate all its dependents, and they're repopulated. But that's only possible if the function was included via `require`/`include`. I should (but don't yet) a add a dependency to the file that defines the global userland function (this goes for regular Psalm runs with `--diff` too, which don't take into account dependencies on functions loaded before Psalm runs).

> How does psalm handle duplicate classes right now?

It doesn't/it's ugly. It should probably add a suffix (e.g. `SomeClass#2`) in the `DependencyFinderVisitor` so methods in the duplicate class don't pollute the original.

> Does this pick up a deletion if a file gets deleted in server mode? 

Not yet

The main challenge I want to overcome is managing files at scale
