### ISSUE TITLE
Unnecessary var annotation not reported if the type is narrower

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#5321]
Here both should be reported IMO:
https://psalm.dev/r/fc696a9f94

Seems it's only reported if it's **exactly** the same type
https://psalm.dev/r/d939fe349c

**Comment by orklah** [comment]
Well, for me the goal of @var is to change override the type of a variable. The Issue is emitted only when there is no change.

@var is a very delicate thing because it's used a lot of times to "fix" edge cases or outright SA bugs. While I don't see any legit case where widening a type using @var could be useful, I assume Psalm is perfect and never produce bugs and handle every edge case.

In case of a bug, emitting an issue when the user contradicts Psalm's inferrence would mean the user finds a bug, uses @var to override Psalm's inferrence and then must suppress the new Issue Psalm emits.

**Comment by weirdan** [comment]
It's best illustrated by tracing the type after the `@var` is used: https://psalm.dev/r/d09870f970

So, not a bug, this is by design.
