### ISSUE TITLE
Psalm loses type when modifying an array shape

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#5361]
Hey there,

I am working with an array shape here and I just want to modify an array key.
After doing it, psalm loses track of the inferred type from docblock.

https://psalm.dev/r/3818f99ff1

Is that intended and if so, what would be the correct way of manipulating an array like this?

**Comment by boesing** [comment]
That was just for a quick scribble.
The use case is, that I import the type from another file.
That file is calling this method.
I've thought when I use the template, psalm keeps track on already verified informations like: "before the $type variable was passed to the method, it contained $type['params'][0], so it will keep that information when overriden by the return value of the method".

https://psalm.dev/r/4ecd59ef38

Without template, this will definitely fail.

With template, it fails due to losing track of the type.
https://psalm.dev/r/93710b9900

**Comment by weirdan** [comment]
Psalm analysis does not cross method boundaries. So for the method body it does not 'lose the type', it just considers *all possible* subtypes, constrained by the type parameter constraint. That includes very specific types like 
```
array{
  name:"John", 
  params:array{
    array{
      name:"numbers",
      params:array{5, 42}
    },
    array{
      name:"strings",
      params:list<string>
    }
  }
}
```
Note this this is a *type*, not a value, and it's a valid subtype of your type. So the method body has to be valid for this subtype as well, and it isn't, because it would change *the type* to
```
array{
  name:"bar", 
  params:array{
    array{
      name:"numbers",
      params:array{5, 42}
    },
    array{
      name:"strings",
      params:list<string>
    }
  }
}
```
This is not a subtype of the type above, thus it fails.
