### ISSUE TITLE
Argument unpacking not always inferring type correctly

### ISSUE THREAD

**Issue by jaikdean** [vimeo/psalm#5451]
Unpacking arguments from an array seems to trip up the type system in some cases. The following two cases are equivalent code, but one incorrectly infers the return type of `max()`.

Not working: https://psalm.dev/r/4966534dd5
Working: https://psalm.dev/r/c0b67c0dd6

**Comment by AndrolGenhald** [comment]
I've come up with a bunch of other false positives and false negatives as well when trying to fix #5420, like this interesting one: https://psalm.dev/r/fc9b5905cb

Argument unpacking is difficult...I'm starting to think we should just have a general "don't use non-object-like arrays when unpacking arguments" issue for some error level and ignore it otherwise (see #5452).

**Comment by AndrolGenhald** [comment]
This seems to be fixed now.
