### ISSUE TITLE
UnusedMethodCall in an immutable context

### ISSUE THREAD

**Issue by 1ed** [vimeo/psalm#5528]
Hello! After updating to 4.7 I got this error which was not an error before:

https://psalm.dev/r/948af0da31

Am I doing something wrong or its a false positive? Thanks!

**Comment by still-dreaming-1** [comment]
This is just a guess, but I imagine Psalm expects that since assertMemberId is pure/immutable, calling it is meaningless if there is no return value or the return value is not used. It would be nice to hear from the developers if this is really the case. I wonder if there might be a need to annotate the method as asserting something. It's almost like the method itself should be flagged by Psalm as being unusable since there is no return value...

**Comment by orklah** [comment]
Documenting that the method can throw should be enough to tell Psalm it's not useless but it does nothing

**Comment by 1ed** [comment]
AFAIK assertMemberId do not need to be pure for immutability. 

https://psalm.dev/articles/immutability-and-beyond

> You can use the annotation @psalm-immutable on any class you like — it’s the equivalent of adding @psalm-readonly to every property and @psalm-mutation-free to every instance method of that class.

> @psalm-pure: the function does not mutate any state external to the function; the function’s output is entirely deterministic based on its parameter input

> @psalm-mutation-free: the function does not mutate any state external to the function, and its output is deterministic based on its parameter input and the attached instance’s properties

I think assertMemberId meets the definition and it is certainly not an unused method.

**Comment by 1ed** [comment]
> Documenting that the method can throw should be enough to tell Psalm it's not useless but it does nothing

I tried that and it does not change anything and I think psalm should infer that from code anyway.

**Comment by orklah** [comment]
> I think assertMemberId meets the definition and it is certainly not an unused method.

Psalm thinks a method that does not mutate state AND doesn't return is automatically useless. This is true except when the method can throw exceptions.



> I tried that and it does not change anything and I think psalm should infer that from code anyway.

For performance reasons, Psalm doesn't just recursively go through every sub-method to see what it does. That's why it requires phpdoc (or types in signatures) at method bounds to be able to work quickly. That's why I thought this should be solved with @throws but it doesn't help. 

IIRC correctly, Psalm notion of immutability/purity exclude exceptions by design but I don't think it can be applied here

**Comment by still-dreaming-1** [comment]
@psalm-mutation-free is very similar to `@psalm-pure`. I don't understand what the difference is, but mutation-free does also mean it will not mutate state internally as well as externally. So if `@psalm-immutable` at the class level means the methods are marks as mutation-free, this is very similar to marking them as pure. https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-mutation-free

**Comment by orklah** [comment]
`@psalm-mutation-free` implies no state modification. `@psalm-external-mutation-free` implies no state modification except for the current class (so it can't mutate another class nor the caller). `@psalm-pure` implies `@psalm-mutation-free` but also state that the method will always return the same result for a given list of parameters.

for example a function that returns `return rand(0,1);` is mutation-free but not pure

**Comment by weirdan** [comment]
> for example a function that returns `return rand(0,1);` is mutation-free but not pure

It actually mutates PRNG state. Better example would be something like `return file_get_contents('/path/to/file');` - it doesn't mutate anything, but is not pure because file may have been changed between calls.

**Comment by still-dreaming-1** [comment]
@orklah @weirdan That was very clarifying, thanks! With all that considered, it still seems plausible that Psalm considers calls to a mutation-free method to be meaningless/unused if there is no return value or the return value is not used for anything. In this case, the method is acting as an assertion method of sorts, throwing an exception if it does not pass. I agree this is a valid issue in that there should be some way for Psalm to know the call to it is not "unused". Whether Psalm should already be able to infer that or there should be some more annotations in this code I'm not sure.

**Comment by christian-kolb** [comment]
Does anyone know about a workaround for it other then using `psalm-suppress` everywhere?

We use those assert methods quite extensively to make the business logic more readable. For example with methods like `$requestingUser->mustNotBeLocked()` or `$requestingUser->mustHavePermissionToDeleteUser()`. They heavily rely on simple "fail check => throw exception" logic.
