### ISSUE TITLE
Feature Request: positive-float type

### ISSUE THREAD

**Issue by melihovv** [vimeo/psalm#5533]
I wonder why there is no support for positive-float type, but positive-int is supported? I think positive-float will be very useful too.

**Comment by Hordev** [comment]
+

**Comment by orklah** [comment]
positive-int pops up naturally in a lot of situations related to static analysis. A length is positive-int, count() will return positive-int, array offset are naturally positive. There's a lot of functions in php core that will either receive or return positive-int.

The same can't be said about positive-float. Also float have a lot of flaws (like floating point number) who would prevent meaningful checks with SA.

I very much encourage you to have a class (possibly even a library like Moneyphp) when you have to handle floats in a meaningful way that would remove the need for static analysis (for example, you can create a CartPrice that will refuse any negative input at all)

I'm gonna close this because we have few resources. positive-int is currently on the way to be deprecated and replaced by integer ranges (`int<0,100>` that would make no sense with floats)

**Comment by rzvc** [comment]
My library could use a positive-float. Will there be float ranges too?

**Comment by orklah** [comment]
As I said, it's a pretty niche feature which wouldn't interact with PHP core at all. Integer ranges were pretty hard to add and I don't intend to add them for float.

Do you have an example where it would be useful for your library?

**Comment by rzvc** [comment]
It has a type called pnumber, which I would have liked to be able to represent differently from int<0, max>|float, but it's a small detail, and if it's difficult to add, your time is probably better spent elsewhere.
