### ISSUE TITLE
Missed RedundantCondition in catch-block

### ISSUE THREAD

**Issue by olegpro** [vimeo/psalm#5585]
https://psalm.dev/r/8c13211470 — With this example, everything is fine (we get an error RedundantCondition).

https://psalm.dev/r/d4b88a3860 — But there is no error here.

**Comment by orklah** [comment]
I'm gonna close this because this is by design. Redundant/Impossible checks are hard to do in catch because try{} involve halting the execution of a block of code at an arbitrary point (we may not know where the exception is thrown). 

The code that remove this error is there: https://github.com/vimeo/psalm/blob/af8033adf037017c7088da773ec6b8bb7711d741/src/Psalm/Internal/Analyzer/Statements/Block/TryAnalyzer.php#L165
