### ISSUE TITLE
Extract: Broken types

### ISSUE THREAD

**Issue by jarstelfox** [vimeo/psalm#5604]
psalm.dev/r/f499e58714

Very weird results here. I suspect the internal state is jumbled.

**Comment by weirdan** [comment]
> Very weird results here.

Mind expanding on that?

**Comment by jarstelfox** [comment]
Sure!

I see two main problems:

1) `Argument 1 of identityInt cannot be mixed, expecting int` is indicating the argument is `mixed` but logging the type with `psalm-trace` shows that the type is an `int`. Thus, a contradiction as the type is both `mixed` and an `int`.

2) `psalm-trace` seems to think an object/string are ints. `$someObject: int` / `$someStr: int` I suspect this is related to 1) above.

**Comment by orklah** [comment]
@jarstelfox see https://psalm.dev/r/d39e392eb0

I added a semicolon at the end of the trace to show you that @psalm-trace show you the type as it is AFTER the following expression.

In the example, you can see all the variables are in fact unknown(and considered as mixed).

However, Psalm is being smart here and it uses the signature type from the called function to type your unknown variable for the rest of the execution.

Here's what happens when the type is not in signature: https://psalm.dev/r/34e95d373a

Hence why every variable is considered "int" even when it's a string in the array.

The core of your problem here is that `extract` does not seem to be supported fully by Psalm right now. That's why every variable is unknown.

You could even argue that "borrowing" the type from the signature of the method is not a correct behaviour (except in strict_types) because PHP does implicit casting otherwise.

**Comment by jarstelfox** [comment]
Oh wow, I just wasn't noticing the extra semi-colon. Sorry for taking your time.

>The core of your problem here is that `extract` does not seem to be supported fully by Psalm right now. That's why every variable is unknown.
>
>You could even argue that "borrowing" the type from the signature of the method is not a correct behaviour (except in strict_types) because PHP does implicit casting otherwise.

Agreed. The behaviour is sensible, however, I see you created https://github.com/vimeo/psalm/issues/5609 which is better suited to handle my concerns. I will close this issue.

**Comment by orklah** [comment]
@jarstelfox You could also suggest, or contribute for support for `extract` also.
