### ISSUE TITLE
False-positive `TypeDoesNotContainType` on `DOMNode::$attributes`

### ISSUE THREAD

**Issue by lukasbestle** [vimeo/psalm#5665]
https://psalm.dev/r/2450182f1f

The [PHP documentation](https://www.php.net/manual/en/class.domnode.php) states that this attribute may be `null`.

**Comment by weirdan** [comment]
Actually Psalm thinks it's *always* `null`.

/cc: @ShiraNai7

**Comment by weirdan** [comment]
I think we may have a case of broken property invariance here.

**Comment by ShiraNai7** [comment]
It's always `null` on `DOMNode`, unless it's an instance of `DOMElement`, then it should never be `null`.

PHP docs:

> A DOMNamedNodeMap containing the attributes of this node (if it is a DOMElement) or null otherwise.

Maybe it should be defined as `DOMNamedNodeMap<DOMAttr>|null` instead of just `null`? In the PropertyMap.

**Comment by lukasbestle** [comment]
> It's always null on DOMNode, unless it's an instance of DOMElement, then it should never be null.

In practice yes, but in the class synopsis the attribute is defined on `DOMNode` anyway and not just on `DOMElement`, which is kind of a mess.

I agree on your proposed solution!

**Comment by caugner** [comment]
I got struck by this issue today and investigated shortly. So, in theory Psalm's PropertyMap already knows about the differences:

DOMElement:
https://github.com/vimeo/psalm/blob/915f80ad5f8e385322b9f2f868ad9ac8e8ce378d/dictionaries/PropertyMap.php#L318-L321

DOMNode:
https://github.com/vimeo/psalm/blob/915f80ad5f8e385322b9f2f868ad9ac8e8ce378d/dictionaries/PropertyMap.php#L371-L381

Now I wonder:
1. Does the mapping for `DOMNode` wins over `DOMElement`, because it is declared *later*?
2. Or does Psalm *add up* both mappings to essentially `never`?

**Comment by orklah** [comment]
@caugner nothing complex here. Psalm knows it has a DomNode, it looks at DomNode::$attributes and see the type is null. The end :) (the never seem to come from the coalesce, not from the property in itself)

But properties are supposed to be invariant so the type of a property for a parent is supposed to be the same as in the child. It seems not to be the case here, but it should at least be as wide as any of the childs, meaning you can't have a null type on DomNode and a wider type in the childs...

**Comment by AndrolGenhald** [comment]
#7641 should fix this for Psalm 5, but we might want to fix the property map for 4.x as well.

**Comment by weirdan** [comment]
Seems to have been fixed already: https://psalm.dev/r/5947237a16
