### ISSUE TITLE
InvalidScope error for method bind

### ISSUE THREAD

**Issue by radonthetyrant** [vimeo/psalm#5668]
https://psalm.dev/r/597c79a788

Should not give the error but recognize that this function may be used in object context, therefore it is valid and works, see: http://sandbox.onlinephpfunctions.com/code/c03e6bd64a29f53bcefd0c746b33cdc6725abea0

**Comment by orklah** [comment]
It works, but this fails:
https://psalm.dev/r/6303790315

And Psalm can't know whether it will pass or fail because it doesn't know which scope it will be used in.

This is basically very static analysis unfriendly code, but Psalm (and PHPStan: https://phpstan.org/r/6ee59a36-60d1-4472-a179-80e9ab513943) will prefer playing it safe and giving you an error.

You're free to suppress the error if you know what you're doing
