### ISSUE TITLE
password_hash() has invalid return type (php 8.0)

### ISSUE THREAD

**Issue by someniatko** [vimeo/psalm#5673]
tested on PHP 8.0+Psalm 4.7.1 and psalm.dev: https://psalm.dev/r/9168e7fec6

expected: `string|false` (docs) or `string` (actual behavior, see below)
actual: `string|null`

from source code it seems on PHP 8 it actually throws an error instead of returning false.
https://github.com/php/php-src/blob/PHP-8.0/ext/standard/password.c#L644-L674

**Comment by orklah** [comment]
Something strange here. password_hash is defined as returning string in PHP8: https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_80_delta.php#L174

I think this may be due to the "old" signature from PHP8 callmap not matching with the previous one: https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_80_delta.php#L453 vs https://github.com/vimeo/psalm/blob/master/dictionaries/CallMap_74_delta.php#L19

**Comment by orklah** [comment]
This was solved
