### ISSUE TITLE
Getting UndefinedDocblockClass for use of a class template

### ISSUE THREAD

**Issue by toby-griffiths** [vimeo/psalm#5689]
I'm receiving an `UndefinedDocblockClass` warning in this example…

https://psalm.dev/r/d695e7815b

… however in the this one I am not…

https://psalm.dev/r/31b96c80a7

The only difference that I can see is that the later is for a `@return` rather than a `@param`.

Have I discovered a bug, or am I being stupid?

**Comment by weirdan** [comment]
The former uses `static` method, and that makes all the difference (https://psalm.dev/r/1a590c24c2). Psalm does not allow using *class* template parameters on *static* methods.

**Comment by toby-griffiths** [comment]
@weirdan Thank you for explaining.  Is this intentional, or just 'not supported _yet_'?

**Comment by orklah** [comment]
It was supported once but IIRC, it creates weird situations so it was removed. If you have a code example of what you want to do, I'd suggest creating a new issue so we can take a look

**Comment by toby-griffiths** [comment]
@orklah Is the code example linked above the kind of thing you're referring to, or something different?

**Comment by orklah** [comment]
Exactly. Above the class, you create a template C that will be bound to an instance of an object implementing CommandConfigInterface. This means, C could have different values in two distinct objects. Once this is said, what should be the value of C for a static function?

For example: https://psalm.dev/r/89f5b2e181
I created two collections here. One contains a boolean, the second an integer to show that the value of "C" is inherently bound to an instance of a class.

So when I use "C" in a static function, it has no meaning because Psalm can't know what I want.
