### ISSUE TITLE
Scalar considered ... mutable sometimes

### ISSUE THREAD

**Issue by SCIF** [vimeo/psalm#5725]
https://psalm.dev/r/4a1d2a0bb0

**Comment by muglug** [comment]
More refined example: https://psalm.dev/r/187c4aa124

**Comment by muglug** [comment]
This fix will not work if the type is in a docblock: https://psalm.dev/r/6e164b5aea

This is due to an intricacy around Psalm's treatment of docblock types when passed through functions that would error if the type did not match the docblock one — it treats a call to `expectsString(string $s)` similarly to `assert(is_string($s)) && expectsString($s)` when the type of `$s` is only informed by a docblock
