### ISSUE TITLE
Support for scalar_objects PHP extension

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#5737]
I would like for Psalm to be able to understand the syntax enabled by the [scalar_objects](https://github.com/nikic/scalar_objects) extension. I tried [asking for help](https://github.com/vimeo/psalm/discussions/5706) in the discussions area, but decided to bump this up to the issues area because I'm at a loss for how to proceed from here, but I'm committed to putting in whatever work is necessary to make it happen myself if it is possible.

This is a pretty good example of what I would like to be able to do:

https://psalm.dev/r/0a4f4633a7

I can conceive of 3 avenues for making this possible. 1) Create a Psalm plugin. 2) If the plugin system is not flexible enough, improve the plugin system. 3) Add support for this extension directly into Psalm. I am willing to do any of these, but am failing to make any progress and could use some help or advice. Which of these avenues do you think is the best approach?

**Comment by orklah** [comment]
What is the goal exactly? Do you want Psalm to stop emitting issues related to the use of this extension or do you want Psalm to infer the "3" in your example?

The first one could probably be feasible. The second one seems so complicated that I'm not sure it would be worth the performance hit that is bound to come with the feature

**Comment by still-dreaming-1** [comment]
My main goal is for Psalm to know the ->length() method is valid to call on a non-empty-string, and to type check what I pass in. I probably should have left out the positive-int stuff.

**Comment by still-dreaming-1** [comment]
Here is a better example without the positive-int

https://psalm.dev/r/e3dc60043b

A simple use case would be if Psalm knew the method was valid to call on a string. In my case, even though PHP itself considers that a valid method to call on a string, the Psalm support wouldn't really be all that helpful unless it knew to consider this method call valid on non-empty-strings and not on regular strings, based on the ->length() method accepting the more specific type, non-empty-string.

**Comment by orklah** [comment]
Ok so, for me, there are at least 3 different issues there.

1) Psalm would have to see the register_primitive_type_handler use before even working on anything else. Psalm checks are non linear and no matter where this function is used, Psalm would have to assume it affects the whole project. Perhaps this is something that should be in the settings instead
2) Psalm internal TString would not be enough anymore because you want to be able to call methods on it. I'd say this ressemble Stringable objects but this is worse than that because you want to maintain the non-empty-string notion. You'd have to recreate the hierarchy between non-falsy-string, non-empty-string, string etc...
3) compatibility with the current system. Every function is documented as taking strings and returning strings. This won't do for you because any string will have to be replaced with the new "Stringable" structure. This means intercepting every TString creation, changing every comparison and every reconciliation between the current TString structure and the new one

This is only the start and any of the three items above is already way more ambitious than everything I personnally did in Psalm on its own.

If this was a feature that would be used by many, I would applaud, but I have little hopes that more than a few dozens people will use both on a project...

**Comment by orklah** [comment]
I'm closing this, I think question where answered
