### ISSUE TITLE
Syntax for callable param/return types

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#580]
***Edit***: consensus has coalesced around the `callable(type1, type2): returntype` syntax

If we want to specify that a function receives a certain sort of closure, we should be able to use a type.

e.g.

```php
/**
 * @param Closure<string, int, int> $foo
 */
function takeClosure(Closure $foo) {
  $a = $foo(3, 5);
}

// this is good
takeClosure(function(int $a, int $b) { return (string) ($a + $b); });
// this fails
takeClosure(function(int $a, string $b) { return (string) ($a + $b); });
```

**Comment by muglug** [comment]
Alternative syntax:

```php
/**
 * @param Closure(int, int): string $foo
 */
```

**Comment by weirdan** [comment]
'Closure', perhaps, is a bit misleading, as function is likely to accept any callable with that signature.

**Comment by prewk** [comment]
This would be extremely valuable to me. Callable/Closure-neutral suggestion: `@param fn(int, int): string $foo`

**Comment by muglug** [comment]
@TysonAndre do you have thoughts/is this already supported in Phan?

**Comment by TysonAndre** [comment]
This isn't implemented in Phan. My preferences are `Closure<string,int,int>` or using `Closure(int, int): string`.

My original idea was also `Closure<ReturnType,ParamType1,ParamType2>`, because of the overlap with template types.

- Would need some way to indicate variadics params as well. Those aren't part of template types
- Neither are references

 `Closure(int, int): string` is probably parseable and unambiguous with psalm's union types

Another idea I thought of is `(a:string)=>string` (this makes it harder to match up `<` and `>`)

- That idea looks ugly and unreadable with `array<int,(a:string)=>string>`

**Comment by TysonAndre** [comment]
It'd also be useful to be able to document the names of parameters.

So, `Closure(int $offset, int $count): array` might be an example of a union type

So, that idea ends up being similar to http://docs.phpdoc.org/references/phpdoc/tags/method.html with the following differences:

- Put the return type at the end
- Prefix with Closure (and possibly callable()/function() for the generic callable -- callable is less ambiguous)?
- Don't bother with `static`
- Allow `= default` syntax, parsed the same way
- Same: Require at least one of the union type/name.

**Comment by TysonAndre** [comment]
Another thought: `Closure` isn't a reserved name in any PHP version so far. `namespace MyNS { class Closure {}}` is valid code.

- So `Closure<T1>` would be ambiguous in the other proposal (not very likely to ever come up)

`Closure(): array` is still unambiguous, though, and can only refer to `\\Closure` (Unless the proposed callable syntax is extended to classes implementing `__invoke`, which I doubt would ever happen)

I'd prefer rendering this in issue messages as `\Closure() : array` with a namespace, to be consistent with `\Closure`. So I'd want syntax to support both `\Closure():array` and `Closure():array` in phpdoc?

**Comment by muglug** [comment]
I'm happy with

```php
/**
 * @param \Closure(int, string) : bool $callback
 */
function doThing(\Closure $callback) : void {}
```
and
```php
/**
 * @param callable(int, string) : bool $callback
 */
function doThing(callable $callback) : void {}
```

Wrapping those in another set of parentheses would make it slightly easier to parse e.g.

```php
/**
 * @param callable((int, string) : bool) $callback
 */
function doThing(callable $callback) : void {}
```

**Comment by muglug** [comment]
Also @TysonAndre I'd encourage you to sign up for https://groups.google.com/forum/#!msg/php-fig/ywaSYo_tXdc/UE6_qfLhAAAJ

@ondrejmirtes already has (and what do you think of this syntax?)

**Comment by TysonAndre** [comment]
I'll consider signing up for it. I have some concerns about it stalling again if a large number of features get requested for the initial PSR.

**Comment by TysonAndre** [comment]
I noticed one ambiguity which may occur when serializing/unserializing these.

`@param Closure(string) : resource|false $callback` can be parsed two ways (`(Closure(string) : resource)|false` or `Closure(string) : (resource|false)` if return types can be false

One way to resolve this is to force the return type to be wrapped with brackets in the user's code if there's two or more types (e.g. @param Closure(string) : (resource|false) $callback

> Wrapping those in another set of parentheses would make it slightly easier to parse e.g. `callable((int, string) : bool)`

And that would be another way to avoid that amgiguity

**Comment by TysonAndre** [comment]
I'm still leaning towards `Closure():returnType` over `Closure(():returnType)` - The former is closer to `<?php function(): returnType {}`. To make this unambiguous if `[]` and `|` tokens were in the return type, the way I'd implement it would be:

> allow only a word token (with optional `?` prefix) as the return union type, **unless the return type is inside of `()`**.

- E.g. `Closure() : int` is parseable, and so is `Closure() : (int)` and  `Closure() : ?int` and `Closure() : (int|false)`, but `Closure() : int|false` would be unambiguously be parsed as a union type that can be a closure or false.

And potentially allow `<>`/`{}` after the return type without surrounding brackets in the future, if it won't conflict with any work on object types or templates or closure templates


---

**Also, what about documentation of references and parameters?** If this imitates PHP's syntax order, that would be `Closure&(?int&) : ?int` for `return function &(?int &$x) : ?int {$x = 2; return $x;};`

- `Closure&() : ?int` is probably easier for users to remember
- But `Closure() : ?int&` would be consistent with the way reference parameters are documented (Looks strange, though).
- Placing `&` before/after the `:` would also be possible

---

Another source of ambiguity is empty union types, which I believe psalm disallows (E.g. a type may be serialized as `Closure(int):void` if the first param is an int, `Closure():void` if the first param is an empty union type. If a linter supports empty union types, that could be worked around by consistently casting empty union types to mixed.

---

A shorthand I'd propose is `@param Closure(int) $callback`, which would be equivalent to `Closure(int):void` (Similar to `@method`'s treatment of absent return types).

**Comment by TysonAndre** [comment]
Also, what are you planning to do for optional parameters and variadic parameters?

My thoughts would be to have the below canonical representation for `function(int $arg = 2, string ...$remainingArgs) : string`

`Closure(int=, int...): string`

If an alternate syntax allows optional variable names for readability, `/** @param Closure(int $count=default, int... $args):string $callback` would be equivalent to the above. (See above comment mentioning `@method`)

**Comment by JanTvrdik** [comment]
I mostly agree with the proposed syntax, here is a more formal definition:

* Current ABNF grammar used by [phpstan/phpdoc-parser](https://github.com/phpstan/phpdoc-parser):
    * [type.abnf](https://raw.githubusercontent.com/phpstan/phpdoc-parser/7ab7c78f55a82d3705eb3f0b04c06f7c47fc4d65/doc/grammars/type.abnf)
* Proposed ABNF grammar change to support callable types:
    * https://github.com/phpstan/phpdoc-parser/commit/8ee5c2d94647bcf5cba0cd44fe7ffaa5e803add4 (gh has broken syntax highlighting for ABNF grammars)
    * [type.abnf](https://raw.githubusercontent.com/phpstan/phpdoc-parser/8ee5c2d94647bcf5cba0cd44fe7ffaa5e803add4/doc/grammars/type.abnf)

### Return Type Resolution

Assuming I have written the grammar correctly it should result in the following return type resolution rules:

~~~
callable(): A[]              -> ParseError, unexpected '['
callable(): A|B              -> (callable(): (A)) | (B)
callable(): A&B              -> (callable(): (A)) & (B)
callable(): ?A               -> (callable(): (?A))
callable(): A<B>             -> (callable(): (A<B>))
callable(): $this            -> ParseError, unexpected '$this'
callable(): callable(): A    -> ParseError, unexpected '('

callable(): (A[])            -> (callable(): (A[]))
callable(): (A|B)            -> (callable(): (A|B))
callable(): (A&B)            -> (callable(): (A&B))
callable(): (?A)             -> (callable(): (?A))
callable(): (A<B>)           -> (callable(): (A<B>))
callable(): ($this)          -> (callable(): ($this))
callable(): (callable(): A)  -> (callable(): (callable(): (A)))
~~~

I'm not sure whether it would be useful to allow `callable(): $this` as well.

The syntax for marking callable / Closure which returns by reference is a bit problematic.
  * Placing it before `callable`, i.e. `&callable`, does looks weird with intersection types
  * Placing it after return type, i.e. `callable: A&`, also looks weird with intersection types
  * Placing it before return type, i.e. `callable(): &A` seems like only reasonably option and yet a I don't like it very much.


### Parameter Types

I currently think  it's best to make it consistent with `@method`, i.e. making *parameter type* optional and *parameter name* required. That also make it easier to [resolve conflict](https://github.com/phpstan/phpdoc-parser/blob/7ab7c78f55a82d3705eb3f0b04c06f7c47fc4d65/src/Lexer/Lexer.php#L110-L111) between intersection type operator and reference operator.

Reference / variadic are declared in their usual place (matching `@method` syntax).
Default value is declared in the usual place and restricted to constant expression (matching `@method` syntax).

**Comment by TysonAndre** [comment]
https://github.com/phpDocumentor/ReflectionDocBlock/blob/5ea3cbf8cfc5d6d51fd56d85a1d455fba891b5f0/src/DocBlock/Tags/Method.php#L140-L153

The phpdocumentor2 implementation (product) allows at least one of the param type and param name to be specified. The phpdoc2 specification is vague on what is allowed as a `parameter`: https://github.com/phpDocumentor/phpDocumentor2/blob/v3.0.0-alpha1/docs/references/phpdoc/tags/method.rst (unit tests and examples seem limited to combination of type and name, at first glance)

Forbidding $this entirely in callables would help get rid of reference ambiguity in parameters

---

Also related: https://github.com/phpDocumentor/phpDocumentor2/issues/1712 (That issue was put on hold)

**Comment by TysonAndre** [comment]
Also, conceptually, closure types are types, and `@method` tags are declarations of instances of methods. Having parameter names seems less necessary for closure types. It would make code readable in some cases but not others, e.g.:

```php
/**
 * @param Closure(A):B $f1
 * @param Closure(B):C $f2
 * @return Closure(A):C
 */
function compose($f1, $f2) {
  return function(A $a) : C { return $f2($f1($a)); }
}
```

**Comment by muglug** [comment]
@JanTvrdik I love the syntax for closure return types. I might steal that grammar for a more formal type parsing step in Psalm.

I agree with @TysonAndre about requiring param types though (even `mixed` if necessary) for parameters. Anyone who uses this syntax will already be a high-level typer (insofar as this is already a niche annotation). Requiring param types (with optional param names) makes this a type-centric annotation, and I think that's ok.

Also a similar format exists for Flow/TypeScript closure types, and seems to work well there.

**Comment by TysonAndre** [comment]
> The syntax for marking callable / Closure which returns by reference is a bit problematic.
>
> - Placing it before callable, i.e. &callable, does looks weird with intersection types
> Placing it after return type, i.e. callable: A&, also looks weird with intersection types
> Placing it before return type, i.e. callable(): &A seems like only reasonably option and yet a I don't like it very much.

I mentioned another syntax earlier... Now that I think about it, that would potentially be ambiguous for intersection types (Intersection types wouldn't be followed by `:` after the right hand side, so I guess it depends on the parser used)

>  If this imitates PHP's syntax order, that would be Closure&(?int&) : ?int for return function &(?int &$x) : ?int {$x = 2; return $x;};

> Closure&() : ?int is probably easier for users to remember

**Comment by TysonAndre** [comment]
> I agree with @TysonAndre about requiring param types though (even mixed if necessary) for parameters. 

I was planning to require at least one of the parameter type or name, but that's probably optional to do, if it would cause parsing issues.

E.g. `Closure($x):int` would be equivalent to `Closure(mixed):int`

**Comment by muglug** [comment]
> I was planning to require at least one of the parameter type or name

How often would inputs to a closure actually be mixed? Or do you feel that just the presence/requirement of an argument itself is a useful indicator, and it's worth forgoing type information to get that?

**Comment by muglug** [comment]
> My thoughts would be to have the below canonical representation for
> `function(int $arg = 2, string ...$remainingArgs) : string`

> `Closure(int=, int...): string`

I like this syntax a lot

**Comment by TysonAndre** [comment]
If return types were optional, my suggestion was ambiguous, so never mind.

`Closure&(int)&int could be parsed as an intersection type of 2/3 types (parser probably wouldn't special case void)

**Comment by JanTvrdik** [comment]
### Syntax for callbacks returning by reference

So far two sort-of reasonable syntax have been proposed

1. `callable(): &A`
2. `callable&(): A`

and I dislike both of those. So I looked into real-world data and there are in total 5 anonymous functions which return by reference used in the top 1000 packages on packagist (it's a dataset I have locally downloaded for statistical purposes). Five out of 17 019, that is less than 0.03 %

So I'd like to propose a another option:

3. NOT supporting callbacks which returns by reference at all. At least initially.


### Requiring parameter type instead of parameter name.

Ok. It will make it slightly harder to distinguish between intersection operator `&` and reference marker `&`, but I guess it does not really matter whether I'm looking if the next non-whitespace token is one of (`TokenVariable`, `TokenVariadic`) or if it is one of (`TokenVariable`, `TokenVariadic`, `TokenEqual`, `TokenComma`, `TokenParenthesesClose`).

Requiring either parameter type or parameter name would only lead to unnecessary inconsistencies, so I'd much prefer to always require a parameter type.


### Required / optional / disallowed parameter default value expression

Just few random points.

Making parameter default value expression optional / disallowed would obviously mean `callable(A=null)` signature would (maybe unintuitively for some users) need to be changed to `callable(?A=)`.

I have initially liked the idea of using `default` keyword as placeholder for unspecified default value, but given type `callable(array $arr = default)`, the parameter `$arr` may or may not be nullable depending on the unspecified default values. That's quite problematic.

Disallowing parameter default value expression entirely is probably the easiest way how to approach the problem.


### Grammar update

Corresponding grammar update: https://github.com/phpstan/phpdoc-parser/commit/ac61dbcb1e6f25c4ac85718ea71db2f09f4e545d

**Comment by muglug** [comment]
> NOT supporting callbacks which returns by reference at all. At least initially.

At least, not supporting it in the type definition. I am 100% ok with this.

> Making parameter default value expression optional / disallowed would obviously mean `callable(A=null)` signature would (maybe unintuitively for some users) need to be changed to `callable(?A=)`.

I am also very OK with this, and thanks for thinking about it.

**Comment by TysonAndre** [comment]
> Making parameter default value expression optional / disallowed would obviously mean callable(A=null) signature would (maybe unintuitively for some users) need to be changed to callable(?A=).

I implemented that but didn't mention it earlier (I copied over most of my implementation from the way phan parses `@method` tags, which also treated `A=null` the same way as `?A = null`)

**Comment by dg** [comment]
Because 
- Closure is only small subset of callables 
- and Closure is class name that should be resolved using “use and namespace statements”
- and is not keyword, so Closure in different namespace may not be callable

the only meaningful keywords for this syntax are “callable” and “function“

**Comment by muglug** [comment]
@dg absolutely. I think we'd most likely stick to `callable` (because `function` doesn't appear in the PHP type system anywhere else).

Once the dust has settled I'll update the original post at the top with the consensus position.

**Comment by TysonAndre** [comment]
> and Closure is class name that should be resolved using “use and namespace statements”


`@param Closure(T1): T2 $varName` is unambiguous already. I don't think any analyzers mentioned in this discussion would allow parsing `@param SomeOtherUsedName(T1): T2 $varName`. `@param Closure $varName` without `()` would continue to use "use and namespace statements", and look up `MyNs\Closure` if the usage was in `MyNs` without any use statements. (Also mentioned in https://github.com/vimeo/psalm/issues/580#issuecomment-373963649)

I assume that both `callable(...)...` and `Closure(...)...` would be supported, with otherwise identical syntax.

E.g. those would be needed to be as specific as possible for these examples: (Although technically, it might be possible to represent that internally as `(\Closure)&(callable(T1):void)` internally in implementations supporting intersection types.)

```php
/** @param callable(T1) : void $f */
function invoke_callable(callable $f, T1 $obj) : void {$f($obj); }
/** @param Closure(T1) : void $f */
function invoke_closure(Closure $f, T1 $obj) : void {$f($obj); }
```

**Comment by JanTvrdik** [comment]
> I don't think any analyzers mentioned in this discussion would allow parsing `@param SomeOtherUsedName(T1): T2 $varName`

I disagree. I think it would be super-weird and very confusing to users if `Closure(mixed...): mixed` would be resolved differently than `Closure`. It make no sense to resolve `use` & `namespace` statements for one and not for the other. Therefore assuming we allow `Closure(mixed...): mixed` as more specific alternative to `callable(mixed...): mixed`, we must also allow

~~~php
<?php
use Closure as Foo;

/** @param Foo(mixed...): mixed $cb */
function (callable $cb) { ... }
~~~

For the same reason because

~~~php
<?php
namespace Foo;

/** @param Closure $cb */
function (callable $cb) { ... }
~~~

is invalid (missing `use Closure`), the following must be also invalid

~~~php
<?php
namespace Foo;

/** @param Closure(mixed...): mixed $cb */
function (callable $cb) { ... }
~~~

**Comment by TysonAndre** [comment]
> I disagree. I think it would be super-weird and very confusing

I'd say moderately (not super) weird and confusing. The alternate namespaced syntax I proposed would still be available. Also, the usage of `use Closure as Foo;` would hopefully be very low in practice.

There're already names that are valid only in phpdoc2 but are invalid in real types. E.g. `callback` in phpdoc already refers to `callable`, and not `Foo\callback` (But that's still troublesome to analyze if someone actually declared `Foo\callback` as a class)

http://docs.phpdoc.org/references/phpdoc/types.html

integer, double, callback, and boolean are already reserved in phpdoc2 but not in real types for php 7.0-7.2. (Same for resource?)

Aside: Hopefully, A language standardization proposal could make declaring a classlike with the name `Closure` outside of the global namespace deprecated in 7.3, and make Closure (without `\\`) consistently refer to the global scope in 8.x

- `int` wasn't a reserved word in php 5.6, but became a reserved word in 7.0

**Comment by JanTvrdik** [comment]
> There're already names that are valid only in phpdoc2 but are invalid in real types

Yes, and none of them refer to a class name. Because we already have a way to refer to a class name.

> Hopefully, A language standardization proposal could make declaring a classlike with the name Closure outside of the global namespace deprecated in 7.3, 

I hope not. What would be the benefit?

> int wasn't a reserved word in php 5.6, but became a reserved word in 7.0
Again, `int` is not a class. We already a way to refer to a class in type. And it includes resolving `use` & `namespace` statements.

**Comment by dg** [comment]
Closure is not special class, I think it can be (mostly) implemented in userland. We are talking about `callable`, fundamental part of PHP, not about Closure, so it would probably be better to concentrate on in.

Btw this is closely related https://wiki.php.net/rfc/callable-types

**Comment by ondrejmirtes** [comment]
I love @JanTvrdik's syntax suggestion and from the reception I can see it's a viable solution going forward, which is great!

I also agree with @dg about `callable` vs. `Closure`. I don't see a reason to typehint `Closure` because that's only one type of possible callable (others are arrays, strings and `__invoke`-able objects) and you can handle them all equally.

**Comment by muglug** [comment]
I see consensus around `callable():void`, and a lack of it around `Closure():void`.

There's nothing to stop particular implementers supporting `Closure` too, when followed by `(` – I know I will, simplifying it to `Closure&callable():void` internally. But I accept that may be a non-standard use case.

Perhaps @nikic has suggestions given the earlier RFC?

**Comment by dg** [comment]
IMHO Nikita Nefedov !== Nikita Popov :-)

**Comment by nikic** [comment]
@muglug Not related to that RFC, but from a quick scan of the discussion...

 * If you want to support return by reference, I'd go with `callable&()`, as that's what PHP uses for closure declarations.
 * What is the motivation for supporting optional parameters? Does that imply that the caller specifying this signature may invoke the callable either with or without the parameter? Note that it is always possible to downgrade a signature by making a required parameter optional, but not the other way around.
 * An important point of contention for the native support was that it actually required those signatures (up to LSP) to be specified when passing the closure. With correct variance handling, parameter types obviously don't have to be specified, but it did add the requirement to make the return type explicit. I'm assuming that static analyzers making use of these annotations will also accept a matching (up to variance) inferred return type, rather than requiring an explicit declaration?

**Comment by muglug** [comment]
> What is the motivation for supporting optional parameters? Does that imply that the caller specifying this signature may invoke the callable either with or without the parameter?

Yes, and also `Closure`s may be passed that lack the optional param.

> I'm assuming that static analyzers making use of these annotations will also accept a matching (up to variance) inferred return type, rather than requiring an explicit declaration?

Absolutely. And the same (but in reverse) for param types.

**Comment by JanTvrdik** [comment]
I noticed that there are some possible collisions with `@method` tag. 

For example `@method callable(): string foo()` can be parsed as 

1. method `foo` with which returns callable type
2. method `callable` with `: string foo()` as description<br>(if `@method` without explicit return type is allowed)
3. method `callable` which returns `string` and `foo()` as description<br>(if `@method` with PHP 7 return type syntax is allowed)

**Comment by muglug** [comment]
@JanTvrdik Psalm errors on that saying it's an `InvalidDocblock`: https://getpsalm.org/r/8046933f28, so that's not too worrying.

But it also fails to properly parse the `@method` docblock in https://getpsalm.org/r/cf2da23209, which is bad (and I've ticketed in #700)

**Comment by JanTvrdik** [comment]
> Psalm errors on that saying it's an InvalidDocblock

Based on what logic? It looks perfectly valid to me. `callable():string` is a valid *type* and standard `@method` syntax is `@method <type> <name>(<args>)`. How would you explain this behavior to end-user?

*(Also I'm not sure if this is something you consider relevant but the *PHP 7 return type syntax* for `@method` is used exactly zero-times in the top 1000 packages on packagist.)*

**Comment by muglug** [comment]
@JanTvrdik if they're using `callable() : string` as a return type on the LHS of an `@method` annotation, they're already pretty advanced.

I'd tell them to put brackets around the LHS, which Psalm understands without any issue.
```php
/**
 * @method (callable() : string) foo()
 */
class A {
  public function __call() {
  }
}
```
 https://getpsalm.org/r/8c6b88d601
