### ISSUE TITLE
Property-attribute issue when used in constructor promotion

### ISSUE THREAD

**Issue by zmitic** [vimeo/psalm#5881]
https://psalm.dev/r/a1854c9119

When attribute for parameters is used in constructor promotion, it is reported as an error.

**Comment by orklah** [comment]
Sorry, I don't know lots about attributes. Can you please explain the target use and how can I know the TARGET_PARAMETER is allowed on promoted properties?

**Comment by mathroc** [comment]
It looks like you can actually put them wherever you want

Doing it "wrong" will only throw an error when calling `newInstance()` on the `ReflectionAttribute()` as we can read on [the PHP doc](https://www.php.net/manual/en/language.attributes.classes.php#example-344)

I tried every combination here: https://3v4l.org/2t774#v8.1.1

And we can see that calling `newInstance()` on a "Property" attribute put on a promoted constructor argument works when we get the reflection attribute from the reflection property

**Comment by orklah** [comment]
Yeah, but it also works when the target is FUNCTION: https://3v4l.org/ZB3oi#v8.1.1

I don't understand how those targets are supposed to be used. If they're just declarative and have no effect whatsoever in php core, they *could* be used for checks from static analysis tools, but then, we need to establish the rules first. Do we allow a promoted property to have the PROPERTY target and/or the PARAM target?

**Comment by zmitic** [comment]
> Do we allow a promoted property to have the PROPERTY target and/or the PARAM target?

It should be both. But if it is hard to make, we can close the issue; the bug is **very** small and can be ignored.

**Comment by orklah** [comment]
I'm not sure it would be that hard, but I want to make sure I grasped the issue correctly.

Do you know if this TARGET feature is described somewhere? An RFC maybe?

**Comment by zmitic** [comment]
>Do you know if this TARGET feature is described somewhere? An RFC maybe?


No, and I think it has some bugs. For example: https://3v4l.org/vgsBv#v8.1.1

If you set `TARGET_CLASS`, it still works even though it doesn't make sense. So I guess future PHP versions will get that sorted out, someone must have reported it by now.

**Comment by orklah** [comment]
Let's leave that open for now. If there is someone that has special insight on what's going on here or if it's fixed in the future, we'll check that issue again

**Comment by mathroc** [comment]
From what I understand, this is all normal behavior, an attribute doesn't have to be an existing class, eg: https://3v4l.org/d069L#v8.1.1

So if the class is absent, PHP cannot and afaict won't ever, prevent to use any attribute anywhere. And this may be useful because we can get the name and arguments of the attribute even if the class does not exist. But I suspect this won't be used much and the majority of use will be trough using the `newInstance()` method. And it's only at that moment that PHP enforce the attribute target specification.

In my opinion the current behavior of Psalm is almost correct. But I think this issue is valid, think of it like that: a promoted constructor parameter is a `parameter&property` if an attribute is applicable to a `property` then this is ok since the promoted parameter does *is* a property.

in other words, an attribute declaring to accept a parameter as a target says only that, if the target is a parameter it's fine. if it's also a property it does not matter.

In the end I would relax the rules you already have only for this case

---

Another thing that could be interesting (but another subject entirely) is to identify this kind of error:

https://psalm.dev/r/6e6aad3a3b

Here calling `$att->newInstance()` is wrong because the attribute comes from a `ReflectionClass` and the `TaggedLocator` only accept parameter targets.

I can see Psalm already report `ReflectionAttribute` with a template type, `ReflectionAttribute<TaggedLocator>` here. I think it should also remember the source and be a `ReflectionAttribute<ReflectionClass, TaggedLocator>`. Nothing is wrong with having such an attribute, but calling `newInstance()` on it is invalid

**Comment by AndrolGenhald** [comment]
> Nothing is wrong with having such an attribute, but calling `newInstance()` on it is invalid

If anything I would think we'd report an issue here: `$r->getAttributes(TaggedLocator::class);`. We already consider it invalid to use that attribute on a class, shouldn't it also be invalid to get attributes of that type from a class, even if PHP itself doesn't care?
