### ISSUE TITLE
`InvalidParamDefault` false positive with class-name types

### ISSUE THREAD

**Issue by BackEndTea** [vimeo/psalm#5890]
https://psalm.dev/r/ee99f83ff7

**Comment by orklah** [comment]
https://psalm.dev/r/a0251cb551 would be better

Otherwise, you have a config in Psalm to allow string coercion to class-string: https://psalm.dev/docs/running_psalm/configuration/#allowstringtostandinforclass

**Comment by orklah** [comment]
Mmh, the setting doesn't seem to work here, I'll reopen this

**Comment by orklah** [comment]
Seems like I confused the `allowStringToStandInForClass` config with `allowCoercionFromStringToClassConst` that has been removed for a while now. I'm not sure about the reasons why the latter was removed but it seemed to have been partly replaced by the former.
I'll let this open to see if someone can clarify the situation. Feel free to close if `Exception::class` is good enough for solving your issue.

**Comment by orklah** [comment]
allowCoercionFromStringToClassConst has been flagged as deprecated since. And after checking, allowStringToStandInForClass  is actually pretty restrictive. It just allows using string for `new $string_var` or for `$string_var::method()`.

This could be extended to args and returns possibly but there is some work to be done here. 

I'll close this as answered for now given the low activity here :)
