### ISSUE TITLE
[MissingConstructor] Differentiate between access level of properties

### ISSUE THREAD

**Issue by ostrolucky** [vimeo/psalm#592]
It's one thing to scream here
```php
class Foo {
  private $bar;
}
```

and entirely different to scream here
```php
class Foo {
  public $bar;
}
```

This inspection does not differentiate between these.

**Comment by ostrolucky** [comment]
Closing, because now it's more obvious to me that this is just about missing __construt method (How did I not figure that out initially? :man_facepalming:)

**Comment by weirdan** [comment]
Not exactly. Your example first fails with 'property type missed', then, after adding the corresponding type it would fail with unitialized property, and after adding constructor it would complain about property not initialized in constructor. It indicated that class does not present (or hold to) a consistent interface. If you define a non-nullable type for a public property that is not initalized in constructor, you have to provide default value for it. Or you can define it as a nullable type, and it will be null by default.
```php
<?php
class ValidFoo1 {
  /** @var string */
  public $bar = '';
}
class ValidFoo2 {
  /** @var ?string */
  public $bar;
}
class InvalidFoo {
  /** @var string */
  public $bar;
  public function __construct() {}
}
```
`InvalidFoo` is invalid because after the point of initialization and before `$bar` is set the property would be null, but you haven't defined it as nullable:
```php
<?php
$f = new InvalidFoo;
// here $f->bar === null, but defined as a non-nullable string
```

**Comment by ostrolucky** [comment]
Yes, of course there will be different errors triggered by example code too. I'll definitely suppress specifically MissingConstructor in all of my projects though. It's too common to set dependencies via setter and I don't want static analysis tool to count with the fact these properties can be null, because it should not happen - it would mean bootstraping is wrong, I want opposite.

**Comment by muglug** [comment]
> I'll definitely suppress specifically MissingConstructor in all of my projects though

Don't feel bad - Psalm does too. But it's something Hack has that's also relatively easy to implement so I wanted that option.
