### ISSUE TITLE
null coalesce with null check combination not recognized

### ISSUE THREAD

**Issue by nscheer** [vimeo/psalm#6001]
https://psalm.dev/r/5ad510a5c1

I wonder if it was possible for psalm to understand the first variant.
Apart from the discussion if a local variable is more readable, it would be nice if psalm was able to understand such combinations.

**Comment by orklah** [comment]
If you take a look at this code: https://psalm.dev/r/7973e770b1 it's an example of an object that may return null once but not twice. The thing is that Psalm can't know because your object is not properly typed (so it may be a WeirdObject).

In the second example, you're safe because you only call the property once.

There's not much to be done here, unless you can type "object" more precisely

**Comment by nscheer** [comment]
Thanks for the clarification!
