### ISSUE TITLE
XlsWriter signatures are outdated

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6140]
/cc: @UrsusArctosUa

**Comment by pawel-slowik** [comment]
XlsWriter is a PECL extension. How do we handle callmap changes for PECL extension versions?

E.g. the signature of the `\Vtiful\Kernel\Format::align` method changed in commit https://github.com/viest/php-ext-xlswriter/commit/65f556f055db56478964ba296cafd2d3fa5d3b40 , which is a part of the 1.2.4 release. But you can still run XlsWriter 1.2.3 on a more recent PHP version.

Should I maybe correlate the XlsWriter changes with PHP release dates? IMO this is unrealistic, but no other idea comes to mind.

**Comment by orklah** [comment]
Is the latest version of the extension still compatible with old PHP version?

**Comment by pawel-slowik** [comment]
Yes, it is compatible with old PHP versions down to 7.0  That's what [package.xml](https://github.com/viest/php-ext-xlswriter/blob/9f70406a79aaf594db93d669c727192a0f444985/package.xml#L307) states and that's also how the [testing pipelines](https://github.com/viest/php-ext-xlswriter/actions/runs/1250894838) are configured.

**Comment by orklah** [comment]
Well, then I'd say to document only last version. That's what we did for other extensions

**Comment by pawel-slowik** [comment]
This got a bit tricky because apparently there's no up to date reference documentation for this extension:
- the [PHP.net docs](https://www.php.net/manual/en/book.xlswriter.php) are outdated,
- the [official documentation](https://xlswriter-docs.viest.me/) follows a more "by example" model instead of listing all method signatures.

I ended up generating the updated signatures via reflection. Unfortunately extension reflection only gets you method and parameter names, without types. So I edited the types manually, using the extension source code, official documentation and tests as references. Finally I removed signatures of some undocumented and untested methods.

All of this is using the latest release of the extension, 1.4.0.

Note that accepting this PR will put us out of sync with the outdated PHP.net docs, I hope that's OK. If you have any other ideas about how to handle this, let me know.
