### ISSUE TITLE
Taint analysis inaccurate if parent class not defined

### ISSUE THREAD

**Issue by mmcev106** [vimeo/psalm#6156]
In [this example](https://psalm.dev/r/98bf106bbc), no taints are displayed, even though I suspect they can & should be.  If you uncomment the parent class definition, they will display.

I work in an environment where PHP "modules" are loaded very dynamically (somewhat analogous to WordPress plugins).  It would be safest if we could run a taint analysis on individual modules, without requiring all their dependencies to be defined.  When I comment [this line](https://github.com/vimeo/psalm/blob/4.8.1/src/Psalm/Internal/Analyzer/ClassAnalyzer.php#L339), the taints will display anyway.  I believe this means this is technically do-able, though I'm not sure what the appropriate PR would look like...

If displaying taints regardless of parent class availability is not possible, would it make sense to display the `UndefinedClass` error that is displayed when [running psalm normally](https://psalm.dev/r/0b547e5c43)? As it stands, running a taint-analysis currently reports "No issues!" without any indication that some code was not really scanned due to undefined classes.

**Comment by orklah** [comment]
Running Psalm without some dependancies is weird. For a simple example like this one that doesn't interact with the dependancy, it's ok, but as soon as you have a `$this->callMethodInParent()`, Psalm will be quite lost.

I think the best possible solution for you would be to load stubs for your possibly undefined classes or to run an autoloader that will load your modules as needed

**Comment by mmcev106** [comment]
@orklah, that makes sense.  What are your thoughts on reporting `UndefinedClass` when a dependency is missing during taint analysis?

**Comment by orklah** [comment]
If we go this way, we'll have to add a bunch of other issues to stay consistent. There more than 15 Undefined* issues (like UndefinedInterface, UndefinedTrait, UndefinedMethod) that would most certainly have impact on taint analysis, but it won't stop there. InvalidDocblock for example will break taint analysis if there's taint specific tags in the docblock.

I think if we take this path, we'll probably regret it down the line because we'll have to judge wether an issue should or shouldn't be emitted in taint analysis and we'll have no clear choice.

Fortunately, Undefined* issues are already being reported even at high levels so it should be the first issues to be fixed in a given project so I don't think it will have a big impact. If there's situations were those issue can't be fixed, it would be best to work on that instead.

**Comment by mmcev106** [comment]
Does that mean that it is never recommended to run ONLY the taint analysis without running Psalm normally first (as the taint analysis may incorrectly report no errors)?

**Comment by weirdan** [comment]
Basically yes. Taint analysis was designed to be used in addition to normal Psalm checks, not on its own.

**Comment by orklah** [comment]
I'd say it depends what your goal is.If you want to guarantee that your code don't have vulnerabilities, running taint analysis only is risky because of all the other issues that can mask security problems.

If your goal is to incrementally improve your code, it doesn't really matter what issue you fix first.

There is a similar problem with Psalter (the tool that fixes issues automatically). When some issues are not solved, Psalter will make wrong assumptions and can produce broken code. It's not bad enough to outright warn users that they should fix all the other issues before trying it, but results should be taken with caution
