### ISSUE TITLE
psalm.phar fails to check the source it was built from

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#618]
Starting from 83811e6e8a4e74122a4c144993f36dad7dbe5deb `psalm.phar` reports errors when run on the psalm source it was built from. I was able to track it down to differences in bundled `src/Psalm/PropertyMap.php`, where failing version had `PhpParser\*` replaced with `PsalmPhar\\PhpParser`, and it seems it was done deliberately (see patcher changes in that commit).

I was under impression that file was meant to serve as a kind data asset, so it it shouldn't be scoped (well, maybe namespace part, but nothing else).

These patcher changes did not produce any differences in any of the other files that patcher is meant for (stubs and call map).

**Comment by muglug** [comment]
Yup, this is by design. The code in `src/Psalm/PropertyMap.php` that is not in Phan's equivalent is only there to help Psalm analyse itself.

I added an additional step to ensure that the scoped source passes its own Psalm checks, more or less (i.e. that the scoping doesn't break any behaviour).

The linked commit includes that self-check on the scoped files when running `bin/build-phar.sh`

**Comment by weirdan** [comment]
Well, I see some generally useful definitions in that file, as well as those Psalm-specific changes (PhpParser\*). To me it seems that psalm needs a way to configure those per-project. If this was the case, phar could bundle generic property map, and psalm.xml would add anything needed to check the project at hand (psalm itself in this case).

**Comment by muglug** [comment]
> To me it seems that psalm needs a way to configure those per-project

Agreed!

**Comment by muglug** [comment]
Related to  https://github.com/vimeo/psalm/issues/482
