### ISSUE TITLE
Error loading config paths in subdirectory

### ISSUE THREAD

**Issue by muglug** [vimeo/psalm#62]
If running Psalm from a directory with a config in a sub-directory (using `--config=path/to/file.xml`), relative paths to `<projectFiles />` directories will not resolve properly.

**Comment by svivian** [comment]
Hey, Disgruntled Goat from reddit here :)

I'm not sure that having the config in a different directory is the cause of the problem. I tried copying the file to the root of my project and I still get the same problem (no errors output).

**Comment by muglug** [comment]
Definitely *one* of the problems... I've made the errors much more obvious – try now and let me know what you see.

And thanks for being so patient!

**Comment by svivian** [comment]
OK so it looks like the paths must be relative to the XML file rather than the project root? I think I fixed the paths but it's still not working correctly. I set up a completely separate folder to try to isolate this. I have these files:

    /index.php
    /psalm.xml
    /src
        Comment.php
        /vendor
            test.php

psalm.xml:

	<?xml version="1.0"?>
	<psalm name="Barebones config" stopOnFirstError="false" useDocblockTypes="true">
		<projectFiles>
			<directory name="src" />
			<ignoreFiles>
				<directory name="src/vendor" />
			</ignoreFiles>
		</projectFiles>
	</psalm>

index.php:

	<?php
	include 'src/Comment.php';
	include 'src/vendor/test.php';

src/Comment.php:

	<?php

	class Comment
	{
		public $id;
		public $comment;

		/**
		 * No params here
		 */
		public function __construct($id, $comment='')
		{
			$this->id = $id;
			$this->comment = $undefined;
		}
	}

src/vendor/test.php:

	<?php
	echo $unknown;

Here is the output for various commands:


	$ psalm -c psalm.xml 
	Checks took 0.011067867279053 and used 3.844MB



	$ psalm -c psalm.xml src/vendor/test.php 
	Checks took 0.005871057510376 and used 2.737MB
	ERROR: UndefinedVariable - src/vendor/test.php:3 - Cannot find referenced variable $unknown
	echo $unknown;


	Checks took 0.0097551345825195 and used 3.175MB



	$ psalm -c psalm.xml src/Comment.php 
	Checks took 0.0080311298370361 and used 3.845MB
	ERROR: UndefinedVariable - src/Comment.php:14 - Cannot find referenced variable $undefined
			$this->comment = $undefined;


	Checks took 0.1380980014801 and used 20.174MB


	$ psalm -c psalm.xml index.php 
	Checks took 0.042136907577515 and used 2.735MB
	ERROR: MissingPropertyType - ./src/Comment.php:5 - Property Comment::$id does not have a declared type
		public $id;


	ERROR: MissingPropertyType - ./src/Comment.php:6 - Property Comment::$comment does not have a declared type
		public $comment;


	ERROR: MissingPropertyType - ./src/Comment.php:13 - Property Comment::$id does not have a declared type
			$this->id = $id;


	ERROR: UndefinedVariable - ./src/Comment.php:14 - Cannot find referenced variable $undefined
			$this->comment = $undefined;


	ERROR: UndefinedVariable - ./src/vendor/test.php:3 - Cannot find referenced variable $unknown
	echo $unknown;


	Checks took 0.28942489624023 and used 19.909MB



So there is a lot of inconsistency here, and I don't know what is supposed to be the correct output in each situation.

- `psalm -c psalm.xml` -- I'd expect this to check all the files in `src/` and ignore `src/vendor/`, so it should show the errors from `src/Comment.php`
- `psalm -c psalm.xml src/vendor/test.php` -- seems to be correct output.
- `psalm -c psalm.xml src/Comment.php` -- appears to be missing some errors.
- `psalm -c psalm.xml index.php` -- this shows additional errors from Comment.php. It also shows errors from `src/vendor/` which should be ignored.

Let me know if I'm misunderstanding things here :)

**Comment by muglug** [comment]
Update Psalm to latest – I just pushed https://github.com/vimeo/psalm/commit/e3a9cb98c3906ffc86d7c1500b37a524a46f46a3. When I run `vendor/bin/psalm --debug` on the above setup I now get:

```
Visiting src/Comment.php
Parsing src/Comment.php
ERROR: MissingPropertyType - src/Comment.php:5 - Property Comment::$id does not have a declared type
	public $id;


ERROR: MissingPropertyType - src/Comment.php:6 - Property Comment::$comment does not have a declared type
	public $comment;


Revisiting src/Comment.php
Analyzing src/Comment.php
ERROR: MissingPropertyType - src/Comment.php:13 - Property Comment::$id does not have a declared type
		$this->id = $id;


ERROR: UndefinedVariable - src/Comment.php:14 - Cannot find referenced variable $undefined
		$this->comment = $undefined;
```

**Comment by muglug** [comment]
The initial fix for this issue introduced the inconsistencies you encountered. Moving entirely to file paths (vs relative paths) seems to have fixed it, but feel free to reopen this ticket.

**Comment by muglug** [comment]
Oh, and one more remark about `vendor/bin/psalm index.php`: that file is outside of the config-provided project directories & files, so Psalm doesn't abide by the exclusions dictated in the config (hence the extra errors you see).

**Comment by svivian** [comment]
OK turns out the errors being omitted are due to the command itself, it's not picking up the `psalm.xml` file. Running either of these commands works:

    psalm --config=psalm.xml
    psalm -c=psalm.xml

It's not clear from `psalm --help` that you need the equals. Also, single-dash flags don't usually use equals, it's normally `--flag=value` or `-f value`.

> Moving entirely to file paths (vs relative paths) seems to have fixed it

Yes, I've updated and the output is consistent now.

> that file is outside of the config-provided project directories & files, so Psalm doesn't abide by the exclusions dictated in the config

OK fair enough.

**Comment by muglug** [comment]
> It's not clear from psalm --help that you need the equals. Also, single-dash flags don't usually use equals, it's normally --flag=value or -f value.

Makes total sense. I've fixed that here: https://github.com/vimeo/psalm/commit/dde39ed841598b06d8fb7a752c1393590a9b4568

**Comment by svivian** [comment]
Yep, all good! Kudos for your quick work.
