### ISSUE TITLE
List value verified with `isset` should be treated as `non-empty-list`

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#6254]
Hey there,

when having the following code, I would assume that this will result in `non-empty-list` for the `$list` variable.  

https://psalm.dev/r/36f4fac855

So when I have a list before using `isset`, I would expect having a list afterwards. And when checking with `0` or `positive-int`, I think it would be quite safe to make that "assertion" (e.g. `non-empty-list` for `$list`)?

Another thing what I think could be inferred would be: if a `true` from `isset` is returned when applied on a `list`, we could assume that if a variable was passed and not already explicitly known - e.g. by `TLiteranInt` - is `0|positive-int`.

```php
<?php
/** @psalm-var list<string> */
$foo = [];

/** 
  * @template T
  * @psalm-param list<T> $foo
  * @psalm-assert-if-true 0|positive-int $index
  * /
function assert(array $foo, int $index): bool
{
    return isset($foo[$index]);
}

/** @psalm-var int $int */
$int = 0;
assert($foo, $int);
/** @psalm-trace $int  Should result in 0|positive-int union in case it was int before */
```

What do you think, is that something which could be achieved in a meaningful way?

**Comment by orklah** [comment]
I agree about `isset($list[0])` or with any non-literal int could change the type to non-empty-list.

With any literal, it's more complex. TList in Psalm doesn't have any notion of length right now so you have to choose between `non-empty-list<string>` and still get errors for `$list[12]` even after checking with isset that 12 exists, or switch to `array{12: string}<int, string>` and forget that this was a list and that 11 is a valid offset too.

For the int part, technically yes, but I doubt this would have practical uses. I don't think anyone uses a list as a way to refine their offset variable.

**Comment by orklah** [comment]
I checked more in depth and it's more subtle than that.

types like `array{1: string}` are represented internally by TKeyedArray while `list<string>` is a TList.  However, TKeyedArray has a property `is_list` that allows it to behave like a list.

So when this is flagged to true (and it is in your example), `array{1: string}<int, string>` actually contains more details than `non-empty-list<string>`

However, there are places where TKeyedArray with is_list doesn't exactly behaves like a non-empty-list. For example:
https://psalm.dev/r/8f137e871a should not emit an issue (similar to https://psalm.dev/r/b47dedf1ae)

I'll close this because the initial suggestion is not correct, but feel free to reopen issues for when you have issues with a TKeyedArray with is_list that doesn't behave like a list
