### ISSUE TITLE
InvalidArgument incorrectly being shown with generic

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#6262]
I created a simple dictionary class here:  https://psalm.dev/r/bc7634d434.  When I instantiate the dictionary with some key-value pairs and try to retrieve one that is defined, all is good.  However, if I try to retrieve a value from a key that was not in the dictionary, Psalm is giving me an `InvalidArgument` error, which I believe is not correct.  Should this work as written without errors?

**Comment by weirdan** [comment]
See https://psalm.dev/r/d28560170f.

`TKey` is (correctly) inferred as `"foo"`, and `getValue()` only accepts `TKey`, thus rejecting `"baz"`. If type parameters were wider (e.g. https://psalm.dev/r/a917efbb39) it would accept that.

You may override the inferred type with `@var` docblock: https://psalm.dev/r/1c815d0ae0

**Comment by davidbyoung** [comment]
Thanks for the pointers. I guess I am confused why `TKey` is not inferred as type string when passing in `'foo'`, which would make the dictionary of type `<string, string>`.

**Comment by weirdan** [comment]
Psalm is always as specific as it can be when it infers generic type parameters. Was it otherwise it could just infer that as `<mixed, mixed>` and be done with that. `"foo"` *is a type* to Psalm ([a literal value type](https://psalm.dev/docs/annotating_code/type_syntax/value_types/#some_string-4-314), to be precise. Do not confuse that with `literal-string` type though, that's different).

**Comment by davidbyoung** [comment]
Thanks for the explanation!
