### ISSUE TITLE
Splat in constant array expression produces wrong array shape

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6263]
https://psalm.dev/r/fb451afec9

Expected: flat list (https://3v4l.org/0IdDo)

**Comment by orklah** [comment]
I took a quick glance at it. The issue is in here: https://github.com/vimeo/psalm/blob/c2ba1fec25f131ea04af7befa93a81ff95bf1797/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php#L1167

We loop over the class constants and we use SimpleTypeInferer::infer to calculate the type. Unfortunately, this method doesn't handle unpacking at all. We should probably take a look at how it's handled in ArrayAnalyzer::handleUnpackedArray and reuse code somehow

**Comment by weirdan** [comment]
@ondrejmirtes PHPStan also suffers from this bug: https://phpstan.org/r/f5a17feb-139f-433d-8503-6d081598e694

**Comment by orklah** [comment]
@weirdan FYI you can dump types in PHPStan, similar to @psalm-trace: https://phpstan.org/r/4b4198b8-b52a-4c72-b185-42b3b5c8dc94

**Comment by ondrejmirtes** [comment]
Please open a bug report in PHPStan's repo, thanks :)
