### ISSUE TITLE
False negative on undefined attribute class

### ISSUE THREAD

**Issue by laneroberts-ul** [vimeo/psalm#6287]
https://psalm.dev/r/e1a1ecfa6f

As both Bar and Baz are undefined, I would expect two UndefinedClass errors, not one. (Or an UndefinedClass and an UndefinedAttribute).

**Comment by AndrolGenhald** [comment]
This currently reports UndefinedAttributeClass for [attributes used on classes](https://psalm.dev/r/a2e0f88e71).

It should definitely be a separate issue from UndefinedClass since using a non-existent attribute is (intentionally?) [supported](https://3v4l.org/stntc) by PHP. At least if we report it as a separate issue, anyone who wants to use attributes that aren't defined can just suppress the issue globally.
