### ISSUE TITLE
Native intersection types

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6413]
https://psalm.dev/r/229fec5b31

https://wiki.php.net/rfc/pure-intersection-types

`nikic/php-parser` support for 8.1 is tracked here: https://github.com/nikic/PHP-Parser/issues/801

**Comment by davidbyoung** [comment]
Hey.  Out of curiosity, is this feature going to be supported some time soon?  No rush, just trying to get an idea of when I can run Psalm with intersection types.

Thanks!

**Comment by weirdan** [comment]
As far as I'm aware nobody is working on it at the moment.

**Comment by davidbyoung** [comment]
Ok, np. Thanks for the prompt reply!

**Comment by AndrolGenhald** [comment]
I had a branch I was experimenting on many months ago that overhauled psalm's type system and added first class support for intersections, with the goal of being able to do things like `lowercase-string&non-empty-string`, and even properly combine with unions (which PHP itself doesn't support yet) like `(lowercase-string&non-empty-string)|int`.

I'll see if I can find some time to dig it up, rebase on master, and see how much work it would take to make it viable. I ran into feature creep and eventually gave up on it, I think my initial goal was just to make the type system more intuitive and get rid of comparators. I wanted types to be able to be compared directly instead of having to use comparators, and instead of having weird edge cases in `TypeCombiner` I wanted to be able to have `new Union([new TString(), TNonEmptyString()])` automatically reduce the type and return a `Union` with only `TString`.

**Comment by petewalker** [comment]
@AndrolGenhald - were you able to dig up your branch, or is this issue still up for grabs?

Given the feature creep in your branch, is it better to add the 8.1 native typing as a first step, and then look at the bigger refactor?

**Comment by AndrolGenhald** [comment]
@petewalker I ran into the same problem I did last time, which is that Psalm makes a universal assumption that all types are Unions of Atomics. Adding first-class Intersections requires a lot of rewriting to make things work correctly. I'm still working through it, but it'll probably be another month or two (or more, depending on the time I can devote to it) before everything is fixed enough to merge, and it'll probably take more time after that review all of the changes. If you want to try adding native intersections just for objects using the existing HasIntersectionTrait feel free.

**Comment by orklah** [comment]
@AndrolGenhald Atomic is just a word. I think having a TIntersection extends Atomic should work, no?

**Comment by AndrolGenhald** [comment]
> @AndrolGenhald Atomic is just a word. I think having a TIntersection extends Atomic should work, no?

It's more than a word, it's assumed to be a single type (except edge cases like `HasIntersectionTrait`, but I'm not really a fan of how that's implemented, and it still only allows intersections of Atomics). Having Intersection extend Atomic seems confusing to me, and it would still require almost as many changes to allow Intersections of Unions. I figure it's better to take the chance to refactor the type system to make it more intuitive.

**Comment by orklah** [comment]
What I meant is that you can rename Atomic to fit your usage. Something like TypePart would be less charged semantically while still being consistent with our type system. Then, TIntersection would contain a list of Unions

so (A&B)|(C&D) would be an Union of two TypeParts who happen to be TIntersections with two Unions each. (Each Union would then contains TypeParts for A,B,C and D

You can indeed try to refactor the whole thing, but small steps are usually better. Keep in mind that changing the whole type system will probably leave Bruce and me in the dust, so we'll be of little help. And we'll have to add this into Psalm 6.
