### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by weirdan** [vimeo/psalm#6425]
from @niconoe- (https://github.com/vimeo/psalm/issues/6395#issuecomment-913151041)
- [x] #6426
- [x] #6427
- [x] #6428
- [x] #6429
- [x] #6430
- [x] #6431
- [x] #6468
- [x] #6470
- [x] #6471
- [x] #6472
- [x] #6837
- [x] #6841 (won't fix for now)
- [x] #6982 
- [x] #6994
- [x] #7364 

https://wiki.php.net/rfc/enumerations

**Comment by weirdan** [comment]
@niconoe- mind elaborating on those two non-linked points?

**Comment by niconoe-** [comment]
About `Enum are objects` I was thinking about the good behavior of using `instanceof` like described in the RFC. I didn't thos this was already developped as I tested in the default PHP version, not forcing it to PHP 8.1.  
You can remove this point, or check it to say it's already done.

About `Attributes are allowed on Enums and TARGET_CLASS also references Enums` I was thinking about something like https://psalm.dev/r/c31b9b8e81?php=8.1 or like this: https://psalm.dev/r/36779dc1b9?php=8.1

In the first case, the attribute usage is triggered by Psalm because `Status` is not a class (while enums are actually a subset of classes, if I understand correctly the concept in the RFC).

In the 2nd case, the attribute usage should be triggered by Psalm but not for the givven reason, as currently it's the fact that `Status` is not a class, but it should trigger the fact that the target is not respected.

Maybe there are still other cases to discover when mixing attributes with enums, but I'm not familiar enough with both of them to go deeper.

**Comment by ricardoboss** [comment]
In the same way that `value` is not recognized (#6468), `from` is reported as UndefinedMethod for backed enums.

**Comment by orklah** [comment]
- Enums can't be instantiated: https://3v4l.org/vB468#v8.1rc3

**Comment by jpresutti** [comment]
Enums in attributes are not properly detected for their types
https://psalm.dev/r/aa57812a88

**Comment by simPod** [comment]
- Enums have properties
- Interface `StringBackedEnum` exists
- Interface `IntBackedEnum` exists
- type of `IntBackedEnum->value` is `int` (same for `StringBackedEnum`)

 https://psalm.dev/r/9df7604507

**Comment by weirdan** [comment]
> Interface StringBackedEnum exists
> Interface IntBackedEnum exists

Do they? https://3v4l.org/3piBE#v8.1.1

**Comment by simPod** [comment]
Hm, my bad, looked into wrong stubs. So only this one should not give any error https://psalm.dev/r/461a456ffb.

**Comment by orklah** [comment]
As far as I can tell, Enum are now fully supported. Please open new issues if bugs are found
