### ISSUE TITLE
Type/null inference forgotten when using closure

### ISSUE THREAD

**Issue by bendavies** [vimeo/psalm#6460]
Hi there,

see https://psalm.dev/r/b5a2d77e60

impl 1 and 2 are functionally equivalent, but using a closure seems to make psalm forget that `$this->bar` is non-null.

Thanks

**Comment by weirdan** [comment]
As I said on slack, Psalm is actually not wrong here. `$this->bar` could change before the closure is called.

There's two workarounds:
1. Use `[$this->bar, 'equals']`: https://psalm.dev/r/f93fec8cea . It'll get easier on the eye with upcoming first-class callable syntax in PHP 8.1: `$this->bar->equals(...)`
2. Capture `$this->bar` instead of `$this`: https://psalm.dev/r/962131747c

**Comment by bendavies** [comment]
thanks @weirdan !
