### ISSUE TITLE
Type hinting conflict

### ISSUE THREAD

**Issue by zhukovsergei** [vimeo/psalm#6487]
Guys any ideas why the Psalm is mad about type hinting?

```
    /**
     * @psalm-return array<int, CustomerCollection>
     */
    public function findAll(): CustomerCollection;
```

![image](https://user-images.githubusercontent.com/1946769/133342918-505c0995-9adc-4d2f-89d6-49788d8e506a.png)

if I remove the docblock it will complain that doctrine return list<T> but you are return non-array `CustomerCollection`. How to resolve it then?

**Comment by zhukovsergei** [comment]
https://psalm.dev/r/75cbe1bd65

**Comment by orklah** [comment]
A list is an array of items. That means, the contract expects you to return an arrray and nothing else. In your case, you return a random class. Given the class name, I think it's supposed to be an Iterator (it's not the case in your snippet) but an Iterator is not an array and this doesn't respect the contract.

I'm afraid you should either not name your method findAll if you want to return an Iterator. Either that or the contract defined by Doctrine should be `iterable<T>` in order to accept iterator as well as arrays.

**Comment by weirdan** [comment]
Simpler put, you declared you're going to return array of `CustomerCollection`s in your docblock, but just `CustomerCollection` in the native return type. Both can never be true, so at least one is an error for sure.
