### ISSUE TITLE
mb_strtolower has wrong return type

### ISSUE THREAD

**Issue by snapshotpl** [vimeo/psalm#6531]
https://psalm.dev/r/042270ea20

**Comment by snapshotpl** [comment]
When changed execution order in `strtolower` also infern wrong type https://psalm.dev/r/7a469a04d7

**Comment by orklah** [comment]
The first part should be as easy as adding a stub for mb_strtolower, like there is already for strtolower: https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub#L508

The second part is a little more complex. It involve adding a method in AssertionFinder::scrapeEqualityAssertions named getEmptyEqualityAssertions (which would be the opposite of getEmptyInequalityAssertions) to find cases where we do `=== ''`. When we find them, we should add an `empty` assertion to the variable so that in SimpleAssertionReconciler::reconcile we could add a reconcileEmpty that would check for existing known TString or TLowercaseString to transform them into TNonEmptyString and TNonEmptyLowercaseString (that would also solve this: https://psalm.dev/r/d9332678bc)

**Comment by fluffycondor** [comment]
> like there is already for strtolower: https://github.com/vimeo/psalm/blob/master/stubs/CoreGenericFunctions.phpstub#L508

I'm not quite sure it's correct to assume strtolower returns lowercase-string. It's a lowercase-ascii-string if to be exact. `strtolower('École');` will return `École`. It can be confusing to have something like that in a var docblocked as lowercase-string.

**Comment by orklah** [comment]
Well, Psalm seems to considers `École` to already be in lowercase so it's coherent: https://psalm.dev/r/649f4508ac

**Comment by weirdan** [comment]
Fixed in #9678
