### ISSUE TITLE
Assume array key type casting

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#6539]
https://psalm.dev/r/00bbf29095

https://3v4l.org/RcCW5

**Comment by orklah** [comment]
Your example is pretty easy to fix. Your string is hard coded and we can process what the result will be.
We could also handle the case where the offset is a known `numeric-string` pretty easily.

However, both of those cases will be really rare in projects and it won't catch a lot of issues.

What's hard to fix is the case where the offset is a non-literal string. This would basically means every offset returned in such a case (with array_keys or foreach) would become `array-key` (which means, any combination of int or string, with a high tolerance as to what you can coerce this into). This would make Psalm miss a lot of relevant issues.

I think this is one example of a case where trying to spot a new issue would lead Psalm to be blind about a lot more other issues.

What could be done is to create a new config which would turn any string pushed in an offset comes out as `int|string`. This would have the same meaning as `array-key` except it would not be tolerant to coercion at all. Meaning any function that expects string will emit an issue if you push a variable that comes out of an offset. This would be reaaally strict and I don't expect this would be used by a lot of people. However, you're free to try to implement it!

**Comment by ro0NL** [comment]
The hardcoded string is an example. In production only `@return string` is known, hence an example as such.

If we could detect potential type juggling beforehand that be awesome :) 

> turn any string pushed in an offset comes out as int|string.

depending on context (eg. array_keys) this is always the case isnt it? (from a static analysis POV)

**Comment by orklah** [comment]
> depending on context (eg. array_keys) this is always the case isnt it? (from a static analysis POV)

Well, for now, you can put a `string` into the offset of a `array<string, string>` and retrieve `string` through array_keys. To solve your issue, it would mean either of those:
- You can't add a `string` to an `array<string, string>` (because of implicit casting), so unless you add literals, your array will become `array<array-key, string>`
- You can add `string` to an `array<string, string>` but when you try to retrieve the offset through array_keys, you'll always retrieve `array-key` or `int|string`

Both of those things imply that you'll never have a continuity of the string type from adding it to the array and retrieving it. This would be detrimental to a lot of projects, hence the suggestion of adding it as a config if you really want that

**Comment by ro0NL** [comment]
Not sure i follow :} i pursue out-of-the-box type-safety.

```
INFO: Trace - 17:1 - $stringsish: non-empty-list<string>
```

But the actual type is `non-empty-list<array-key>` IMHO (unless we know of a key type that doesnt juggle, ie. just `int`).

**Comment by orklah** [comment]
By config I meant something like "considers_string_arraykey_unsafe" with a default to false.

It's not a level on its own because doing that would let Psalm become less strict.

For example:
https://psalm.dev/r/43328eb2fd
With that example, Psalm can know the key is supposed to be string in rand() so it tell you that this is probably a mistake.
In the implode, it knows it's a string so it doesn't complain.

If you implement your change, you can consider `$b[0]` to be an `array-key`, in which case Psalm will stop complaining about rand() and don't complain about implode. Or you can consider it to be `int|string`, in which case, Psalm will complain about both.

So, right now, Psalm makes the good guess for 99.9% of cases but miss an error sometimes. With your suggestion, Psalm will stop making guesses and will either stop trying to emit issues or start emitting them on 99.9% of the cases to be able to catch the 0.1%

**Comment by ro0NL** [comment]
Sorry, still not following :(

AFAIK inferring `/** @var non-empty-list<array-key> $b */` solves bugs :)

https://psalm.dev/r/0934540cc5
https://3v4l.org/7ao6v
https://3v4l.org/J3WmZ

**Comment by orklah** [comment]
oh weird, I would have guessed that Psalm allowed that(that's supposed to be the difference with `int|string`). But it just shows my second point. You've now made impossible to pass any string through an offset without getting error. That's a lot of false positive added to find a possible bug

**Comment by ro0NL** [comment]
> You've now made impossible to pass any string through an offset without getting error. 

Right, i think i follow :) In a strict-typing world, as of some level, i'd close this gate.

Eg. i tend to make it explicit like https://psalm.dev/r/44b1714878

At this point psalm thinks `$b: non-empty-list<numeric-string>`, but actually it's `non-empty-list<int>`: https://3v4l.org/kHHot

makes sense?

**Comment by ro0NL** [comment]
> considers_string_arraykey_unsafe

could/should we flip the default in a next major? In effort to let psalm represent actual types. I think that's the fundamental issue i'm raising here.

**Comment by orklah** [comment]
What we would need to keep the string intact is a `non-numeric-string` so we know it's not changed by PHP internally, but it would not be a good idea to create that

>could/should we flip the default in a next major
I don't think it will ever be worth the time invested into it by users. Having too much false positive is not good looking for the tool. There's already a ton of config here to make Psalm stricter and even Psalm don't use them all

**Comment by ro0NL** [comment]
I give up :) I'll wait for bugs and solid data structures in PHP.
