### ISSUE TITLE
Incorrect flow analysis with yield in loop conditions

### ISSUE THREAD

**Issue by tux-rampage** [vimeo/psalm#6550]
Psalm does not check for side effects in a loop body when the condition would cause a `yield` in a Generator.

In line 22 psalm reports incorrectly, that the property is never falsy which is obviously not the case.

https://psalm.dev/r/407318e068

**Comment by orklah** [comment]
This is technically a false positive, but this is really not Static Analysis friendly at all. Even if Psalm was able to correctly analyze the flow of the loop and matched the yield correctly, The assumption that the property won't change value would still be the most probable, dropping this assumption would make Psalm blind to a lot of very basic errors. If we want to go that far, Psalm shouldn't even be able to assume that you didn't make an `unset($this->something);` somewhere and should require an isset on your property.

I'd suggest suppressing the issue, refactoring the code completely or at least fetching your property through a getter, which should make Psalm stop making this assumption. For example: https://psalm.dev/r/efe3d7815a

I'll close this because I don't think there's a lot more we can do here.

**Comment by tux-rampage** [comment]
@orklah Thank's for your feedback and insight.

Besides the fact that this code is far from good quality (it's just an example to show the effect), I'd argue that yield stops the execution flow of the method in a generator. That means anything (in boundaries of psalm validation) could have happened to the class state (unless it's immutable) after the yield statement was executed. This is especially true in Async frameworks like [amp](https://amphp.org/) which makes heavy use of Generators as Coroutines.

What I'm talking about is not some odd code that calls `unset()` or bypasses psalm validation by setting anything. What I mean is that after a yield, a narrowed type like  `object|null` -> `object` for an outer scope variable (like `$this` properties, global scope, static properties) or properties of objects that are exposed to outer scope (like properties of yielded objects) might no longer be true and must be reset to initially known type (`object|null` as for this example).

I get your point, that this is not easy to analyse and maybe its such an edge case that it's not worth putting the effort into it. But it's still a technically incorrect behaviour.

@kelunik Is that something AMP users need to be aware of?

**Comment by tux-rampage** [comment]
> I'd suggest suppressing the issue, refactoring the code completely or at least fetching your property through a getter, which should make Psalm stop making this assumption.

Works only unless the first part of the condition is important for the yield part, which breaks your refactoring:

https://psalm.dev/r/0822b06a4b

The original code stays valid.

**Comment by orklah** [comment]
It's not so much a question of what's worth it or not, it's just that if we take your example and remove the side effect, what's left is an obvious bug: https://psalm.dev/r/3cbd840ff8, one that should be reported by Psalm if possible but we can't have both.

For Psalm it's a tradeoff: should we assume the variable will change and stop reporting issues when it doesn't or should we assume the variable won't change and miss the kind of errors you showed.

My point was to say Psalm is better off assuming the variable won't change because I believe in most case it won't.

But I agree with you, you're technically correct
