### ISSUE TITLE
`PossiblyNullArgument` now reported as `NullArgument`

### ISSUE THREAD

**Issue by AlexandruGG** [vimeo/psalm#6685]
### Description

Hello,

I think [release 4.10.0](https://github.com/vimeo/psalm/releases/tag/4.10.0) potentially introduced an issue where a former `PossiblyNullArgument` error is now incorrectly reported as `NullArgument`. Managed to reproduce it in the playground:

https://psalm.dev/r/6b1745b479

I know the example might be a bit complex but couldn't reproduce it with a simpler one. I'll try to clarify it:

- `current` from the `Currentable` interface returns `T|null`
- `current2` from the `CollectionInterface` has the **same** return type
- `CollectionInterface` extends `Currentable`

### Desired behaviour
Both of these methods return the same union type. A null check on the result is valid.

### Current behaviour
Psalm reports that `current` always returns `null` via the `RedundantConditionGivenDocblockType`, which does not seem correct.

The same example in PHPStan does not report any issues: https://phpstan.org/r/fff430c3-1547-47d6-8113-39526e371142

**Comment by orklah** [comment]
Template annotation inheritance is a weird issue.

When you name a template `T`, Psalm will namespace it with the class/interface it's in (so something like `CollectionInterface:T`). When you have an implementation of this interface you have to add `@implements CollectionInterface<TKey, T>`, So you're creating a new T (`Collection:T`) who will fill the gap for the old T. But template names are just names. You could have as well called your template U, and even created a new template T that means something else entirely.

And at this point, you override a method without adding annotation. It's unclear what Psalm should do:
- Forbid this and require an explicit annotation?
- Allow this and use a template with the same non-prefixed name?
- Allow this and use the template that took the place of T in the interface?

Currently, Psalm seem to do the first one. I'm not too sure that it's a good idea to do something implicitly because of the confusion on the rules.

**Comment by AlexandruGG** [comment]
> sorry, I answered without checking if my assumption was correct, it was not. At least, not at the location I thought.
> 
> Your example can be resolved like this though: https://psalm.dev/r/f7fd753d73.
> 
> It adds a `@return CollectionInterface<TKey, T>` to first.

Thank you very much for this @orklah . Could I just clarify a couple things please?

1. How come the extra type hint is needed on the `first` method, but not on the implementation of `current` or `current2`? Should these have it as well?

2. Does this mean that when using an interface with template parameters it's necessary to repeat the doc blocks in the implementing classes, as well as the interface itself?

**Comment by orklah** [comment]
Seem fixed

**Comment by drupol** [comment]
Merci <3

**Comment by AlexandruGG** [comment]
> Seem fixed

Nice one, thank you! 💯
