### ISSUE TITLE
Dont report DuplicateFunction if wrapped in !function_exists

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#6767]
If a function is wrapped in !function_exists check, do not report it as duplicate function: (that's why we check function_exists, otherwise function_exists would be completely unnecessary)

https://psalm.dev/r/2eeefd6d49
https://psalm.dev/r/68c5db8c25

This is a common occurrence when creating compatibility code for legacy or 3rd party things, where we need to provide basic functions that should be there, but are not in all cases, so we put the !function_exists with that function.

**Comment by kkmuffme** [comment]
Using PHP logic, we go from top to bottom of the script - **functions declared earlier have priority**

For your example this means:
line 8 - NO DuplicateFunction error, since we have it wrapped in !function_exists
line 11 - give error, bc the required arg is missing
line 13 - give error bc stdClass is not a string
line 14 - same as 11, but also bc assigning void to $a

**Comment by orklah** [comment]
> functions declared earlier have priority

By that logic, the function that is not defined here but may exists (because of the !function_defined) has priority. But then, what if we find this function in vendors? In Stubs? The second problem is, Psalm will possibly find those functions in different files. How should it decide which is first? It will be random, and possibly change between analysis.

And what if there's one in function_exists but not the other?

I really believe those are issues that should not be solved by static analysis as they're too dependent on runtime. The answer you gave me is the one that is more adapted to your situation, but it will probably not be for others.

Note: PHPStan ditch the first one and register only the second one.

The best I can propose is to document this in the issue. And I also suppose, if the function is stubbed, stubs should take priority and just ignore (or emit DuplicateError) when finding other function with the same name

**Comment by kkmuffme** [comment]
You are correct in all points, I wasn't aware psalm isn't parsing from an entry point, which would ensure the same ordering in all cases.
Fyi this issue not only happens with stubs, but more commonly also with functions in prended files or php native libraries.
e.g. if we have a auto-prepend PHP file which defines a function, and that function is again defined in normal code (but in a !function_exists) this issue comes up too.

Anyway, to keep things simple and what my initial intention was:
if a function is wrapped in !function_exists, don't give a "DuplicateFunction" error for it.

**Comment by orklah** [comment]
This won't happen. This is useful to warn users that their code is too runtime dependent to be checked by Psalm. If we remove this, Psalm will silently skip analysis around those functions.

Why don't you suppress those errors if you don't want them?

**Comment by kkmuffme** [comment]
Because I can't suppress psalm errors for a file (and in another issue this was a nofix too). And suppressing 100s of errors in a file is a pain.
Anyway, built my own psalm post-processor to filter out all these issues and included a @psalm-suppress-file feature.

**Comment by orklah** [comment]
> Because I can't suppress psalm errors for a file

You can with issueHandler
