### ISSUE TITLE
How to suppress UnusedPsalmSuppress?

### ISSUE THREAD

**Issue by donquixote** [vimeo/psalm#6786]
I have code that produces an inspection warning in PHP 7.4, but not in PHP 8.
I am using `@psalm-suppress all` to suppress in PHP 7.4, but now I get `UnusedPsalmSuppress` in PHP 8.

How can I suppress all of it?

**Comment by donquixote** [comment]
> Hey @donquixote, can you reproduce the issue on https://psalm.dev ?

I don't think so. I cannot control the php version on psalm.dev.

**Comment by donquixote** [comment]
To clarify, I am using the cli parameter ` --php-version=8.0` to switch version.

**Comment by weirdan** [comment]
> I don't think so. I cannot control the php version on psalm.dev.

You can, by using `?php=` query parameter. E.g. https://psalm.dev/r/e200b6c83e?php=7.1 vs https://psalm.dev/r/e200b6c83e?php=8.1

**Comment by donquixote** [comment]
I can't get psalm.dev to give me `UnusedPsalmSuppress` :(
At least the "RedundantCast" should be seen as redundant suppression.
Perhaps another query parameter? Are those documented somewhere?

**Comment by orklah** [comment]
Not all config are available through psalm.dev. This one must be one of them.

To suppress UnusedPsalmSuppress, check this part of your config: https://psalm.dev/docs/running_psalm/configuration/#issuehandlers

**Comment by donquixote** [comment]
I suppose this is to globally suppress UnusedPsalmSuppress?
I would like to do this locally, for a specific piece of code only.

**Comment by orklah** [comment]
https://psalm.dev/docs/running_psalm/dealing_with_code_issues/

**Comment by orklah** [comment]
I'm closing this because I'm afraid there's no simple better solution here.

The suppression module for this specific issue is complex. Issues may come from a lot of places inside Psalm, that's why UnusedPsalmSuppress has to be near the end of analysis and work its way through already emitted issues and check if every suppression has been used. However we're completely out of the analysis at that point and we have no way to access inlined suppression in the code anymore.

There may be grounds for improvements if we were to store this suppression from the start inside IssueBuffer and we'll welcome PR on this but we won't work on it. If someone wants to, a good place to start is by looking at IssueBuffer::addUnusedSuppression

**Comment by orklah** [comment]
Well, turns out @AndrolGenhald found a solution for this issue here: https://github.com/vimeo/psalm/pull/7133. It will be available on next release
