### ISSUE TITLE
Non-negative integer assertion not working

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#6797]
https://psalm.dev/r/bc9c74c3d2

**Comment by orklah** [comment]
This is is a limitation due to Psalm being unable to negate `lesser than 0` into `0|positive-int`. This is is the kind of issue that can be fixed by integer ranges pretty easily but they're hard to introduce because loops are pretty complex things and trying to be more precise in it is a problem so we have to go slowly

**Comment by weirdan** [comment]
There are no loops here though.

**Comment by orklah** [comment]
No, but removing positive-int as an assertion solve this but break loops :p
