### ISSUE TITLE
InvalidDocblock when annotating promoted property with @var only

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#6857]
https://psalm.dev/r/f99085fcfb

Also adding non-type property annotations does not have any effect: https://psalm.dev/r/c33004265b. I can add a separate issue if needed.

**Comment by orklah** [comment]
Yeah, please open a new issue for the second example

**Comment by orklah** [comment]
The error is caused by https://github.com/vimeo/psalm/pull/6764 , Psalm thinks `iterable` comes from param type and `iterable<string>` comes from property type. We should probably allow signature return type to be independant for that check

**Comment by orklah** [comment]
I'll think about it this afternoon. This issue dug up the exact problem we were trying to solve by forbidding to have more than one type.

At worse, we could have something like
```php
public function __construct(
        /**
         * @var string
         * @param int
         */
        private float $param,
    ) {
    }
```
And we have to decide what to do with that
and we have to decide

**Comment by orklah** [comment]
The most natural way to do that in Psalm would be:
1) The param type must be equal or more precise than the property type
2) The param type is defined by "the param docblock ?? the signature type ?? the property docblock"

Those are the rules when there are no promoted properties, but those two rules make the first example fail because the param type becomes `iterable<mixed, mixed>` and the property type is `iterable<mixed, string>`

To make the example pass, those rules should be applied:
1) the param and property types must be exactly the same
2) the param and property types are defined by "the param docblock ?? the property docblock ?? the signature type"

I think it's a little weird to do that because then, there is absolutely no difference between a param docblock and a property in terms of features so why bother using @var here?

The first set of rules would also allow this:
https://psalm.dev/r/3b7fd246d1
In this example, we restrict the type of the incoming parameter while still allowing the property to have a wider type than the param. With the second set of rules this becomes impossible (as both must be absolutely equal)

I'm really conflicted on what to do here. I'm not sure what would be best. @weirdan @ondrejmirtes WDYT?

**Comment by ondrejmirtes** [comment]
Hi, when I was implementing promoted properties in PHPStan, I wasn't sure how people are going to use it. So PHPStan supports declaring promoted property type through both `@param` and the `@var` style here.

So in case of constructor `@param` tag, it uses the type for both the method parameter (for instantiation) and also for the property type.

In case of `@var` (https://phpstan.org/r/e79ca1d7-529f-49d6-abdb-55eb81d27138), it uses the type for the promoted property and it also uses it for the parameter type in this special case.

I don't know what would happen if someone uses both `@var` and `@param` for promoted property, I haven't defined that case, and I don't know why anyone would want to choose that.

I don't know if there's some unclear case to take care of, if it is, please ask about that :)

**Comment by weirdan** [comment]
I think as far as docblocks are concerned we should require `@var` and `@param` to be the same if both are present for some reason, otherwise use whatever is there for both property and parameter type. This gives us a single docblock type. And its relation with the native type should be the same as we have now for parameters - that's 'docblock type should be a subtype of native type', if I'm not mistaken.

**Comment by orklah** [comment]
Thanks for your answers! I'll read that calmly tomorrow and I'll fix that :)
