### ISSUE TITLE
MixedReturnTypeCoercion with functions returning arrays

### ISSUE THREAD

**Issue by mrpavlikov** [vimeo/psalm#6862]
https://psalm.dev/r/3b4c85bee9

After upgrading from Psalm 3 to Psalm 4 I've got many errors like this for arrays. If you specify `$array = [];` its all good, but if some function returns array it does not work anymore.

**Comment by orklah** [comment]
The issue is that `array` for Psalm is `array<array-key, mixed>` and means "any array filled or empty with mixed keys and mixed values".

This is different than `[]` which Psalm translate to `array<empty, empty>` and means "an empty array".

So when you return `: array`, Psalm can't know what kind of data you have in there so it's not so easy to replace `array<array-key, mixed>` by `array{foo: string}`. However, it can be discussed given the current meaning of `array{foo: string}` is "an array containing at least a key named "foo" with a string value" so it doesn't exclude other possible content for the array.

If your need is really to return empty arrays to be filled later, then what you need is:
https://psalm.dev/r/62347f5b1a

Otherwise, can you give us a more detailed use case?

**Comment by mrpavlikov** [comment]
My case is exactly "an array containing at least a key named "foo" with a string value", and it worked fine for PhpStorm + deep-assoc-completion plugin + Psalm v3, but not with Psalm v4 :/

**Comment by orklah** [comment]
Psalm 4 came with a lot of improvements yeah, it's expected that more issues are reported. I gave you a solution in the previous post and after checking, PHPStan also behaves like Psalm on this. I don't consider this as a bug

**Comment by mrpavlikov** [comment]
I don't see logic in how this does not pass: https://psalm.dev/r/2d0987d6b3
But this passes: https://psalm.dev/r/17ae49d841

What solution did you give, I'm not following? To type hint function as `@return array<empty, empty>`? I'd rather `@psalm-suppress`, because it makes more sense. That function returning array is sometimes in library I can not control also.

Dunno about PHPStan, but I consider this as a bug tho.

**Comment by orklah** [comment]
The logic is explained on my first answer. An empty array is not the same thing as a indefinite array

Adding a new key to an empty array makes an array with just one key
Adding a new key to an indefinite array makes an indefinite array

The solution is indeed to document `@return array<empty, empty>` when you're returning an empty array, it's the more detailed version of `array` when you know there is no keys/values in the array

If the return is in a library you cannot control, you can use stubs to override the returns that are not precise enough.

But yeah, feel free to suppress issues when you can't or doesn't want to fix them, that's why it exists.

**Comment by CthulhuDen** [comment]
@orklah You said it yourself `the current meaning of array{foo: string} is "an array containing at least a key named "foo" with a string value"`. So how again does it make sense to you that arbitrary array after having key `foo` added to it cannot satisfy return type `array{foo: string}`?

**Comment by mrpavlikov** [comment]
Forget about the empty array please, it was just for example. I didn't know you treat those in such a different way. But this array works well too:

```
/** @psalm-return array{bud: string} */
function getArray(): array
{
    return [
        'bud' => 'light',
        'more' => 'keys',
        'added' => 'here',
    ];
}
```

That clearly shows it is being treated as "array containing at least a key named 'bud' with a string value", since it obviously contains more keys. And if I add my `foo` key to this it is fine, but without this docblock I can't do it.

**Comment by orklah** [comment]
Yeah, I said it wouldn't be too far fetched to transform `array<array-key, mixed>` into `array{foo:string}` after adding foo to it.

This is touching the borders of what analysis tools can handle because to support this, it would also mean `array<string, mixed>` should change. To prevent loosing information (that all keys are string), we would need this notation: `array{foo: string}&array<string, mixed>` but this syntax is only supported by Psalm and it's contested (using intersection like that does not make sense).

I'd be up to this change if PHPStan or Phan would behave like that, but turns out [Phan](https://phan.github.io/demo/?code=%3C%3Fphp%0A%0A%2F**+%40return+array%7Bfoo%3A+int%7D+*%2F%0Afunction+foo%28%29%3A+array%0A%7B%0A++++%24array+%3D+%5B%5D%3B%0A++++%24array%5B%27foo%27%5D+%3D+%27bar%27%3B%0A++++%0A++++return+%24array%3B%0A%7D%0A%0A%2F**+%40return+array%7Bfoo%3A+int%7D+*%2F%0Afunction+foo2%28%29%3A+array%0A%7B%0A++++%24array+%3D+getArray%28%29%3B%0A++++%24array%5B%27foo%27%5D+%3D+%27bar%27%3B%0A++++%0A++++return+%24array%3B%0A%7D%0A%0A%0Afunction+getArray%28%29%3A+array%0A%7B%0A++++return+%5B%5D%3B%0A%7D%0A%0Aecho+foo%28%29%5B%27foo%27%5D%3B%0Aecho+foo2%28%29%5B%27foo%27%5D%3B) also behave consistently with Psalm and PHPStan.

I won't personally work on this because I value consistency between tools, but I'd accept a PR who goes this way if you're up to it. If PHPStan or Phan revisit this on their tool, we can discuss about it again

**Comment by weirdan** [comment]
@orklah don't we have an internal notion like `array{a:b}<c,d>` (it's invalid in docblocks, but I think I've seen it in error messages)?

**Comment by weirdan** [comment]
https://github.com/vimeo/psalm/blob/68495be1473004398c8b934b8b554db2de7acfbe/tests/TypeParseTest.php#L184

**Comment by orklah** [comment]
Yeah, it's the same thing as the intersection: https://psalm.dev/r/ca6b6c3056. Maybe a parser issue prevented the two syntax being the same?

**Comment by orklah** [comment]
This was fixed
