### ISSUE TITLE
Using equality to narrow down int range

### ISSUE THREAD

**Issue by still-dreaming-1** [vimeo/psalm#6871]
https://psalm.dev/r/e825568c19

**Comment by orklah** [comment]
This is handled in https://github.com/vimeo/psalm/blob/b7834689e53eda8bd1675ef3edebe4ff4ed548cc/src/Psalm/Internal/Type/NegatedAssertionReconciler.php#L394

The method does not check integer ranges into account. I actually tried to change that a week or two ago but as usual when I try to change things around integers, it makes loops goes crazy.

The comment I posted here is relevant https://github.com/vimeo/psalm/pull/6474#issuecomment-958198889

I should try to work around issues, but these tries takes a lot of time and it's pretty depressing to see it was for nothing when the whole CI fails

**Comment by orklah** [comment]
I tried to tackle this again but hit the same wall as always. If you're curious, here's the branch:
https://github.com/orklah/psalm/tree/negatedLiterals

and the test suite:
https://github.com/orklah/psalm/runs/4169544216?check_suite_focus=true

In the test suite, there is one monstruous code that is actually extracted directly from Psalm code that would take me weeks to understand and reason about:
https://psalm.dev/r/19a33b692f

Currently, this only works because Psalm reverts everything that moves to an int or positive-int who are two very coercable types (you can put those types pretty much everywhere without Psalm complaining it's too large) but as soon as you try converting that to literal ints or int ranges, Psalm start to freak out :)

Fixing every loop inferrence issue could help with that, but I don't think I'll have the patience to do that alone and even then, I'm not even sure it is possible to compute this kind of loop without starting to actually execute the thing turn by turn in order to see what can happen

**Comment by still-dreaming-1** [comment]
Thanks. I guess we will have to stick to alternative types of integer comparisons for now.

https://psalm.dev/r/fa2b700f26
