### ISSUE TITLE
Invalid SoapClient::__doRequest() signature

### ISSUE THREAD

**Issue by veewee** [vimeo/psalm#6901]
The stubs indicate that the `$one_way` variable is an integer. 
Since PHP 8.0 this is a bool.

https://github.com/vimeo/psalm/blob/2d0758ab104b615786a85bda83894b6d26a29266/stubs/soap.phpstub#L261-L268

See https://www.php.net/manual/en/soapclient.dorequest.php

> 8.0.0 | The type of oneWay is bool now; formerly it was int.

**Comment by orklah** [comment]
Ouch, tough one.

This stub is not version dependant so we can't just replace int to bool without messing with lower version. We could allow both int and string but we would not be able to see errors both in older and newer versions.

I'm not sure why we have a stub for this instead of just relying on the CallMap. I guess removing this method from the stub and fixing types directly in the CallMap could work.

Could you try to push a PR doing that and we'll see if it pass?

**Comment by veewee** [comment]
Hello @orklah,

I tried removing the stub method and all tests seems to pass.
See https://github.com/veewee/psalm/actions?query=soap-stubs 


However, If I run that version of psalm on my repo, I get errors like

```
ERROR: MethodSignatureMismatch - src/AbusedClient.php:51:14 - Argument 5 of Soap\ExtSoapEngine\AbusedClient::__doRequest has wrong type 'bool', expecting 'int' as defined by SoapClient::__doRequest (see https://psalm.dev/042)
        bool $one_way = false


ERROR: InvalidArgument - src/AbusedClient.php:66:94 - Argument 5 of SoapClient::__doRequest expects int, bool provided (see https://psalm.dev/004)
        $this->__last_response = parent::__doRequest($request, $location, $action, $version, $oneWay);
```

So I guess that doesnt fix it? Or do I have to do anything special in the code for that new stub to get picked up?

**Comment by orklah** [comment]
Yeah you should also make a few changes in callmaps:
https://github.com/vimeo/psalm/tree/master/dictionaries

CallMap contains current types and then CallMap_XX_delta are delta files in order to know which version changed what. So you should change SoapClient::__doRequest on CallMap.php and CallMap_80_delta

See https://psalm.dev/docs/contributing/editing_callmaps/ for more info on how to edit those

**Comment by veewee** [comment]
That does the trick indeed!
Created a PR.

**Comment by veewee** [comment]
@orklah, I just noticed that the return type is invalid as well. It is `?string` instead of `string`.
I can't find a place in the CallMap to change this. Any clue? :)

**Comment by orklah** [comment]
The return type is the first element of the array in the callmap, just before the parameters (that are named). Should be easy to change :)
