### ISSUE TITLE
In some cases, Psalm ignores that PHP converts string array keys to int

### ISSUE THREAD

**Issue by mathroc** [vimeo/psalm#6923]
https://psalm.dev/r/5401e80338

the first array should be a `array<array-key,int>` not a `array<string,int>`

**Comment by mathroc** [comment]
I guess fixing this would however makes Psalm miss a lot of opportunities to report relevant issues. Maybe it would be useful to have a non-numeric-string ?

**Comment by orklah** [comment]
> I guess fixing this would however makes Psalm miss a lot of opportunities

Precisely. A non-numeric-string would be almost impossible to check, but more importantly, it would conflict with other type in weird ways (in a non-numeric-string goes through `strtolower`, should it stay a `non-numeric-string` or become a `lowercase-string`?)

A clever way Psalm resolves certains issues like that is by having a special flag

For example, `PHP_INT_MAX + 1` gives float in PHP. However, in most cases, Psalm doesn't know the value of the two ints it adds, but returning `int|float` would create a lot of false positives.

Psalm resolves this by returning an `int` with a flag `from_calculation` which prevent Redundant errors when someone want to check is_float on the result.

Psalm could use something like this for any string returned from an array-key that would prevent emitting Redundant errors on is_int

(I believe we already have an issue with this suggestion somewhere, so this issue may be a duplicate)

**Comment by orklah** [comment]
Yeah, but that's seriously the risk when talking about new types. It can quickly become hell just to list the types, but remember that after that, we have to code each interaction between every type. Want to add to string together? It has to be coded. Want to concatenate? It has to be coded. Want an union of those? Is has to be coded.

That's why we're very prudent about adding types. It's not simply a new class, it's hundreds of interactions to think about for each new class.

**Comment by mathroc** [comment]
indeed, adding a `non-numeric-string` looks like a bad idea. 

What would you think about making the array a `array<array-key,T>` instead when some keys are "unknown" strings?

**Comment by orklah** [comment]
Well, this reverts back to 
> this would however makes Psalm miss a lot of opportunities

Let's imagine this code: https://psalm.dev/r/b73985bc04

For now, Psalm is happy to consider that the string you put in the offset is okay and the code is good.

However, if we start saying that any addition of an string offset in an `array<string, ...>` leads to it becoming an `array<array-key, ...>`, this code will start emits this error:
`MixedArgumentTypeCoercion - 9:23 - Argument 1 of expectStringArray expects array<string, string>, parent type non-empty-array<array-key, string> provided`

Because it can no longer warrants that you have an array with string offsets. This is correct from a type perspective, but this is very wrong from the user experience when using Psalm because in almost every case, we actually had a non-numeric-string here, and even if we had a numeric-string, if the user uses non-strict comparison operator or just use the offset for displaying something, it will be fine

**Comment by mathroc** [comment]
yes, that's an unfortunate PHP behavior :thinking: 

We got a bitten by this a couple of times already, I wonder how we could avoid that in the future...

I'm closing this then

**Comment by orklah** [comment]
Yeah, I'd like to fix that too but there isn't a good way to make sure to detect all potential bugs without ruining the usability...

You could create a Psalm plugin that does what you ask, but I'm not sure you'd like the final result on the rest of your code.
