### ISSUE TITLE
Argument 1 of strpos expects a non-literal value

### ISSUE THREAD

**Issue by dzentota** [vimeo/psalm#6925]
Pslam raises InvalidLiteralArgument Error when it should not:

```php
$test = 'foobar';
if (false !== strpos($test, 'foo')) {
   echo 'foo', PHP_EOL;
}
```

https://psalm.dev/r/b2d46a9be1

While this works:

https://psalm.dev/r/3a7744373e

**Comment by weirdan** [comment]
Do you have a more realistic example where you get that issue?

**Comment by dzentota** [comment]
No, I faced it when tried to reproduce another real issue from `psalm/phar` on psalm.dev

 RedundantCondition - src/MetaData/ViewdefManager.php:130:21 - int can never contain false (see https://psalm.dev/122)
```php
                if (strpos($path['path'], 'custom') !== false)
```
It seems fixed in the current repo but not in psalm/phar.

**Comment by dzentota** [comment]
Here is a more realistic example from the top of my head. Say you have a game where you need to guess the latest character (substring) in a secret word.

```php
<?php
$superSecret = 'supersecrettext';
if (isset($_GET['attempt'])) {
    $attempt = (string) $_GET['attempt'];
} else {
    die();
}

if (false !== ($pos = strpos($superSecret, $attempt))) {
    echo "your score is $pos", PHP_EOL;
}

```

**Comment by weirdan** [comment]
> It seems fixed in the current repo but not in psalm/phar.

`psalm/phar` is up to date with `vimeo/psalm:master` as far as I can see.

**Comment by orklah** [comment]
Your code is valid but it's not why this Issue was created.

If you follow the link on psalm.dev, the [documentation](https://psalm.dev/docs/running_psalm/issues/InvalidLiteralArgument/) says 
> Emitted when a literal argument is passed where a variable is expected, such as the first argument of strpos, where an explicit $haystack is almost always unintended.

Your case is the one that is not `almost always intended`. Feel free to suppress this issue for this piece of code or for your project if it doesn't suit your needs.

The explanation about why this: https://psalm.dev/r/3a7744373e is working, is because Psalm doesn't see the function always return a literal when it's processing the call. It just sees `string` in the return type. If you detail the return type a little, Psalm start emitting the issue again: https://psalm.dev/r/3bbec77a8f

Please create a new issue if you manage to reproduce the RedundantCondition. Beware, PHP versions can have an impact on certain types

**Comment by weirdan** [comment]
Also see the discussion in the original PR that provides rationale for this issue: https://github.com/vimeo/psalm/issues/4070
