### ISSUE TITLE
Multiple failure varieties when inferring return type from argument type

### ISSUE THREAD

**Issue by markrandall** [vimeo/psalm#6977]
When attempting to use template parameters of an argument type to define the return type of the function the logic gets confused and treats the value as a literal.

RedundantConditionGivenDocblockType  
https://psalm.dev/r/75667139f3

DocblockTypeContradiction  
https://psalm.dev/r/5846bf5243

DocblockTypeContradiction exhibiting taking value as literal type.
https://psalm.dev/r/63b5b6b254

**Comment by orklah** [comment]
Seems correct. If you say you have a template `T` that is received in param and returned as is, Psalm will return the value of the param. 

If you prefer, your annotations match with a function that would do: https://psalm.dev/r/d997e1ba56

Do you have a more representative example of what you're trying to do?

**Comment by orklah** [comment]
I'm closing this as answered, feel free to keep the discussion active here if you still need precisions

**Comment by markrandall** [comment]
The function in question is a single entrypoint to a backing array that returns a type based on the value of the default.

```
  $stringValue = ini('key1', 'foo');
  $intValue = ini('key2', 0);
  $boolValue = ini('key3', false);
```

An int default means an int return type, a string default means a string return type etc.

By using the templated T as the parameter type we expected that the type of that passed parameter would  be used in the return type, i.e. a default value of 0 would be either an integer, or 0. 

The observed behaviour and your comment indicate that rather than treating T as a PHP type, it's forming a single-value enum-like type based on the literal value similar to if 'a'|'b'|'c' was used instead of T.

A cascade of conditional types appears to work at initial look, checking if T is X ? X : (Y is Y ? Y : mixed)) and so forth.

With your comment I think I follow the reasoning, but it was unexpected.

**Comment by orklah** [comment]
Ok, I get what you're trying to do.

Unfortunately, there is a wrong assumption you made: Psalm's type system is not limited to PHP type system. Meaning, Psalm does not limit itself to `int`, `string`, `bool`, instead is has `5`, `int<4, 8>`, `positive-int`, `a`, `non-falsy-string` and many more.

That implies that when you create a template, Psalm will always takes the most precise type that matches all its inputs. For example, if you have a templates that matches two params that are `5` and `7`, Psalm will infer `5|7` as a resulting template (you'd have to push a lot of literals for Psalm to fallback to `positive-int` or `int` when applicable)

There is a solution though, but maybe not as elegant as you could have hoped:
https://psalm.dev/r/150568cb9b

This uses conditional types: https://psalm.dev/docs/annotating_code/type_syntax/conditional_types/ in order to describe the return types depending on the param type
