### ISSUE TITLE
First-class callable

### ISSUE THREAD

**Issue by userqq** [vimeo/psalm#6989]
Hi, I'm trying to get works psalm with php8.1 syntax, but getting error 
`Uncaught AssertionError: assert(!$this->isFirstClassCallable()) in /app/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/CallLike.php:36`
when trying to inspect following line 
```php
array_map($this->handle(...), $message->parameters['messages']->value);
```

When I trying to run the snippet https://psalm.dev/r/399d485cde , https://psalm.dev/check responds with 500 error:
```<br />
<b>Warning</b>:  Undefined property: PhpParser\Node\VariadicPlaceholder::$name in <b>/var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php</b> on line <b>118</b><br />
<br />
<b>Warning</b>:  Undefined property: PhpParser\Node\VariadicPlaceholder::$value in <b>/var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php</b> on line <b>177</b><br />
<br />
<b>Warning</b>:  Undefined property: PhpParser\Node\VariadicPlaceholder::$value in <b>/var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php</b> on line <b>178</b><br />
<br />
<b>Warning</b>:  Undefined property: PhpParser\Node\VariadicPlaceholder::$value in <b>/var/www/vhosts/psalm.dev/httpdocs/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentsAnalyzer.php</b> on line <b>200</b><br />
{"error":{"message":"\/vendor\/vimeo\/psalm\/src\/Psalm\/Internal\/Analyzer\/Statements\/ExpressionAnalyzer.php: Psalm\\Internal\\Analyzer\\Statements\\ExpressionAnalyzer::analyze(): Argument #2 ($stmt) must be of type PhpParser\\Node\\Expr, null given, called in \/vendor\/vimeo\/psalm\/src\/Psalm\/Internal\/Analyzer\/Statements\/Expression\/Call\/ArgumentsAnalyzer.php on line 200","line_from":35,"type":"psalm_error"}}
```

**Comment by weirdan** [comment]
Can you try parsing the source file with `vendor/bin/php-parse`? If that fails it needs to be reported upstream: https://github.com/nikic/PHP-Parser/issues

**Comment by orklah** [comment]
It's not a PHP-Parser issue, it's indirectly due to https://github.com/vimeo/psalm/pull/6628

in PHP-Parser 4.13, the argument list (for a `MethodCall` in this case) is not longer a list of `Args` due to PHP support for first class callable. It can now be a VariadicPlaceholder also.

In #6628, I replaced every use of MethodCall::args (and others) by MethodCall::getArgs() in order to fallback to a method that returns the same list of Args as before.

However, PHP-Parser does an assert on MethodCall::args in order to check that it's not a first class callable to be able to make sure it only return Args.

The effect of that is that Psalm doesn't have support for first class callable (it would have failed to parse in PHP-Parser 4.12 and now it fails on the assertion)

This makes this issue very related to https://github.com/vimeo/psalm/issues/6412, if not a duplicate

**Comment by FractalizeR** [comment]
Any news here? Stumbled over the same problem

**Comment by orklah** [comment]
Actually, this should have been closed by https://github.com/vimeo/psalm/pull/7113. @FractalizeR if you could make sure your use case work in latest master, it would help checking everything works. Please open a new issue if you encounter difficulties

**Comment by FractalizeR** [comment]
Latest master (pointing composer to dev-master branch) didn't work. The error is still:

```Psalm
psalm: Target PHP version: 8.1 (inferred from composer.json)
Scanning files...
Analyzing files...
Uncaught AssertionError: assert(!$this->isFirstClassCallable()) in <...>/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/CallLike.php:36
Stack trace:
#0 <...>/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/CallLike.php(36): assert(false, 'assert(!$this->...')
#1 <...>/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeCollector.php(358): PhpParser\Node\Expr\CallLike->getArgs()
```

**Comment by orklah** [comment]
@FractalizeR can you please open a new issue?

**Comment by userqq** [comment]
> @FractalizeR can you please open a new issue?

@orklah I did  - https://github.com/vimeo/psalm/issues/7196
