### ISSUE TITLE
Assertion inside loop does not work

### ISSUE THREAD

**Issue by gndk** [vimeo/psalm#7038]
Asserting that `mixed` is a `string` (or any other more specific type) does not work inside a loop:

With `if(! is_string)`: https://psalm.dev/r/07d2930bc7
With `assert(is_string())`: https://psalm.dev/r/1d30be66ac

But works as expected when moved outside the loop:

With `if(! is_string)`: https://psalm.dev/r/f0033ef351
With `assert(is_string())`: https://psalm.dev/r/616e96ada3

**Comment by orklah** [comment]
This has to do with the way Psalm record Issues while in loop.

When starting a loop, Psalm calls the method IssueBuffer::startRecording(). This increase by 1 the level of IssueBuffer::$recording_level and will record every issue in IssueBuffer::$recorded_issues instead of adding them to the list of prepared issues.
When leaving a loop, Psalm calls IssueBuffer::clearRecordingLevel()  to retrieve recorded issues and IssueBuffer::stopRecording() to decrement the recording level. It will then call IssueBuffer::bubbleUp() in order to try to emit issues again (if recording level is at 0, it will emit them, if not it will continue recording them).

The core of the issue is that, when Psalm encounters a is_string function, it will try removing any MixedAssignment issue that has been emitted, but given that the issue is not emitted but recorded, IssueBuffer::remove does nothing.

What would need to be done here is to improve IssueBuffer;;remove to allow it to remove recorded issues as well
