### ISSUE TITLE
query re: issue with max

### ISSUE THREAD

**Issue by anubhav217** [vimeo/psalm#7085]
This is possibly a little more complicated than I thought because max() accepts & processes a lot more than numerics o_O

I've got an issue whereby I'm treating max() as max(T, ...T): T, with what I would be hoping would be detected for T as int.

https://psalm.dev/r/a181337b14

<?php
$files = [
  __FILE__,
  __FILE__,
  __FILE__,
  __FILE__,
];

$a = array_map('filemtime', $files);
$b = array_map(
  function (string $file) : int {
    return filemtime($file);
  },
  $files
);

$A = max(filemtime(__FILE__), ...$a);
$B = max(filemtime(__FILE__), ...$b);

echo date('c', $A), "\n", date('c', $B);
Psalm output (using commit 5bb28cc):

INFO: MixedAssignment - 17:1 - Cannot assign $A to a mixed type

INFO: MixedAssignment - 18:1 - Cannot assign $B to a mixed type

INFO: MixedArgument - 20:16 - Argument 2 of date cannot be mixed, expecting int

INFO: MixedArgument - 20:37 - Argument 2 of date cannot be mixed, expecting int

**Comment by orklah** [comment]
Well, your snippet shows a big issue with the way we handle min and max: there is no unpacking support when there is more than one argument.

Everything is done in this class: https://github.com/vimeo/psalm/blob/e9d9481ea650b72a0b9b0ef39920b32e448749c4/src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php#L22

Here, we handle the case where there is only one argument:
https://github.com/vimeo/psalm/blob/e9d9481ea650b72a0b9b0ef39920b32e448749c4/src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php#L42

In this case, min and max will return the lowest/highest value from the array

Then we have a big loop to try to output the literal value or a range of acceptable values when only ints are present in arguments:
https://github.com/vimeo/psalm/blob/e9d9481ea650b72a0b9b0ef39920b32e448749c4/src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php#L54

And then, every other case is handled here: https://github.com/vimeo/psalm/blob/e9d9481ea650b72a0b9b0ef39920b32e448749c4/src/Psalm/Internal/Provider/ReturnTypeProvider/MinMaxReturnTypeProvider.php#L115

But we never check `$arg->unpack` in order to check if we should flatten an array due to destructuration, which means we actually output the horrible `array{int|false}|int|false` instead of just `int|false`

Are you up for a PR?

**Comment by AndrolGenhald** [comment]
This seems to be fixed now, probably along with #1820.
