### ISSUE TITLE
False positive when using static variables inside a function

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#7092]
I may be wrong, but I see no way that this variable could ever be mixed. It is defined as empty array and upon execution it is populated. 

https://psalm.dev/r/9fb94780c8

Psalm should infer the type to be always array.

**Comment by orklah** [comment]
This is really hard for Psalm because it's a recursive process. Consider this: https://psalm.dev/r/e1a7dba9bb. If we wanted to understand what's going on here, Psalm would have to
1) Init the value to 0
2) With the value to 1, consider the condition and see we put the count to 2
3) Repeat the process while knowing the count is 2 to know we can go up to 6

If we do that, we can realize that indeed, there is never a case where $count is 7, so we can never return 0, so indeed, the return is a positive-int 

This is a very simple case but analyzing this require to pseudo-execute the code (Psalm is forced to literally loop over every possible iteration).

Back to your case, you retrieve a static variable. All Psalm know is at some point, you initialized it to `[]`, so at this point, it has to consider it `mixed`. Then it goes to analyzing your code and see that in the case where it's an empty array, you initialize it to a specific array, so it process `mixed|array{...}` and simplify this to `mixed`.

This is a chicken and egg issue. Starting from the top of the function, Psalm can't know the variable cannot contain mixed without analyzing the function... that requires it to know the variable cannot contain mixed.

The solution is simple though. If you actually document the value of the variable, Psalm will be happy: https://psalm.dev/r/0c8f07242b. It will be able to see that when the array is empty, you fill it again so it can never be empty or mixed at the end
