### ISSUE TITLE
Manually typed arrays which reflect a list are not always detected as a list

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#7102]
Hey there,

I do have the following code example and I would assume that there is no error.
As I know that I usually tend to abuse types in a way how they should not be used, I'd like to get some feedback on this before probably working on it (not sure if this year but my plan is to fix those bugs I reported by myself until I got fixed all of them 👍🏼 ).

https://psalm.dev/r/3b4f763b1d

So any feedback welcome.

**Comment by orklah** [comment]
Yeah, that feels like a bug.

Given that the second line here is not an issue:
https://psalm.dev/r/14a74ac2a7

I'd guess the repetition cause a problem.

The type in itself is constructed in ArrayAnalyzer. It should create a nested TKeyedArray structure where the is_list property should be true for the first level.

Then, in MethodCallAnalyzer, Psalm will try to check if your TKeyedArray structure is allowed by the TList you declared for doSomething. It should allow it because of the is_list propertty and structure matching but it does not. It could be a bug in `UnionTypeComparator::isContainedBy`

**Comment by boesing** [comment]
This seems to be fixed in one of the v5 versions.
