### ISSUE TITLE
False positive InvalidReturnStatement/InvalidReturnType?

### ISSUE THREAD

**Issue by jdreesen** [vimeo/psalm#7112]
This snippet fails, while the resolved types are the same: https://psalm.dev/r/4aa5eda057

Did I do something wrong?

**Comment by orklah** [comment]
If you consider this example:
https://psalm.dev/r/386a2d172a

Here, I create an instance of C (I removed the abstract for the example).

I added a constructor in order to specify the type of the template. In this case, I created a `C<A>`

So, if I call foo() on my `C<A>`, documentation say I should retrieve a `A`. But the code of foo() doesn't guarantee that. It just says that it will get either a A or a B. That's not good enough.

You have to make sure foo() returns something related to T, because when T is A, you need to return a A, not a B.

**Comment by orklah** [comment]
So for example, something like this should work: https://psalm.dev/r/9a9026dddb. Psalm sees you provide something related to T to `type` and the method is documented to return a class-string of the same type of what you push. That way you're guaranteed to get a A when your T is a A.
