### ISSUE TITLE
UndefinedVariable "$__fake_offset_var__"

### ISSUE THREAD

**Issue by PurpleVsGreen** [vimeo/psalm#7164]
Thank you for making Psalm such an amazing analyzer.
I might have found a bug but I'm not sure.

https://psalm.dev/r/cccdb532d0
https://psalm.dev/r/c114e494ca

The error goes away when I use an anonymous function as the callable for the inner array_map.

**Comment by AndrolGenhald** [comment]
Best I can tell, this is due to the nested `array_map`. `$__fake_offset_var__` is removed from the context at `ArrayMapReturnTypeProvider.php:470`, and at some point it tries to use `$__fake_offset_var__` when only `$x` and `$x['$__fake_offset_var__]` are set (I don't really understand why `$x['$__fake_offset_var__]` is being set in the first place though).

Using a temporary variable is another workaround: https://psalm.dev/r/b582aba92e

**Comment by AndrolGenhald** [comment]
Ok, I'm convinced the `$x['$__fake_offset_var__]` isn't intended to be set and is polluting the context, it should probably be removed somehow.
