### ISSUE TITLE
Feature Request: Exclude files from being scanned when ignored by `.gitignore`

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#7166]
Hey there,

wondering if its possible to parse several `.gitignore` files found in the project to determine if certain errors can be ignored.
I think it might be fine to parse these files but if one of the `.gitignore` patterns are matching, probably its possible to suppress these errors.

Is this something which is somehow achievable or would this take too complex file scanning logic?

**Comment by AndrolGenhald** [comment]
If you want to try this yourself I would look into how ProjectFileFilter and FileFilter handle the IgnoreFiles config. If you do it though, I would add a config for it which is disabled by default, maybe changing it in Psalm 5 to be enabled by default.

**Comment by boesing** [comment]
Will give this a try when I find some spare-time

**Comment by orklah** [comment]
Can you give us more details about what you want? 
- Why do you want to use gitignore instead of your psalm config? 
- What would be the syntax in the file?

**Comment by AndrolGenhald** [comment]
@orklah I assume the motivation is that there's a config file or some other `.gitignore`'d file that's showing errors, but @boesing doesn't care about it because it's not committed anyway so it won't affect anyone else. Looking at this again, I think I'd prefer that not be the default even for Psalm 5, but it seems like a valid use-case, it would simplify things for people who want it to behave that way so they don't have to ignore the file in both git and Psalm.

A lot of other utilities have defaults like this as well, VS Code defaults to ignoring `.gitignore`'d files when searching for example. I think it makes more sense for projects where you'd have some sort of build directory, like for typescript or other compiled/transpiled languages, but I could see it being a useful feature for projects that use https://github.com/Ocramius/ProxyManager for example (I know Doctrine and Symfony do at least, but usually the generated files are in a directory I have ignored by Psalm anyway).

**Comment by orklah** [comment]
I'm okay with it not being the default (this would be very confusing for some users). Also we'll have to make sure the implementation doesn't check for gitignore files if the feature is not activated. Recursively scanning for gitignore files could take some time for some projects

**Comment by boesing** [comment]
The main reason is that I indeed got errors for a file which was excluded by gitignore *and* my psalm config but psalm stopped ignoring it somehow.
Probably have to see why that was the case but overall, I think this could be somehow useful as I do have to do specify directories twice, such as cache directories where php files are written to which contain code which is actually scanned or doctrine proxy or metadata files, etc.

**Comment by ohader** [comment]
Personally I'd consider ignoring files declared in `.gitignore` the job of a project-specific plugin - or a task that needs to be configured explicitly in a `psalm.xml` config file. I doubt Psalm core can offer a "one size fits all" solution for this use-case.

**Comment by boesing** [comment]
Yah, the need is not high enough as that I would spend time on it either.
Closing this for now - in case I experience that issue again, I might find a different solution instead. 
Thanks anyways.
