### ISSUE TITLE
`mb_internal_encoding()` always returns string when called without an argument

### ISSUE THREAD

**Issue by ThomasLandauer** [vimeo/psalm#7408]
`mb_internal_encoding()` returns `string|bool` in principle, but when called without an argument, it's always `string`: https://www.php.net/manual/en/function.mb-internal-encoding.php

Example:
https://psalm.dev/r/32218305f6

PHPStan does take this into account, and is not reporting anything.

**Comment by orklah** [comment]
This can be handled by adding a new stub for this function, kinda like for strlen: https://github.com/vimeo/psalm/blob/4.x/stubs/CoreGenericFunctions.phpstub#L742

With a conditional return, you'll be able to check that if the param is an empty-string, the return will be a string.

Could you check if the function ever return true as well?

**Comment by derrabus** [comment]
> Could you check if the function ever return true as well?

It does return `true` if you call it with a valid `$encoding` parameter. On PHP 8 though, it will never return `false` because calling the function with an invalid encoding will trigger a `ValueError`. Also, the behavior for `null` has changed in PHP 8.

The rules for the return type are:

| `$encoding` | PHP 7 | PHP 8 |
|---|---|---|
| omitted | string | string |
| valid encoding string | `true` | `true` |
| invalid encoding string | `false`+ `E_WARNING` triggered | `ValueError` is thrown |
| `null` | `false` + `E_WARNING` triggered | string |
| non-stringable parameter | `null` + `E_WARNING` triggered | `TypeError` is thrown |

**Comment by orklah** [comment]
Thanks @derrabus, looking at your chart, I thought better to create a return type provider instead of a stub with a big conditional return.

This will ship with Psalm 5 soon
