### ISSUE TITLE
`parent` doesn't account for `@method` annotations?

### ISSUE THREAD

**Issue by leighman** [vimeo/psalm#7411]
Maybe I'm being stupid but I would not expect `UndefinedMethod` here because of the `@method` annotation. The annotation seems to work when just calling the method.
https://psalm.dev/r/ccfc1a31f2

**Comment by orklah** [comment]
Seems like a bug indeed. @vincent4vx you worked on something very related. Would you mind looking at this?

**Comment by vincent4vx** [comment]
It looks like psalm considers parent::create as static call

**Comment by orklah** [comment]
yeah, I noticed something similar some time ago.

The syntax for an instance method returning static and a static method without return is the same...

We should probably forbid static method not having return type and assume a single "static" is a dynamic method.

Not sure how phpstan handles this

**Comment by vincent4vx** [comment]
PHPStan works as expected : https://phpstan.org/r/15872adb-5dd2-4436-a46a-e07cd5632d1f
The static keyword will be used as return type, like psalm.

Thue current issue is that `parent::xxx()` is analysed by `AtomicStaticCallAnalyzer`, so in case of magic method, it'll check for `__callstatic` method existence, and read the MethodStorage from `pseudo_static_methods`.

This issue do not occurs on instance methods, because static and instance methods are all stored into `methods` property of `ClassLikeStorage`.

**Comment by orklah** [comment]
Your diagnostic seems correct, I fixed the issue by adding handling for `pseudo_methods` when we detect a call with `parent::` but I have an issue with the static return type resolution. I'll push the PR when I find the issue. Thanks!
