### ISSUE TITLE
incorrect evaluation of non-null conditional return type

### ISSUE THREAD

**Issue by pilif** [vimeo/psalm#7413]
https://psalm.dev/r/78422eb8fe

what's interesting is that the `trace` on line 26 gets the type correct (constant `1234`), but on the function call to `g()`, it still complains about `$f` possibly being null, despite `trace` knowing it can't be.

**Comment by orklah** [comment]
Fixed your snippet:
https://psalm.dev/r/a8c1b13be5

Psalm removed the null on your trace because the trace displays the type AFTER the expression and once you've called a function that only accepts int (`g`), Psalm assume you have an int.

However, after `check` Psalm still think you can have an int. This is because assertions (the internal module Psalm uses to refine variable types) doesn't work this way (it doesn't try to compute the conditional return to check if the return of the function will be truthy or falsy).

However, there is a way to make Psalm understand that with docblock assertions: https://psalm.dev/r/c590d74ac9
