### ISSUE TITLE
Windows defender trojan warning

### ISSUE THREAD

**Issue by kamil-tekiela** [vimeo/psalm#7459]
Windows defender has detected a trojan warning. 
![image](https://user-images.githubusercontent.com/6583064/150639531-80ca5ed8-f680-4af8-b7b5-3bf3e9c667af.png)

Is this something that should be rectified by the project?

I assume this is a false positive, but could the test be changed in any way to not trigger it?

**Comment by orklah** [comment]
😄 that's literally forbidden code then!

Does it happen when you require psalm through composer for another project or when you checkout Psalm's repo itself?

I'm not sure what to do about it, basically, windows defender just perform static analysis on our own test to detect that shell_exec is performed.

That basically means that we'll be playing cat and mouse with Microsoft because we precisely want to test what they're trying to prevent

We could try make the code looks more tame and hope they don't catch that (for example replace `shell_exec("rm -rf");` by `shell_exec("");` to make windows less suspicious, Feel free to propose a PR among those lines

I'm probably not gonna loose too much sleep on that however. It can be ignored/deleted without big consequences

**Comment by weirdan** [comment]
Not going to act on this. This doesn't happen when Psalm is installed normally (either as phar or through `composer require` using default composer settings).
