### ISSUE TITLE
Intersection types with built-in classes does not work

### ISSUE THREAD

**Issue by davidbyoung** [vimeo/psalm#7520]
https://psalm.dev/r/07aeb2b8c9

**Comment by AndrolGenhald** [comment]
It shouldn't crash like that, but intersecting two classes doesn't make much sense anyway. Either we already know one class extends the other, or we know they can't possibly intersect. It seems to work correctly for interfaces: https://psalm.dev/r/1b136de642.

**Comment by davidbyoung** [comment]
My real use-case is intersecting an interface and `MockObject` in a unit test.  In this case, my interface was `SessionHandlerInterface`.  Here's a repro of that issue:  https://psalm.dev/r/f544acf7cc

**Comment by davidbyoung** [comment]
(it still breaks if you make `Foo` an interface in my above example)

**Comment by davidbyoung** [comment]
The order of the type seems to matter.  For example, [this works](https://psalm.dev/r/09f17deb82), but [this does not](https://psalm.dev/r/e9af3116a7).

**Comment by orklah** [comment]
ouch, this breaks badly. I'll look into it.

I'm not sure what will happen by intersecting a mock object and an interface though... Either the mock object already implement the interface and it should already work or it doesn't and it's weird

**Comment by AndrolGenhald** [comment]
> Either the mock object already implement the interface and it should already work or it doesn't and it's weird

Intersecting objects and interfaces in makes sense when the class is non-final, since children can implement interfaces.

**Comment by davidbyoung** [comment]
Fwiw [PHPUnit returns an intersection type](https://github.com/sebastianbergmann/phpunit/blob/b32796b9c4c19bdd7b8080bc36bbf3182c7cb3f6/src/Framework/TestCase.php#L1322) when creating a mock

**Comment by orklah** [comment]
Thanks for feedback :)

So far, I found out that the issue happens because of Psalm didn't manage to scan SessionHandlerInterface before it tries to create the intersectionType (for that, Psalm needs to know the class storage). 

I'm still digging

**Comment by AndrolGenhald** [comment]
@orklah Given that [docblock types](https://psalm.dev/r/39c247533a) work I'd take a look at the PR that added support for intersection signature types, maybe there's something happening during scanning that needs to happen during analysis?

**Comment by orklah** [comment]
That's highly possible, but I'm confused by the fact it works when you flip the intersection around. If I solve the mystery here and the answer is not right, I'll try to fix it further

**Comment by AndrolGenhald** [comment]
Probably related: #8387, I think we need to move some of the intersection stuff to the analysis phase instead of the scanning phase, but I'm not sure how much work that'll be.

**Comment by Forestsoft-de** [comment]
Hey here is another example. Its not possible to scan a symfony project right now.

`Deep scanning /var/www/html/vendor/symfony/http-foundation/Session/Storage/Handler/MigratingSessionHandler.php
Uncaught InvalidArgumentException: Could not get class storage for sessionhandlerinterface in /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Provider/ClassLikeStorageProvider.php:48
Stack trace:
#0 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(740): Psalm\Internal\Provider\ClassLikeStorageProvider->get('sessionhandleri...')
#1 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/ClassLikes.php(730): Psalm\Internal\Codebase\ClassLikes->getParentInterfaces('sessionhandleri...')
#2 /var/www/html/vendor/vimeo/psalm/src/Psalm/Codebase.php(756): Psalm\Internal\Codebase\ClassLikes->interfaceExtends('sessionhandleri...', 'sessionupdateti...')
#3 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/ObjectComparator.php(307): Psalm\Codebase->interfaceExtends('sessionhandleri...', 'sessionupdateti...')
#4 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/ObjectComparator.php(68): Psalm\Internal\Type\Comparator\ObjectComparator::isIntersectionShallowlyContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), 'sessionupdateti...', false, false, NULL)
#5 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php(309): Psalm\Internal\Type\Comparator\ObjectComparator::isShallowlyContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), false, NULL)
#6 /var/www/html/vendor/vimeo/psalm/src/Psalm/Type.php(825): Psalm\Internal\Type\Comparator\AtomicTypeComparator::isContainedBy(Object(Psalm\Codebase), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject))
#7 /var/www/html/vendor/vimeo/psalm/src/Psalm/Type.php(706): Psalm\Type::intersectAtomicTypes(Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Type\Atomic\TNamedObject), Object(Psalm\Codebase), false)
#8 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/TypeHintResolver.php(113): Psalm\Type::intersectUnionTypes(Object(Psalm\Type\Union), Object(Psalm\Type\Union), Object(Psalm\Codebase))
#9 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php(1544): Psalm\Internal\PhpVisitor\Reflector\TypeHintResolver::resolve(Object(PhpParser\Node\IntersectionType), Object(Psalm\CodeLocation), Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), Object(Psalm\Storage\ClassLikeStorage), Object(Psalm\Aliases), 80210)
#10 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/Reflector/ClassLikeNodeScanner.php(724): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->visitPropertyDeclaration(Object(PhpParser\Node\Stmt\Property), Object(Psalm\Config), Object(Psalm\Storage\ClassLikeStorage), 'Symfony\\Compone...')
#11 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/PhpVisitor/ReflectorVisitor.php(186): Psalm\Internal\PhpVisitor\Reflector\ClassLikeNodeScanner->start(Object(PhpParser\Node\Stmt\Class_))
#12 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): Psalm\Internal\PhpVisitor\ReflectorVisitor->enterNode(Object(PhpParser\Node\Stmt\Class_))
#13 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#14 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#15 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#16 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Scanner/FileScanner.php(88): PhpParser\NodeTraverser->traverse(Array)
#17 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(578): Psalm\Internal\Scanner\FileScanner->scan(Object(Psalm\Codebase), Object(Psalm\Storage\FileStorage), false, Object(Psalm\Progress\DebugProgress))
#18 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(807): Psalm\Internal\Codebase\Scanner->scanFile('/var/www/html/v...', Array, true)
#19 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(452): Psalm\Internal\Codebase\Scanner->scanAPath(1132, '/var/www/html/v...')
#20 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Codebase/Scanner.php(305): Psalm\Internal\Codebase\Scanner->scanFilePaths(1)
#21 /var/www/html/vendor/vimeo/psalm/src/Psalm/Codebase.php(503): Psalm\Internal\Codebase\Scanner->scanFiles(Object(Psalm\Internal\Codebase\ClassLikes), 1)
#22 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/ProjectAnalyzer.php(1217): Psalm\Codebase->scanFiles(1)
#23 /var/www/html/vendor/vimeo/psalm/src/Psalm/Internal/Cli/Psalm.php(382): Psalm\Internal\Analyzer\ProjectAnalyzer->checkPaths(Array)
#24 /var/www/html/vendor/vimeo/psalm/psalm(9): Psalm\Internal\Cli\Psalm::run(Array)
#25 {main}
(Psalm 5.1.0@4defa177c89397c5e14737a80fe4896584130674 crashed due to an uncaught Throwable)
`

**Comment by Ultra-Code** [comment]
I just stumbled upon this problem myself. It would be great if the psalm team fixes this.
