### ISSUE TITLE
Incorrect type checking (0|positive-int)

### ISSUE THREAD

**Issue by sergkash7** [vimeo/psalm#7555]
https://psalm.dev/r/0b7a15278a

**Comment by AndrolGenhald** [comment]
Looks like the underlying problem is that `$i` isn't narrowed to `int<1, max>` inside the loop. [This](https://psalm.dev/r/255ae9814f) works fine.

**Comment by orklah** [comment]
This is because of this line: https://github.com/vimeo/psalm/blob/4a85fed1816ca59ba9892a1f163b9839afabede2/src/Psalm/Internal/Type/SimpleAssertionReconciler.php#L1650

Range operations inside loops are merely supported because some backbone work has to be done in Psalm before this can work.

I tried to explain the reasons here: https://github.com/vimeo/psalm/pull/6474
