### ISSUE TITLE
False positive for `RedundantPropertyInitializationCheck`

### ISSUE THREAD

**Issue by ADmad** [vimeo/psalm#7592]
I don't think the `RedundantPropertyInitializationCheck` error should be shown for this code:

https://psalm.dev/r/220b68f789

phpstan correctly doesn't show any error for it https://phpstan.org/r/016e0982-ef49-492b-944d-60faed480d4f

**Comment by orklah** [comment]
Psalm and PHPStan made different choices on that matter.

Based on your example, this is a horrible bug for which PHPStan is completely fine: https://phpstan.org/r/e6f0360d-2f60-4099-90f3-66d5f34489c5

What Psalm does is forcing you to initialize every property in the constructor. That's why you get a `MissingConstructor` and why you'd get a `PropertyNotSetInConstructor` if you did have a constructor but didn't initialize your property.

As a tradeoff, Psalm can know assume every property you have is initialized and will in turn tell you that it's pointless to check if they are.

So if you have a project that relies on having uninitialized properties, you should not only suppress `MissingConstructor` and `PropertyNotSetInConstructor` but also `RedundantPropertyInitializationCheck` and you'll be left with manual checking for property initialization (like PHPStan does)

**Comment by orklah** [comment]
Opened https://github.com/vimeo/psalm/pull/7593 to improve documentation for these issues

**Comment by ADmad** [comment]
> Based on your example, this is a horrible bug for which PHPStan is completely fine: https://phpstan.org/r/e6f0360d-2f60-4099-90f3-66d5f34489c5

Yes, for this one would expect an error but my code has an `isset()` check.

> What Psalm does is forcing you to initialize every property in the constructor. That's why you get a MissingConstructor and why you'd get a PropertyNotSetInConstructor if you did have a constructor but didn't initialize your property.

I am fine with the `MissingConstructor` (and `PropertyNotSetInConstructor`) but `RedundantPropertyInitializationCheck` is incorrect IMO, since the property has not been initialized. The fact that it's not initialized through the constructor is why the `isset()` check is done. PHP (8+) is totally fine with typed properties being initialized outside of the constructor and there's no code path where the provided example would generate an error.

**Comment by ADmad** [comment]
BTW when you have code like `if (!isset($this->o) || ...) {` the error changes for `RedundantPropertyInitializationCheck` to `TypeDoesNotContainType. I would expect at least the error type to stay consistent for easy suppression.

**Comment by orklah** [comment]
> I would expect at least the error type to stay consistent for easy suppression.

This is probably a bug. Can you open an issue with a reproducer?

**Comment by ADmad** [comment]
https://psalm.dev/r/864c8178c5

**Comment by AndrolGenhald** [comment]
I think the easiest solution here is to just [default-initialize to null](https://psalm.dev/r/eb8ff4f282)... Then there's no risk of child classes accidentally accessing it before it's initialized, and the child classes will warn when using it that it's nullable so you get a nice hint that you should be using `getter()` instead of direct access.
