### ISSUE TITLE
Must annotate var to trigger further checks

### ISSUE THREAD

**Issue by andraaspar** [vimeo/psalm#7627]
Please see the sample code: https://psalm.dev/r/afe3908815

### Actual:
When the following line is removed:
```
 /** @var false|list<string> $objects */
```
All errors go away.

### Expected: 
PossiblyFalseIterator, MixedAssignment, MixedOperand errors even when $objects is not annotated.

**Comment by AndrolGenhald** [comment]
[This](https://psalm.dev/r/22dda22565) also works. Are falsable returns somehow being ignored when they come from the callmap maybe?

**Comment by orklah** [comment]
Oh, that's a fun one :)

Union have a property `$ignore_falsable_issues` which is used with https://psalm.dev/docs/running_psalm/configuration/#ignoreinternalfunctionfalsereturn and the `@psalm-ignore-falsable-return` annotation.

When this property is set to true (with previous config or annotation), Psalm won't emit issues related to the `false` being in there.

This is mainly here to allow users to avoid endless false/null checks on internal functions that rarely return those values.

However, when overwriting the union with an `@var` annotation, Psalm does not have this property set to true and will emit issues because you can't loop over false.

We could possibly not emit a `[UnnecessaryVarAnnotation](https://psalm.dev/212)` when there's a difference in those properties, but I think the behaviour would become less clear, as those properties are largely out of reach from users.

I'll close this because it can be considered normal behaviour. If you want to get those errors back, you should be able to toggle the config

**Comment by AndrolGenhald** [comment]
Ah, I knew there was a config there I just assumed it applied to _all_ falsable returns, not just internal falsable returns from the callmap. That explains it. It would be nice to allow more configuration on psalm.dev so that can be demonstrated there.

Would it be a good idea to change the default for that config in Psalm 5? I think it would at least be nice to provide some way to init a new project with the most strict config possible, rather than using default configs like this that are lenient.

**Comment by orklah** [comment]
I'd be up for having a strict mode in `--init` that enable every strict config, but I think having it as a default would only scare new users away

**Comment by andraaspar** [comment]
Thank you for the clarification.

This page: https://psalm.dev/docs/running_psalm/configuration/ is rather hard to digest as a newcomer. Maybe the docs could use some structuring on that page. I felt like I was reading a dictionary.

I was looking for a "strict" option á la TypeScript. First I thought it would be the "totallyTyped" option, but sadly that is deprecated.
