### ISSUE TITLE
Problem with template constraint and class

### ISSUE THREAD

**Issue by nthnptt** [vimeo/psalm#7634]
Hello,

I tried to use the template constraint in a class but I get an error of type `InvalidArgument`. I reproduce my problem on  [psalm.dev](https://psalm.dev/r/fd7f1290dd).

Psalm say `ERROR: [InvalidArgument](https://psalm.dev/004) - 29:29 - Argument 1 of Foo::build expects T:Foo as Entity, Entity provided`.  I don't understand why because I constraint my template `T` to be of type `Entity`.

Could you help me to understand what is going wrong ?

**Comment by orklah** [comment]
A `@template T as Entity` only restricts the upper bound of the type you can put in the template. You're not saying that the type couldn't be `Foo<EntityA>` or `Foo<EntityB>`.

Which means you can't just return "A random instance of Entity" because otherwise, you could have a `Foo<EntityA>` that returns `EntityB` when `test` is called.

Effectively, it means that what you return must be somehow related to `T`

This is what the error means: "I expected T but you gave me a random Entity"

So in your case, T must come either from a parameter in the method (exactly like you did in build()) or from a property that has been assigned to T before (probably from a parameter of the __construct())

**Comment by AndrolGenhald** [comment]
> So in your case, T must come either from a parameter in the method (exactly like you did in build()) or from a property that has been assigned to T before (probably from a parameter of the __construct())

Or from constructing a `class-string<T>` in a similar fashion.
