### ISSUE TITLE
Property type is not inferred when a class has a property docblock

### ISSUE THREAD

**Issue by mr-feek** [vimeo/psalm#7676]
https://psalm.dev/r/83b6098866

If a property does not have a native type declared, I'd expect psalm to look at the class `@property` phpdoc annotations to check if a type is declared there.

**Comment by orklah** [comment]
Why would you document it here?

This seems better on all fronts: https://psalm.dev/r/87bce25608

**Comment by mr-feek** [comment]
@orklah basically millions of lines legacy code. If there's no need for this in legacy code, i can write a plugin!

**Comment by orklah** [comment]
I think it would be better, yeah. @property is commonly admitted as documenting magic properties. PHPStan also works like that.

Promoted properties were a pain to implement properly because you have to check compatibility between the three possible types (signature, docblock for param, docblock for property), this will be pretty similar and I'm not too hyped for it :p

**Comment by mr-feek** [comment]
Roger that! Thanks for the quick feedback.
