### ISSUE TITLE
Checking with class_exists does not influence the UndefinedClass inspection

### ISSUE THREAD

**Issue by MetalArend** [vimeo/psalm#7725]
When the code first checks if a certain class exists, Psalm does not recognize the following path to be able to use that existing class.

Example of code: https://psalm.dev/r/618d930c83

Method exists1 uses an indirect use of the check, method exists2 uses it directly.

**Comment by AndrolGenhald** [comment]
What's your actual use-case here? You can do something like [this](https://psalm.dev/r/6e6ac9e105).

**Comment by orklah** [comment]
Psalm really doesn't like not knowing every class in your application. You should make sure every class is declared and can be autoloaded in order for Psalm to work correctly. You can see that Psalm doesn't only complain on the instantiation, it also complains on the return type and it will also complain on every call to one of those method that uses an undefined class.

Now to the heart of the issue: while Psalm doesn't like it, it still tolerate working with undefined classes in some regards. For example, if you checked that the class indeed exists beforehand, Psalm won't trigger this particular flavor of UndefinedClass. However, putting the check in another method makes everything complex. For example, what about https://psalm.dev/r/60f3ef4d43 ?
The class is not checked anymore for this particular child. Psalm won't (and can't) visit pathways between methods like that. It can usually only infer things that are documented on the method (usually in the form of types in param signature or return type, but also docblocks with type information, but also [assertions](https://psalm.dev/docs/annotating_code/assertion_syntax/)).

Assertions are the feature that looks the more like what you'd need. Except instead of asserting that a certain param is a string for example, you want to make Psalm aware you `Test` is a valid class-string that will create a `Test` instance. This is not currently possible, and while it would probably be feasible, it would add complexity on a very niche problem, because as I've said, you should not work with undeclared classes, Psalm will sometimes stop analyzing a method when it sees that such issues.

What AndrolGenhald showed you is an assertion that will override the type of your variable from `string` to `class-string`. While this will make Psalm stop screaming, it will still bugs you because it has now no idea what object will be created that way.

If you really must have undefined classes, I suggest you suppress this issue

**Comment by MetalArend** [comment]
Oh, wauw, certainly a very fast response, thanks a lot :) But I'm not sure why we would already close this...

For some more examples:
- I could change it from a string to a class-string like this, but it still gives me the exact same result: https://psalm.dev/r/84b6f6b902
- If I don't make it more generic, but reproduce a very simple use case I currently have with an optional php-extension class: https://psalm.dev/r/0f889acceb
- If I slightly change the example from AndroIGenhald, by not using the string, but using the actual class name, I get the same error: https://psalm.dev/r/b09b0f2886

What I understand from your response, orklah, is that Psalm is basically useless for almost every possible use of the php function `class_exists`, although it essentially does the exact same thing as an assertion? I would argue that whenever one encounters `class_exists` in the path, the string or class-string that is being checked in it should represent a class-string that does exist going forward in the happy path, and it should represent a class-string that is proven to not exist in the other path - which is basically what an assertion would do? Or is the problem that Psalm can only keep track on a certain variable (for some awesome array key tracking all over the application), but not on class-strings being mentioned as being some more global strings?

I could somehow see that checking for an optional php-extension class (my current use case) or an optional bundle class being loaded is somehow a niche situation, but it's not something completely strange. So is there a know solution to gracefully let Psalm know that I know that the class will actually exist in that specific path, even if Psalm will probably never know it? Or at least some cleaner way than somehow adding `psalm-suppress UndefinedClass` on that whole method?

**Comment by AndrolGenhald** [comment]
> I would argue that whenever one encounters `class_exists` in the path, the string or class-string that is being checked in it should represent a class-string that does exist going forward in the happy path, and it should represent a class-string that is proven to not exist in the other path

Psalm [already does that](https://psalm.dev/r/32d2b2d6ae) (except the negation part, negated types aren't possible yet). What Psalm doesn't do (and never will do) is automatically create assertions based on what happens in a function. Implementing it would be hard enough, but even if someone implemented a PR it would be rejected. The function signature and docblock are a contract that its callers rely on, if we start automatically adding stuff to that contract based on the function implementation then suddenly changing the function implementation can be a BC break.

> checking for an optional php-extension class

I would recommend using `extension_loaded` for that. 

> So is there a know solution to gracefully let Psalm know that I know that the class will actually exist in that specific path

Not without having a `class-string` variable. I hope to eventually provide awesome scope-specific stub support for extensions based on `extension_loaded` checks, but that's a long way off. For now the best thing is to add stubs for the extension and make sure you're careful not to use it outside the `extension_loaded` checks, Psalm can't help you with that yet.

If you'd like, we could add the extension stub to Psalm itself. I've been working on improving extension support in Psalm recently, you can look at the (unmerged) docmuentation [here](https://github.com/vimeo/psalm/pull/7577/files#diff-a8f5996f44efa5bcb7120605c7af05f11887a00b3743ee7a0e886afcab1584a1).
