### ISSUE TITLE
RedundantCast error missing in ternary

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#7745]
https://psalm.dev/r/467a8d3175

should be RedundantCast in line 5 and 9 too

**Comment by AndrolGenhald** [comment]
Casting has much higher [precedence](https://www.php.net/manual/en/language.operators.precedence.php) than the conditional operator, what you're doing here is [this](https://psalm.dev/r/2234040ea8) which considered not redundant in the same way that [this](https://psalm.dev/r/ba30048d82) isn't. [This](https://psalm.dev/r/5ba306e059) works as expected.

I'm not opposed to trying to fix this since it actually _is_ redundant (just not in the way you thought), but I think it's probably harder than it looks and I'm not sure it's worth the trouble.

**Comment by kkmuffme** [comment]
Ok thanks, I'll just close it bc it's not worth it then.
