### ISSUE TITLE
Stricter typing of callable-array

### ISSUE THREAD

**Issue by ssnepenthe** [vimeo/psalm#7778]
It seems like psalm is understanding a callable array as the equivalent of `array<array-key, mixed>` instead of `array{0: class-string|object, 1: string}`.

https://psalm.dev/r/95bfee547d

https://psalm.dev/r/0bdc7fda82

Is it possible to help psalm understand callable arrays a little better? Or am I missing something obvious/making an incorrect assumption about what makes a valid callable array?

**Comment by orklah** [comment]
Oh, that's weird.

Psalm has currently two internal types: `TCallableArray` and `TCallableList`. TCallableArray can be annoted with `callable-array` and is the type you used in your example.

TCallableList can't be created by users directly, it has to be inferred (by having an intersection between a list and a callable in your code)

I tend to agree that all callable-array to be valid must:
- have only two elements
- have numeric keys
- start at 0 (with the class)
- have an offset 1 (with the method)

So this matches the definition of a list.

Which means all callable-array are callable-list.

So what would need to be done is to remove TCallableArray and just substitute with TCallableList everywhere. Doing that is a massive BC break, fortunately we're in the process of releasing Psalm 5 so it can still be done.

Are you up for the challenge? :)

**Comment by AndrolGenhald** [comment]
I noticed this when rewriting the type system in #7179 but I haven't gotten around to fixing it yet. There's also a `TCallableKeyedArray` which seems like the better option to keep and remove `TCallableArray` and `TCallableList`. That way `TCallableKeyedArray` can always mark `$sealed = true` guaranteeing there are exactly two keys. The more difficult part is fixing it so that adding an element to the array changes it to `TKeyedArray` as it's no longer callable.

**Comment by weirdan** [comment]
Fixed in #9794
