### ISSUE TITLE
Check if constant from a base class/interface is referenced via a child class

### ISSUE THREAD

**Issue by LordSimal** [vimeo/psalm#7781]
PHPStorm has internal code inspections which informed me about the following "problem":

![image](https://user-images.githubusercontent.com/9105243/158072452-17d1ce56-b0b0-4728-bfc7-599b9748a1b4.png)

In this case the used constant CODE_SUCCESS was refrenced via the Command class.

But the constant is not defined in the Command class but rather in the CommandInterface.

See https://psalm.dev/r/50344e7d60

**Comment by AndrolGenhald** [comment]
I'm not sure, this seems a bit unnecessary to me. [This](https://3v4l.org/iTMAV) is totally valid and has no warnings or anything. Does PHPStorm explain why they think it's bad?

It seems like this could also be [intentional](https://psalm.dev/r/797c4de619), and how would we tell if it's intentional or if it should be changed?

**Comment by LordSimal** [comment]
Well there is no additional info from PHPStorm directly in the editor popup.

Also the online help page doesn't really explain why it does that.
https://www.jetbrains.com/help/phpstorm/php-class-constant-referenced-via-child-class.html

I guess its more about the fact, that the Child/Base class doesn't overwrite the interface defined constant.

Therefore there shouldn't be code present which references that constant via different classes to make it more consistent.

Otherwise (in my example above) these 3 calls return all the same
```
echo CommandInterface::CODE_SUCCESS . PHP_EOL;
echo BaseCommand::CODE_SUCCESS . PHP_EOL;
echo Command::CODE_SUCCESS . PHP_EOL;
```

**Comment by orklah** [comment]
PHPStorm's inspections are great, but they're covering a lot of domains (and the goal of each inspection is not always very clear):
- performance optimization
- code style
- security issues
- finding bugs through static analysis
- redundant constructions
and still a lot more I can't come up with right now

Psalm is focusing on the 4th item on this list and I believe the issue reported in this topic belong more to the code style domain than anything else, so this is kind of out of scope for Psalm

As long as there is no risk of functional issue, Psalm won't complain :)

(As a matter of personal preference, I do like this inspection!)

**Comment by AndrolGenhald** [comment]
I still don't see a way to tell if this is intentional or not, which makes it seem too dangerous to me. Say you've got a sequence of changes like this:

1. [Initial code](https://psalm.dev/r/127666939c)
2. ["Fix" the "problem"](https://psalm.dev/r/9fca13868c)
3. [A change is made and the previous "fix" is now a bug](https://psalm.dev/r/8ceb192379)

Given that referring to a parent constant using the child class is perfectly valid, and making it a warning could introduce bugs, I don't see that this change would be worth it.

**Comment by AndrolGenhald** [comment]
@orklah Maybe this could be acceptable for [final constants](https://3v4l.org/dGl9C)? I still don't really care for it myself, but with final constants at least there's a guarantee that children will never be able to redeclare it.
