### ISSUE TITLE
InvalidArgument in case of more specific argument in child class constructor

### ISSUE THREAD

**Issue by orklah** [vimeo/psalm#7821]
### Discussed in https://github.com/vimeo/psalm/discussions/7816

<div type='discussions-op-text'>

<sup>Originally posted by **andrew-demb** March 25, 2022</sup>
https://psalm.dev/r/a6deb3aca7

Expected: no issue

Actual: `ERROR: [InvalidArgument](https://psalm.dev/004) - 12:28 - Argument 1 of AbstractConfirmCommand::__construct expects RequestSenderInterface<Iterator>, ConfirmRequestSender provided`

Why psalm is considered this case as an error?
The more specific type is specified in the child constructor just to simplify DI configs (by using autowiring).</div>

**Comment by AndrolGenhald** [comment]
Isn't this another invariance issue? Making the template covariant works fine: https://psalm.dev/r/cc94a91509.

**Comment by orklah** [comment]
Oh, that may very well be, I didn't expect that error for an invariance issue. @andrew-demb does that solve your issue?

**Comment by andrew-demb** [comment]
It solves an issue, thank you.
But it is not clear to me, why there are required a covariance annotation at all.

**Comment by AndrolGenhald** [comment]
It might be a bit unclear since in this case it doesn't seem like there are any mutating methods that could cause an issue, but it's meant to prevent cases like [this](https://psalm.dev/r/06471c3311) which will [crash](https://3v4l.org/4WOPL). Unless a template is created with `@template-covariant` the type is treated as invariant, and a function taking `MyClass<ParentClass>` cannot be passed a `MyClass<ChildClass>`.

**Comment by andrew-demb** [comment]
Yes, I have a basic knowledge about covariance.
But for current case I can't understand, why is this check applicable too.

Child class just narrows possible type for constructor argument. How it can to lead to problems at typing level (with covariance)?

**Comment by AndrolGenhald** [comment]
In this case it might actually be fine because `RequestSenderInterface` doesn't contain any mutating methods, but in general it's a problem because you could do something like [this](https://psalm.dev/r/a071161af4) which will [crash](https://3v4l.org/iA2L0). This is why templates are invariant by default unless specifically marked as covariant.

**Comment by andrew-demb** [comment]
Thank you.
