### ISSUE TITLE
Invalid inferred return type of `DateTimeImmutable::getTimestamp`

### ISSUE THREAD

**Issue by p4veI** [vimeo/psalm#7855]
Hello I've come across an issue while constructing an array with timestamps used as keys, psalm is reporting `false|int` can't be used as array key while `getTimestamp` always returns an `int`.

e.g. https://psalm.dev/r/c45a9a0a0f

**Comment by AndrolGenhald** [comment]
According to the [docs](https://www.php.net/manual/en/datetime.gettimestamp.php) this is a PHP 8 update to throw `ValueError` instead of returning false. This needs to be fixed for PHP >= 8.0, but it still needs to show the issue for PHP < 8.0.

Might as well fix the other methods on `DateTimeImmutable` and `DateTime` at the same time.

**Comment by p4veI** [comment]
ah, yeah that explains it, I'm on php 8.1, only looked into IDE docs (for php8.1 stubs docs). Thanks for clearing this up and thanks for looking into it :)

**Comment by orklah** [comment]
this was fixed :)
