### ISSUE TITLE
Variadic parameter interpreted as an array instead of non-empty-list

### ISSUE THREAD

**Issue by brzuchal** [vimeo/psalm#7856]
When a variadic parameter with type is given, then Psalm resolves that as an array-like `array<array-key, T>`.
In fact, there is no possibility to pass an array where keys are not ordered ints starting from 0 so `array-key` is broader.
Also, there is no way to skip a passing argument if there is no default value which also means it's also `non-empty-`

Example https://psalm.dev/r/69c5900156

**Comment by AndrolGenhald** [comment]
> In fact, there is no possibility to pass an array where keys are not ordered ints starting from 0

In fact, [there is](https://3v4l.org/hQsvv). Use [`@no-named-arguments`](https://psalm.dev/r/2b84ebd770) (although your example is still broken due to the non-empty requirement).

**Comment by brzuchal** [comment]
@AndrolGenhald you're right, thanks.

**Comment by AndrolGenhald** [comment]
I actually missed the non-empty due to no default value part earlier, but it looks like [that's correct too](https://3v4l.org/Tl5us). I recommend [this](https://psalm.dev/r/5f3b47d122) (this example actually works without `@no-named-arguments`, but that's a [false negative](https://3v4l.org/THLkS) tracked at #7297).
