### ISSUE TITLE
Supports var incremented with $var++ generate UnusedVariable

### ISSUE THREAD

**Issue by BruceGitHub** [vimeo/psalm#7858]
It's a Bug?
https://psalm.dev/r/e5b26bb7a3

Because the scalar is returned with return keyword is not allowed this
```php
$this->getNum()++;
```
this gets runtime error:
>Fatal error: Can't use the method return value in write context i
https://3v4l.org/NiGMh

In PHPStan this works
https://phpstan.org/try

**Comment by orklah** [comment]
Because you used post increment, your Psalm snippet is equivalent to:
https://psalm.dev/r/1cd83c4b89

Example:
original code: https://3v4l.org/hP7mZ
change code:
https://3v4l.org/KncOa

The error message is not very clear though... What's unused is the result of the increment, not the variable itself

**Comment by AndrolGenhald** [comment]
> your Psalm snippet is equivalent to:

More like [this](https://psalm.dev/r/c540f41852)? But yes, I've always preferred using pre-increment where possible.

As far as the error message, I'm not sure how it could be improved without making it very brittle. It already highlights only `$num` rather than `$num++`, so there's at least a hint that it's complaining about the variable and not the expression.

**Comment by orklah** [comment]
The snippet you posted does not show a loop. Can you post it again please?

**Comment by BruceGitHub** [comment]
I fixed the comment

**Comment by BruceGitHub** [comment]
> > https://psalm.dev/r/e95043ac09
> 
> That post-increment is also superfluous. `$num` is reassigned at the beginning of each iteration, so the incremented value assigned to `$num` is never used. Psalm is correctly pointing this out. Do you understand how post-increment works?

Yes, but the problem is resolved for me.

**Comment by shandyDev** [comment]
@AndrolGenhald  How about this?
https://psalm.dev/r/625a01ef43
Also it can be converted to infinity loop with $count increment in while condition.
As for me it is false-positive UnusedVariable error.

**Comment by shandyDev** [comment]
Look on inverted loop (when break as part of true conditional):
https://psalm.dev/r/b5f9754743
Should be there psalm error?

**Comment by AndrolGenhald** [comment]
That one does look like a bug! You can open a new issue if you want, but I'm not sure how quickly it'll be fixed, loops are complicated as well 😕

Interestingly [this](https://psalm.dev/r/3e2ee53620) works as expected, but if you [shift the assignments into the `if`](https://psalm.dev/r/11d69db6df) it fails as with the postincrement.
