### ISSUE TITLE
Assuming all typed properties are initiated in ctor is wrong

### ISSUE THREAD

**Issue by brzuchal** [vimeo/psalm#7865]
This example https://psalm.dev/r/1043e4126c is a valid code https://3v4l.org/OjRWX and the use of `isset` is considered safe to work with uninitialized properties.
I believe the [RedundantPropertyInitializationCheck](https://psalm.dev/261) should not be prompted here.

**Comment by AndrolGenhald** [comment]
This is a design choice explained [here](https://github.com/vimeo/psalm/issues/7608#issuecomment-1033056442) and elsewhere (including [both](https://psalm.dev/docs/running_psalm/issues/RedundantPropertyInitializationCheck/) of the [issues](https://psalm.dev/docs/running_psalm/issues/MissingConstructor/) shown for your code). This is one of several patterns that Psalm doesn't support in order to allow for better static analysis. If you want to use this pattern I would recommend adding an [issue handler](https://psalm.dev/docs/running_psalm/dealing_with_code_issues/#config-suppression) to ignore these issues, but Psalm may of course miss issues with your code.
