### ISSUE TITLE
HttpRequest::getMethod() expected to return int

### ISSUE THREAD

**Issue by sanmai** [vimeo/psalm#7915]
```php
class HttpRequest
{
    public ?string $method = null;
    
    public function getMethod(): ?string
    {
       return $this->method;     
    }
}

$r = new HttpRequest();

if ($r->getMethod() === 'GET') {}
```
Gives:
```
ERROR: [TypeDoesNotContainType](https://psalm.dev/056) - 15:5 - 'GET' cannot be identical to int
```

https://psalm.dev/r/76374b9830

**Comment by AndrolGenhald** [comment]
This is due to the way the CallMap currently overrides any user defined class/function, and `HttpRequest` is in the CallMap for https://pecl.php.net/package/pecl_http. We need to remove all `pecl_http` defined functions and classes from the CallMap and add an extension stub instead. See also #7577 and #7641.

For now you can [namespace it](https://psalm.dev/r/ac4365e56c) (and arguably you should probably do this anyway).

**Comment by sanmai** [comment]
I'm going to close this since namespacing is the way.
