### ISSUE TITLE
Add support for auto fixing missing throws doc block errors

### ISSUE THREAD

**Issue by aszenz** [vimeo/psalm#7918]
Related to 
`checkForThrowsDocblock` option, it would be nice to auto add throws docblock to functions. 
Use case: 
Better understanding of how the function can fail for the caller, often times it is useful then to refactor the code to not catch the exception at the higher level and re throw it to provide more context

**Comment by orklah** [comment]
Good idea :)

If you want to dive into it, the issue is emitted here: https://github.com/vimeo/psalm/blob/0fe6eaf5d9c451a1fc9b345c0ccde0cbbfbd77fd/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php#L726

The goal would be to reproduce what we do here for MissingReturnType: https://github.com/vimeo/psalm/blob/ba8234dd2caca77c537b108b53724d53c1f03369/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php#L374

We check that we're trying to fix that and we change the docblock with `FunctionDocblockManipulator` here: https://github.com/vimeo/psalm/blob/ba8234dd2caca77c537b108b53724d53c1f03369/src/Psalm/Internal/Analyzer/FunctionLike/ReturnTypeAnalyzer.php#L944

**Comment by aszenz** [comment]
@orklah I made a draft pr which supports this, would be interested in your feedback
