### ISSUE TITLE
MethodSignatureMismatch with templates and abstract methods.

### ISSUE THREAD

**Issue by rzvc** [vimeo/psalm#7960]
```php
/** @template T */
abstract class Foo
{
    /** @param T $value */
    public abstract function bar($value) : void;
}

/** @extends Foo<string> */
class Bar extends Foo
{
    public function bar(string $value) : void
    {
    }
}
```
https://psalm.dev/r/97edc2b801

Output:
```
ERROR: [MethodSignatureMismatch](https://psalm.dev/042) - 13:32 - Argument 1 of Bar::bar has wrong type 'string', expecting '' as defined by Foo::bar
```

**Comment by AndrolGenhald** [comment]
I believe is intentional, using a docblock [works fine](https://psalm.dev/r/fb78f2bbdd). This is also [not related to templates](https://psalm.dev/r/dab673071d).

PHP type signatures actually alter the behavior of the program (causing errors and/or casting depending on strict_types), so adding or removing a PHP type signature in a child is disallowed.

**Comment by rzvc** [comment]
> PHP type signatures actually alter the behavior of the program (causing errors and/or casting depending on strict_types), so adding or removing a PHP type signature in a child is disallowed.

It looks like you are correct. It's not related to templates and does PHP error out with that code.

I did find something related tho, where PHP doesn't crash, but Psalm loses the template type - will create a new issue.
