### ISSUE TITLE
False positive with `func_get_args()` usage on a callable.

### ISSUE THREAD

**Issue by niconoe-** [vimeo/psalm#7978]
Hello there!

I'm encountering what I think is a false positive when dealing with a callable that uses `func_get_args()`.

Here is the link of the source code that generates an error, but IMO, shouldn't: https://psalm.dev/r/460242b255

As long as `func_get_args` but also `func_get_arg` or `func_num_args` is used in a callable, the number of arguments sent to the callable could be anything even if the signature of the callable makes you think 0 arguments are expected.

What do you think about?

Thanks a lot!

**Comment by AndrolGenhald** [comment]
I actually consider [this](https://psalm.dev/r/573c42eed7) more of a bug since the closure should actually have 3 arguments in this case.

Your case I wouldn't consider a bug. Although PHP allows passing more arguments than a function actually takes, there are a good number of things like this where Psalm is necessarily more strict than PHP in order to provide useful checks. Why not use a [variadic argument](https://psalm.dev/r/6bf2be9490)?

**Comment by niconoe-** [comment]
The usage of variadic argument is really clever! Thanks! I think I'll use this.


> Your case I wouldn't consider a bug. Although PHP allows passing more arguments than a function actually takes, there are a good number of things like this where Psalm is necessarily more strict than PHP in order to provide useful checks. 

I understand this. I though we could still provide a specific behavior for when a `func_get_args` or similar is used, but actually there's so many other ways to get "unnamed" arguments (reflection, stack trace analysis, …) than it's probably not worth it.

Thanks a lot!
