### ISSUE TITLE
InvalidNamedArgument

### ISSUE THREAD

**Issue by mat-twg** [vimeo/psalm#8039]
psalm: InvalidNamedArgument: Parameter $separator does not exist on function SplFileObject::fputcsv

![image](https://user-images.githubusercontent.com/64251479/171433865-9652a5c6-203d-4589-a367-d186dc2cd1a6.png)

**Comment by KevinVanSonsbeek** [comment]
The CallMap for the SplTempFileObject::fputcsv should also be updated, as it extends the normal SplFileObject. Could be overlooked possibly.

**Comment by KevinVanSonsbeek** [comment]
> The CallMap for the SplTempFileObject::fputcsv should also be updated, as it extends the normal SplFileObject. Could be overlooked possibly.

Update:
It seems that the param name was changed when going from php 7.4 to php 8.0

Probably due to the named arguments feature being implemented, and seperator being a clearer name than delimiter. So the delta should also be adjusted. 

Only nuisance seems to be the fact that param name changes when going from 7.4 to 8.0 do not seem to be documented in the php docs.

**Comment by mat-twg** [comment]
> > The CallMap for the SplTempFileObject::fputcsv should also be updated, as it extends the normal SplFileObject. Could be overlooked possibly.
> 
> Update: It seems that the param name was changed when going from php 7.4 to php 8.0
> 
> Probably due to the named arguments feature being implemented, and seperator being a clearer name than delimiter. So the delta should also be adjusted.
> 
> Only nuisance seems to be the fact that param name changes when going from 7.4 to 8.0 do not seem to be documented in the php docs.

yeah... smells `JetBrains\PhpStorm` issue, thank you!
