### ISSUE TITLE
`UnusedClosureParam` for required closure arguments

### ISSUE THREAD

**Issue by boesing** [vimeo/psalm#8095]
When I have a method which declares a callback to consume 2 arguments but my defined callback does not care about the first argument, psalm is issuing `UnusedClosureParam` even tho, its not like I could omit it.

I stated this question already a few months back and the suggestion was to use something like `$_`. 
Sadly, from my perspective, this is:
1. less descriptive of what the value would contain (e.g. in case it has to be used in a future feature)
2. mostly violates styleguides (i.e. when camel cased variables should be used)
3. can not be used more than once (i.e. when one has 1 or more required arguments which are not used)

---

I would like to propose a last-minute feature to the next major which allows closures to consume unused parameters when they are required due to its order.

## Disallowed
https://psalm.dev/r/c2b33c5cae

## Allowed
https://psalm.dev/r/a6201b4d4a

---

Is there a strong veto against this behavior?

**Comment by AndrolGenhald** [comment]
>  less descriptive of what the value would contain (e.g. in case it has to be used in a future feature)

You can use any name prefixed by an underscore, so `$_foo` is fine.

> mostly violates styleguides (i.e. when camel cased variables should be used)

I'm a bit surprised by that since there's a pretty strong convention in multiple languages that underscore or underscore prefixed variables are unused placeholders (but maybe I'm just biased towards thinking it's normal since I've been using Rust lately).

> can not be used more than once (i.e. when one has 1 or more required arguments which are not used)

Using an actual name with an underscore prefix solves that.

> Is there a strong veto against this behavior?

I'm not strictly opposed to it, but I'm not really convinced it's necessary.

**Comment by boesing** [comment]
> I'm not strictly opposed to it, but I'm not really convinced it's necessary.

My fingers typing `@psalm-suppress` and/or my baselines of several projects tell me other 😅 
I just don't see why I have to type a useful variable name but with a prefix `_` just to get rid of a psalm issue which (IMHO) is not an issue.

I am open to add a configuration flag (such as `findUnusedPsalmSuppress` but for `findUnusedClosureParam` instead) so that feature can be at least toggled.

**Comment by orklah** [comment]
Well, I'd merge a PR doing that. It doesn't seem like a big deal either way. If it's a repeated usage, I can understand it become annoying...

**Comment by AndrolGenhald** [comment]
I think the hard part here is that the closure analysis happens separately from the analysis of its usage, and we also don't want unused closure params ignored **unless** that closure is used somewhere that the param is required. For [this code](https://psalm.dev/r/e2f9dbb132), the analyzer will add `UnusedClosureParam` when analyzing the closure itself, then line 5 changes nothing, and finally line 13 is analyzed and it needs to notice that the first 3 parameters are now required and remove the `UnusedClosureParam` from the `IssueBuffer`.

> ## Disallowed
> 
> https://psalm.dev/r/c2b33c5cae
> ## Allowed
> 
> https://psalm.dev/r/a6201b4d4a
> 
> Is there a strong veto against this behavior?

Shouldn't those both be allowed? If we allow an earlier unused parameter to be ignored because it's used somewhere that requires a certain number of parameters, why not a later parameter as well?

> I am open to add a configuration flag (such as findUnusedPsalmSuppress but for findUnusedClosureParam instead) so that feature can be at least toggled.

I think I'd prefer a config for this, I'd personally much rather have the visual indication of the underscore prefix that indicates a parameter is intended to be unused. I'm not sure what the default config should be though.

**Comment by boesing** [comment]
> Shouldn't those both be allowed? If we allow an earlier unused parameter to be ignored because it's used somewhere that requires a certain number of parameters, why not a later parameter as well?

No, because the allowed one has to be suppressed while you can delete the unused argument in the second example. The problem I have with that issue is, that it is not fixable unless one has to use an annoying underscore. I would also be happy with something like `fn (,,int $argICare) => ++int` but PHP does not allow that (but does allow such stuff for `list` 🤷🏼‍♂️

**Comment by AndrolGenhald** [comment]
> you can delete the unused argument in the second example

Huh, didn't know Psalm [allowed that](https://psalm.dev/r/6765bd8a3e).

**Comment by boesing** [comment]
> Huh, didn't know Psalm

I am happy that it does. given the fact that `set_error_handler` for example can pass a bunch of arguments. I would not want to declare all of them 😅

**Comment by VincentLanglet** [comment]
I exactly encounter the issue with set_error_handler
https://psalm.dev/r/0c2afbb9f0

This error seems just a bug to me.

**Comment by weirdan** [comment]
What's wrong with suppressing `UnusedClosureParam` where you don't need it?

**Comment by weirdan** [comment]
@VincentLanglet I'm not sure, are you implying that `InvalidScalarArgument` in your second example is wrong? It seems valid to me: https://3v4l.org/mo1p6

**Comment by VincentLanglet** [comment]
> What's wrong with suppressing `UnusedClosureParam` where you don't need it?

Because we don't want to suppress `UnusedClosureParam` globally because it can be useful elsewhere.
And we don't want to manually suppress `UnusedClosureParam` for this example because the param is not useless.

> @VincentLanglet I'm not sure, are you implying that `InvalidScalarArgument` in your second example is wrong? It seems valid to me: https://3v4l.org/mo1p6

Sorry, I may have to explain more the example.

Let's say I wrote
```
set_error_handler(static function (int $type, string $message): bool {
     return $type !== 0;
}, \E_USER_DEPRECATED);
```
`$message` will be reported as unused.

Great, I can remove the `$message` param.
```
set_error_handler(static function (int $type): bool {
     return $type !== 0;
}, \E_USER_DEPRECATED);
```
is valid for psalm.

Now, let's say I wrote
```
set_error_handler(static function (int $type, string $message): bool {
     return $message !== '';
}, \E_USER_DEPRECATED);
```
this time `$type` is reported as unused.

But removing the param will break the code
```
set_error_handler(static function (string $message): bool {
     return $message !== '';
}, \E_USER_DEPRECATED);
```
and psalm know it, since it's reported as an error.
So psalm shouldn't report the param as useless.

To me, only param which can be removed from the signature should be reported.

**Comment by boesing** [comment]
> To me, only param which can be removed from the signature should be reported.

That was the initial idea when creating this issue.
