### ISSUE TITLE
Linking variables and functions to definitions

### ISSUE THREAD

**Issue by BlakeMScurr** [vimeo/psalm#815]
Hey yo, 

I was using https://github.com/nikic/PHP-Parser (which I understand you use as a base for your [DependencyFinderVisitor](https://github.com/vimeo/psalm/blob/master/src/Psalm/Visitor/DependencyFinderVisitor.php#L37)), and I hit some limitations that the maintainer [said](https://github.com/nikic/PHP-Parser/issues/508) you may have worked on here. 

In particular, I was trying to find all call sites of a function from its definition and vice versa, and find the declaration of a variable from a place where it's used. My hope is that the info required for this is in your [storage objects](https://github.com/vimeo/psalm/blob/master/docs/how_psalm_works.md#storing-data-from-scanning) after parsing - does it seem plausible? Is there any extension that needs to be done to make it happen?

**Comment by weirdan** [comment]
There's [Psalm\CodeBase::findReferencesToMethod()](https://github.com/vimeo/psalm/blob/6bfde90db4f676a98b48270074a93f1fa406d49c/src/Psalm/Codebase.php#L319) (and a similar method for class-like things), but I strongly suspect it requires running full analysis pass before you can call that.

**Comment by muglug** [comment]
Hey, yeah as @weirdan says, it requires a full analysis pass, because to correctly understand 

```php
$foo->bar()->bat()->bang()
```

every individual expression needs to be resolved, which can only be done in the analysis phase.

[These two methods](https://github.com/vimeo/psalm/blob/dc02ca8a7a325e0eca0db2e4c5d9a8c8ebe9297c/src/Psalm/Codebase.php#L314-L379) find uses of methods and classes when `Codebase::$collect_references` is turned on.

`Psalm\Storage\FunctionLikeStorage::$referencing_locations` contains all the referencing locations that Psalm can reason about for methods (regular functions aren't yet supported, but wouldn't be hard to add).

`Psalm\Storage\ClassLikeStorage::$referencing_locations` contains the respective ones for classes, traits, interfaces etc.

Obviously the analysis isn't necessarily complete - there may often be times when Psalm cannot infer the

**Comment by BlakeMScurr** [comment]
Nice, thanks for the help, guys. This is exactly what I'm looking for with respect to method references.

Is there anything equivalent that will let me find references of to a variable from its declaration? It looks like the methods on Codebase only give access to references of classes and methods. I was going to look at using [this](https://github.com/ircmaxell/php-cfg), but I thought you might have solved this problem too.

**Comment by muglug** [comment]
That's a little tricky because variables can be defined in multiple places and used once e.g.

```php
if (rand(0, 1)) {
  $a = 1;
} elseif (rand(0, 1)) {
  $a = 2;
  return $a;
} else {
  $a = 3;
}
echo $a;
```

Here it's less about where `$a` is defined and used, but rather where `$a (line 2)`, is used, and which definitions of `$a` are used by the `echo` statements.

Psalm's dead code detection has various ways to deal with this - you can look at how `Context::$unreferenced_vars` is used
