### ISSUE TITLE
Lowercase strings should be a sub-type of non-empty-string

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8173]
https://psalm.dev/r/32211c9676

The error doesn't make sense, since lowercase string is (should be) part of non-empty-string. As in every lowercase-string is also a non-empty-string.

**Comment by AndrolGenhald** [comment]
Disagree, I would define lowercase string as a string where every letter is lowercase. `""` is a string where every letter is lowercase.

Also, `strtolower()` results in a `lowercase-string`, so if we did this `strtolower($possiblyEmptyString)` would be completely broken.

Leaving this open though because `lowercase-string` and `non-empty-string` should _intersect_, so that's a bug.

**Comment by orklah** [comment]
That's not so simple. Any string going through strtolower is a lowercase-string. Meaning the empty string could be a lowercase-string, There's no subtype or supertype relation between the two

**Comment by AndrolGenhald** [comment]
@orklah Ninja'd :laughing:

**Comment by AndrolGenhald** [comment]
Actually we already have #8125 for this.

**Comment by kkmuffme** [comment]
But in PHP the sides of the comparison are reversible. Means:

#8125 
>non-empty-string can never contain lowercase-string

This is clearly a false positive that needs to be fixed.

While this would fix the first error in https://psalm.dev/r/d27925b0f7, I would still get an error for:
>lowercase-string does not contain non-empty-string

But this makes no sense. The conditions are functionally identical - there must be either an error for both or for none.

**Comment by AndrolGenhald** [comment]
I would consider that issue to cover both of those errors. If the types are made to intersect correctly they should both be fixed.
