### ISSUE TITLE
Callable return type not validated

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8179]
https://psalm.dev/r/780d77b41a

b returns string, but a expects a function that returns void. Should give error.

It works correctly for params though: https://psalm.dev/r/ce3fa40d0e

**Comment by AndrolGenhald** [comment]
This is intentional. Return types are covariant, so [more specific](https://psalm.dev/r/aa60d32e94) return types are allowed. `void` is a special case, since the return type is guaranteed to be ignored it's treated like `mixed` when doing the callable comparison, so a function can return anything it wants to and still satisfy `callable(): void`.

The one improvement I could see here is when the callable is `@pure`, passing a pure callable as a `callable(): void` is probably never a good idea, but Psalm [doesn't catch that](https://psalm.dev/r/651c28d230) right now.

**Comment by kkmuffme** [comment]
But this is a problem when using https://psalm.dev/docs/running_psalm/issues/UnusedFunctionCall/

Also it makes no sense. null and void are the same thing. Why do I get an error in one case but not in the other?
https://psalm.dev/r/c4a2380fc7
https://psalm.dev/r/780d77b41a

Anyway:
to get expected behavior, always use :null not :void in phpdoc, then psalm does what one would expect

**Comment by AndrolGenhald** [comment]
> null and void are the same thing.

Actually no, they're slightly different. A function with a `void` return type will resolve to `null` when called, but that's just a quirk of PHP's implementation to make compatibility easier. Per the documentation:

> null is not a valid return value for a void function.

The intention obviously being that a function returning `void` returns "nothing" (sort of...). Psalm will [warn you](https://psalm.dev/r/aac8e479f7) if you use the result of a function that returns `void`, so we can treat [this](https://psalm.dev/r/acffeab336) differently from [this](https://psalm.dev/r/3be7c9c284).
