### ISSUE TITLE
False positive (InvalidReturnType) for never return via call to untyped function

### ISSUE THREAD

**Issue by ssnepenthe** [vimeo/psalm#8185]
https://psalm.dev/r/1e823779d9

Psalm appears to be correctly inferring that `viaExit` and `viaException` have a `never` return type yet it is still raising an `InvalidReturnType` issue for `indirectExit` and `indirectException`.

Adding explicit types to the `via*` functions fixes this: https://psalm.dev/r/a956736c51

It looks like originally a function with `no-return` return type was required to explicitly throw or exit and could not instead call another function that throws or exits. However it seems like this behavior was quickly changed: https://github.com/vimeo/psalm/issues/1155#issuecomment-451002492. Is it possible this is related?

Also possibly related to the second example here?: https://github.com/vimeo/psalm/issues/8180

**Comment by ssnepenthe** [comment]
Another possibly related issue?

https://github.com/vimeo/psalm/issues/8175

**Comment by AndrolGenhald** [comment]
This is expected and correct. Since there is no return type for `neverViaExit` and `neverViaException` the return type is inferred to be `mixed`. See also my [latest comment](https://github.com/vimeo/psalm/issues/8175#issuecomment-1167662537) on #8175, Psalm will suggest the narrowest possible return type to you when you're missing a return type, but giving `neverViaExit` a `string` return type is totally valid too.

**Comment by orklah** [comment]
@AndrolGenhald Ninja'd 😄

**Comment by ssnepenthe** [comment]
Interesting...

Come to think of it, I believe this expected behavior has been described to me before on a completely separate issue and I just didn't manage to connect the dots.

In any case, thanks for the quick response!
