### ISSUE TITLE
PHP8.1 xml output supprt

### ISSUE THREAD

**Issue by wouter-toppy** [vimeo/psalm#8321]
Almost simular to https://github.com/vimeo/psalm/pull/2856

except, its not possible to pass a argument to the function anymore. 

```
Uncaught RuntimeException: PHP Error: DOMDocument::createTextNode(): Passing null to parameter #1 ($data) of type string is deprecated in /app/vendor/openlss/lib-array2xml/LSS/Array2XML.php:174 in /app/vendor/vimeo/psalm/src/Psalm/Internal/ErrorHandler.php:66
```

Bug is not directly fixable in psalm. but needs to be fixed in the lib-array2-xml bundle.  
Reported a issue there, which needs to be fixed and tagged. 

if so. than psalm need to require expliceit that version (or higher)

https://github.com/nullivex/lib-array2xml/issues/21

**Comment by caendesilva** [comment]
Ran into this as well. Psalm v4.30.0 on PHP 8.1.10.

The [lib-array2xml](https://github.com/nullivex/lib-array2xml) repo has not had any updates in over three years. It could be abandoned. Fork?

The workaround is incredibly simple, albeit gruesome. Apply the fix from this PR [nullivex/lib-array2xml#19](https://github.com/nullivex/lib-array2xml/pull/19/files#diff-fd7422955e12e328341e3ce5c3eb7b912cb75f1b80dd8c53aeb7f65820a18373R173) to the file in the vendor directory.
![image](https://user-images.githubusercontent.com/95144705/200902534-3ba8db99-170a-4d0e-8a62-10ae1279f4ea.png)

While normally modifying vendor files is a huge no-no for me, since I just need this for a one-off on my local machine it's fine for me, just beware.
