### ISSUE TITLE
Update Psalm version on psalm.dev

### ISSUE THREAD

**Issue by vudaltsov** [vimeo/psalm#8332]

**Comment by orklah** [comment]
psalm.dev is willingly using the dev/master branch, which is dedicated to Psalm 5. Every change made in 4.x branch eventually get merged into it but it can sometimes takes time between two merges. I'll close this because we have no reason to change this. The only improvement could come from making more regular merges but I don't have enough time to spend for that currently

**Comment by vudaltsov** [comment]
Ok, thank you for the explanations!
