### ISSUE TITLE
Argument 1 of b expects list<int>, array{0: int, 1: int} provided

### ISSUE THREAD

**Issue by sergkash7** [vimeo/psalm#8386]
https://psalm.dev/r/bd0731004b

**Comment by orklah** [comment]
For anyone wandering here in the future, `array{0: int, 1:int}` does not guarantee list behaviour because Psalm doesn't enforce the order of the keys for this notation. (Hence, `['1' => 1, '0' => 1]` would be a valid value for Psalm but would not be a valid list.

The correct notation for a list would have been `array{int, int}` like here: https://psalm.dev/r/e83b233ccf
