### ISSUE TITLE
The result of assertion-if-true assertions is always a generic bool

### ISSUE THREAD

**Issue by danog** [vimeo/psalm#8393]
https://psalm.dev/r/a21a57965a

**Comment by AndrolGenhald** [comment]
This is sort of related to #7096. The way I see it, `@psalm-assert-if-true` says that if the return value is `true` then `$a` must be an `int`, but it _doesn't_ say that if `$a` is an `int` the return value must be `true`. Maybe we could try to work in some sort of `@psalm-assert-exact` or something to make this work, but right now I think this is intentional. It could certainly be improved though.

**Comment by orklah** [comment]
`@psalm-assert-exact` could probably be inferred through the use of both `assert-if-true` and `assert-if-false` (but it's broken right now).

It's broken because Psalm already assumes that `assert-if-true` can be negated: https://psalm.dev/r/8d38a5bd94

But it's not: https://psalm.dev/r/edb10f9228 (here we can be sure $a is an int when the return is true, but it doesn't guarantee $a is not an int when the return if false, but Psalm does that anyway)

**Comment by AndrolGenhald** [comment]
> `@psalm-assert-exact` could probably be inferred through the use of both `assert-if-true` and `assert-if-false`

Good point, [this](https://psalm.dev/r/f6de401c32) should just be fixed instead of adding a new tag. I think this extra inference needs to require that the `if-false` type is exactly the negation of the `if-true` type though.

**Comment by danog** [comment]
+++, would be real nice, plus it seem like native assertions are kinda broken in this sense as well: https://psalm.dev/r/13be9b6dce

**Comment by orklah** [comment]
Note that assertions are not made to alter $result. $result is altered only by return types (that can be conditional). This issue makes us consider generating a conditional return based on assertions, but it's an enhancement.

The code you posted is not broken in that sense. What we miss for is_int if we want to fix your link without this enhancement is a stub that describes that if the param of is_int is an int, then the return is true

**Comment by orklah** [comment]
I'll close this, Some of the things I said were false and there was a confusion about the goal of assertions. If there is still an enhancement, we better start a new issue
