### ISSUE TITLE
Exclude files based on pattern

### ISSUE THREAD

**Issue by Mte90** [vimeo/psalm#84]
Actually it's not possible to use patterns like:
```
<directory name="*lib*" />
```

**Comment by muglug** [comment]
The second example `<directory name="/vendor/*" />` is redundant (as `<directory name="/vendor" />` has the same effect.

But I'll add support for wildcard matching.

**Comment by Mte90** [comment]
yes, for the second one you are right, I update the first commit

**Comment by fesor** [comment]
And how about `file` patterns? For example I want to supress specific issues for specific files, all of which has some kind of suffix.

```
<file name="*DTO.php">
```

**Comment by muglug** [comment]
@fesor have added that (and directory pattern matching works as well)

**Comment by kkmuffme** [comment]
Doesnt seem to work?

```
<UndefinedGlobalVariable>
	<errorLevel type="suppress">
		<directory name="*/templates" />
	</errorLevel>
</UndefinedGlobalVariable>
```

Results in:
Could not resolve config path to /var/www/vhosts/somepath//*/templates

**Comment by olleharstedt** [comment]
Hm this is not working very well for me. Wanting to ignore all files in different `views/` folders:

            <directory name="*/views/*" />

What's the correct syntax?

**Comment by ctf0** [comment]
@quisse @olleharstedt after search issues and try & error, 
i found that atm the pattern wont work unless all the scanned directories have that `thing` u r looking for, so for example `<directory name="*/views/*" />` wont work because any directory psalm will search will have to have the `views` folder or it wont work.

same goes for `*.phtml`, all the directories will have to have this file present or it wont work.

imo wild cards should be treated differently from absolute/fixed paths.

@muglug plz correct me if am wrong or missing something

**Comment by mringler** [comment]
Could not figure it out from documentation or comments. But this works:
```xml
                        <ignoreFiles>
                            <directory name="src/**/Checker" />
                            <file name="src/Psalm/Checker/*Checker.php" />
                        </ignoreFiles>
```
