### ISSUE TITLE
Does declare(strict_types=1) affect Psalm?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8501]
Follow-up to https://github.com/vimeo/psalm/issues/1455 because the question wasn't sufficiently answered.

Given config with level 1 - does adding strict_types (or `useStrictTypes` in projectFiles) actually report additional errors? Or will the errors only be more strict (e.g. `InvalidArgument` instead of `InvalidScalarArgument`)?

**Comment by orklah** [comment]
There is a slight but notable difference:

https://psalm.dev/r/484b28635d

That happens if you try to call an internal function on a mixed variable (full code here: https://github.com/vimeo/psalm/blob/8098755ce5ad6f3048506860fb9b90a1777c24a9/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php#L1137)

If you are in strict mode, Psalm will assume that the type of your variable is the type of the parameter of the method you just called (because otherwise, you would have gotten a TypeError). But it won't do that if you're not in strict mode.

Otherwise, I believe it just impacts the severity of the error raised
