### ISSUE TITLE
Option/Annotation to force types to not to be combined

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8517]
https://psalm.dev/r/3de1643e45

How can I tell psalm to keep my arrays separate?
Basically I have an array where if 1 key is an array, then all keys are arrays. If 1 key is a string, then all other keys are strings too.

**Comment by orklah** [comment]
Psalm doesn't support this for now. It's not even a question of an option to enable because right now, Psalm just can't store two different arrays in a single Union. I'll close this because I'm sure we discussed this elsewhere and we have an open ticket where we say that a refactor of the type system is needed
