### ISSUE TITLE
Possibly false positive ParadoxicalCondition

### ISSUE THREAD

**Issue by VBelozyorov** [vimeo/psalm#8539]
Hello! 
Please look at https://psalm.dev/r/2afdd66eed. Looks like there shouldn't be `ParadoxicalCondition` because code executing between two similar `if` conditions is may change variable being checked in the condition.

**Comment by orklah** [comment]
Here's the same code snippet but after disabling the setting "Memoize property assignments":

https://psalm.dev/r/fcf02f90c2

The issue is fixed. You have this setting available in your config file so feel free to change it.

But keep in mind you're as likely to get new false positives due to the fact you're now forgetting property assignment.

There is no possible way to have a behaviour that is always good in this situation. If you can control the source code, I suggest suppressing the issue here or refactoring in a way Psalm won't be able to memoize the value of your property (for example, checking cache existence through a method)
