### ISSUE TITLE
Cannot call method X on possibly null value

### ISSUE THREAD

**Issue by LauraTaylorUK** [vimeo/psalm#8548]
https://psalm.dev/r/d0aeeca81f

I have a class with two methods, `foo()` and `bar()` and they both initialize the private property `$awesome`.

For some reason, that I can't figure out, psalm thinks that the above private property can be null, when that is impossible.

I'd appreciate some help.

Thank you.

**Comment by LauraTaylorUK** [comment]
Thank you for the detailed answer.

To be honest, to me it looks like something that should be done by psalm automatically, eg: track the status of the private property within each method. The solution you mention feels like a hack, the same as ignoring the error from psalm.xml.

Since I prefer to avoid adding psalm-specific comments within the code, I'll just ignore the error in psalm.xml and move on.

Thank you again.

**Comment by AndrolGenhald** [comment]
> The solution you mention feels like a hack

Hard to disagree with that :laughing:

> it looks like something that should be done by psalm automatically

This isn't safe for public methods since a child could override it and change what it does. It really needs to be in the method's contract, which a child can't change. Personally I view this as a feature even for private methods, looking at it conceptually as contract-based you don't end up with any weird "action at a distance" where changing the internals of one method mysteriously causes a bunch of other stuff to fail.
