### ISSUE TITLE
False positive: MethodSignatureMustProvideReturnType in __toString()

### ISSUE THREAD

**Issue by derrabus** [vimeo/psalm#8557]
The MethodSignatureMustProvideReturnType check tells me if I need to add a native return type to a function in order to avoid a deprecation notice on PHP 8.1+.

However, it is also triggered on `__toString()` although PHP does not trigger a deprecation here.

https://psalm.dev/r/687115a153
https://3v4l.org/uHsSj

**Comment by orklah** [comment]
Thanks for the feedback!

Unfortunately, this issue only exists on the website(and our master branch) for now but it was disabled on 4.x and soon will be disabled on master.

It was causing a lot of false positives for plugin users because Psalm wrongly considers plugin stubs as part of php core. We won't fix your bug for now because we don't know when this issue will be enabled again.

**Comment by derrabus** [comment]
Sorry, I should've mentioned that I found this issue while testing Psalm 5. Psalm 4 is not affected as far as I can tell.

**Comment by derrabus** [comment]
Thank you for your answer!

**Comment by orklah** [comment]
Thank you for testing Psalm 5 :) It's very helpful to get feedback!

**Comment by derrabus** [comment]
The error is still present in 5.0.0-rc1. Shall we reopen the issue?

**Comment by orklah** [comment]
Most definitely!

**Comment by orklah** [comment]
@danog do you know what happened here?

We merged your PR for this issue here: https://github.com/vimeo/psalm/pull/7363
But then we had to revert it here: https://github.com/vimeo/psalm/pull/7539 because stubs are wrongly qualified as not "user_defined". This was making Psalm enforce wrong return types coming from stubs

But it still end up in master? Do you remember us re-adding it later? Or maybe a mishandling on my part?

**Comment by VBelozyorov** [comment]
Perhaps, this should be closed as fixed now, because it can't be reproduced with the example from the first post (https://psalm.dev/r/687115a153) anymore.
I also had this in a proprietary project and now I cannot reproduce with Psalm 5.24.0 and 5.26.1

**Comment by derrabus** [comment]
Thank you, let's close the issue then. 🎉
