### ISSUE TITLE
MissingImmutableAnnotation when @psalm-consistent-constructor is used

### ISSUE THREAD

**Issue by jnvsor** [vimeo/psalm#8602]
https://psalm.dev/r/177d684e3b

When a parent is marked with `@psalm-consistent-constructor` the child gets a `MissingImmutableAnnotation` error if it has a constructor defined

**Comment by weirdan** [comment]
This is what happens here:

1. Psalm can infer property types from 'simple constructors' (constructors that are only assigning properties, and do not call any methods/functions). It only does so if some of the properties are missing their types. So a workaround would be to declare `$renderer` property type: https://psalm.dev/r/8ec96bc012
2. Every 'simple constructor' is an external-mutation-free method (this is part of a definition of a 'simple constructor'), so when property types are successfully inferred, we mark that constructor as `external-mutation-free`.
3. Constructors that call `parent::__construct()` are not 'simple constructors', so their mutation-free status is not inferred
4. `@psalm-consistent-constructor` requires descendant constructors to be marked mutation-free if the parent constructor is, but only if parent constructor was marked mutation-free *explicitely* (with a docblock tag).

The problem comes from the fact that we mark the parent constructor as mutation free, but fail to add the flag indicating that mutation free has been inferred rather than set explicitly (with a docblock tag).
