### ISSUE TITLE
psalm-pure invalid error

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#8625]
https://psalm.dev/docs/annotating_code/supported_annotations/#:~:text=one%20whose%20output%20is%20just%20a%20function%20of%20its%20input

>one whose output is just a function of its input

https://psalm.dev/r/dff3f37215 the output of `abc()` is pure, as it only depends on the input given (= always returns the same output for same input and has no side-effects) - but it still reports an error for it?

Are the docs wrong/am I misunderstanding "purity"? Or is this a bug?

**Comment by orklah** [comment]
It is the `no side-effects` thing that prevents you from setting this attribute.

With no additional annotation, this could happen:
https://psalm.dev/r/413d60d78e
https://3v4l.org/R0RLT

So Psalm must forbid you to modify attributes when precautions are not taken. However, you could use[ `@psalm-external-mutation-free` ](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-external-mutation-free) in order to inform Psalm that there is no mutation outside of the scope of the object: https://psalm.dev/r/97334d3fc9

Psalm will then allow you to change this attribute

**Comment by orklah** [comment]
Your object is not final, so __set could still be defined in a child (but it seems like even with final, Psalm doesn't allow it)

I guess we could add handling for setting a property on an object if:
- it was created locally
- the instance doesn't leave the current scope
- it's final
- it doesn't have __set
- the property is not static
- it doesn't have any __destruct
- we don't do anything else with the object that may persist it

I think I covered every possibility! Or you could flag the object external-mutation-free and help Psalm a little 😄

**Comment by orklah** [comment]
Do you have a snippet to show how this is related to never? I really struggle to grasp what's bugging you here
