### ISSUE TITLE
"Cannot call constructor on an unknown class" when creating class from variable

### ISSUE THREAD

**Issue by JoolsMcFly** [vimeo/psalm#8628]
Hi all.

I need to create new classes from an array of class names. I have added `allowStringToStandInForClass="true"` to `psalm.xml` but I still get the following error:
```
MixedMethodCall - src/MyClass.php:125:26 - Cannot call constructor on an unknown class (see https://psalm.dev/015)
```

Si I tried to add more context:
```php
foreach ($classNames as $className) {
    if (!class_exists($className)) {
        continue;
    }
    $class = new $className();  // <= how can I make this not fail?
}
```

Adding `class_exists` does not do the trick. Any ideas how to fix the reported error?
Thanks!

**Comment by orklah** [comment]
You seem to know the constructor doesn't have parameters, so I guess you have some kind of insight into what kind of class is pushed to you there.

Psalm need to know that too because otherwise, it can't guarantee you won't get a php error for passing wrong parameters.

So if you can document your $classNames as `array<class-string<SomeObjectOrInterfaceWithConstructWithNoParams>>`, it will solve your issue.

If you're not able to do that, it means you have a inherently unsafe construct and you'll have to suppress the issue instead of trying to fix it

**Comment by JoolsMcFly** [comment]
Right. I know constructors I am dealing with have no params so should be OK for now to use ReflectionClass (which solves my problem)?

```php
try {
    $cl = new ReflectionClass($className);
    $class = $cl->newInstance();
    if ($class instanceof SomeInterface) {
        // do something
    }
} catch (ReflectionException $e) {
}
```

I now need to figure out why phpstan reports `Dead catch - ReflectionException is never thrown in the try block.`.

**Comment by orklah** [comment]
If you know you have a `SomeInterface`, Psalm shouldn't complain after you check that, even without going with Reflection

About PHPStan, I'd assume they have a partial stub that doesn't document this exception

**Comment by JoolsMcFly** [comment]
Thanks for your follow up.

I originally had this:

```php
foreach ($classNames as $className) {
    if (!class_exists($className)) {
        continue;
    }
    $class = new $className();
    if ($class instanceof SomeInterface) {
        // blabla
    }
}
```

but I still had the error message on `$class = new $className();`.

**Comment by orklah** [comment]
Something like that should work: https://psalm.dev/r/f95a929e11

**Comment by JoolsMcFly** [comment]
Works like a charm. Thanks!
