### ISSUE TITLE
Possible variable alteration not taken into account

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#8663]
https://psalm.dev/r/07b2150dfe

In this piece of code, after passing the condition on line 10, Psalm thinks `$this->entityDeletions` will always be truthy, when it really won't be after one iteration.

**Comment by orklah** [comment]
Psalm has a setting called "Memoize property assignment" (assignment being the wrong term here because it also applies to assertions). When this is checked, Psalm will remember the value of properties checked/assigned at one point and checked again later (even if methods were called in between). This is useful in most cases, except on cases like yours where a method call is changing the value of the property that has been checked earlier.

For example, if you disable this config, the snippet passes: https://psalm.dev/r/c46edf55ca

You can try to disable it, but I think you'll see more errors pops up in other places where you want the exact opposite behaviour from Psalm

I'd advise having a `hasEntityDeletions` method in order to check indirectly the property. That way Psalm won't try to remember it: https://psalm.dev/r/6a74d9c227

**Comment by greg0ire** [comment]
Thanks @orklah !

**Comment by VincentLanglet** [comment]
@orklah Is there some psalm phpdoc in order to
- add to a call (like the method `change` in https://psalm.dev/r/5f42e1ff8c) in order to say "forget everything about the passed variable"
- or at least an inline phpdoc like `/** @psalm-forget $foo->bar */ to add after every calls

**Comment by orklah** [comment]
you can @var type the property after a call I guess. You could have a @psalm-assert on the called function but it will only narrow the property type
