### ISSUE TITLE
Array shape with int keys is a subset of `array<int, mixed>`

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#8706]
Sometimes we need a sealed array with numeric keys, but Psalm 5 reports about `InvalidReturnType`.

But, technically, `array{1: string, 2: string, 3: string}` is a subset/more-specific-type of `array<int, string>` or, more specifically, `no-empty-array<int<1, 3>, string>`

Example:

https://psalm.dev/r/4f19028bab

**Comment by weirdan** [comment]
> But, technically, `array{1: string, 2: string, 3: string}` is a subset/more-specific-type of `array<int, string>` or, more specifically, `no-empty-array<int<1, 3>, string>`

Correct. Psalm tells you that you're returning a more general return type, thus potentially violating the contract you declared with `@return` tag.

There are several problems packed into this issue:

1. The error should be `LessSpecificReturnStatement` because it's possible to coerce `array<int,non-empty-string>` into `array{1:string,2:string,3:string}` (unless we also require shapes to match the order of declaration? @danog)
2. Psalm should be able to infer that the loop results in `array{1:non-empty-string,2:non-empty-string,3:non-empty-string}`

**Comment by orklah** [comment]
> Psalm should be able to infer that the loop results in array{1:non-empty-string,2:non-empty-string,3:non-empty-string}

That part is a duplicate of https://github.com/vimeo/psalm/issues/8534

**Comment by orklah** [comment]
Fixed :)
