### ISSUE TITLE
Generator and possible exception leads to unfixable code

### ISSUE THREAD

**Issue by greg0ire** [vimeo/psalm#8819]
Here is an oversimplification of https://github.com/doctrine/orm/blob/4b577e7a18f6aaffd4077cf0f713f87bd8b0faeb/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php :

https://psalm.dev/r/1e816764ad

Clicking the "fix" button leads to https://psalm.dev/r/1e816764ad

Is there a correct way to annotate this?

**Comment by weirdan** [comment]
Simplified: https://psalm.dev/r/23fd09276c

**Comment by orklah** [comment]
@kkmuffme it may be due to the never PR restricting too much. Could you have a look?

**Comment by orklah** [comment]
Thanks for having a look!

It seems like Psalm doesn't see the function can return (implicitly) after the while loop. It's because the while loop looks like infinite so Psalm stops here. However, it doesn't see that there is a break statement in there that will end up breaking the loop.

It's an oversight I made in https://github.com/vimeo/psalm/pull/6392
