### ISSUE TITLE
Psalm should not prevent run-time checks

### ISSUE THREAD

**Issue by Chi-teck** [vimeo/psalm#8829]
Example:
https://psalm.dev/r/5d427ba6d8

Is there a way to keep the condition?

**Comment by danog** [comment]
The only way is to suppress this issue, personally I usually just don't add those runtime checks at all if I know this is internal code that will only be used by oher statically analyzed code, or I add a suppression only if I know the code may be used by external, non-statically-analyzed code (ie a library).

**Comment by danog** [comment]
For user input, the `$size` variable must be asserted to be >= 0 _before_ it is passed to the function, that's the whole point of specifying an `int<0, max>` typehint.

For third-party consumers not using static analysis, suppression is the only way to go, and it's for the best because it is still signaling a technically redundant check.

**Comment by Chi-teck** [comment]
Makes sense. Thank you.
