### ISSUE TITLE
StringBackedEnum is not known. 

### ISSUE THREAD

**Issue by RSickenberg** [vimeo/psalm#8855]
Greetings,

When I specify a StringBackedEnum to my method, psalm doesn't allow \StringBackedEnum who extends \BackedEnum.

https://psalm.dev/r/5e92764b5b

**Comment by weirdan** [comment]
> \StringBackedEnum who extends \BackedEnum.

Is it an interface you defined? It's missing from the snippet.

**Comment by RSickenberg** [comment]
No, @weirdan @orklah. `\StringBackedEnum` are from the embedded stubs 
![Screenshot 2022-12-13 at 11 20 41](https://user-images.githubusercontent.com/16922548/207291795-b1c463f5-3657-463f-8b06-ecd87622a54b.png)
![image](https://user-images.githubusercontent.com/16922548/207291923-4a55e072-d0b8-4fba-85d4-feb9c83bfd95.png)

**Comment by danog** [comment]
StringBackedEnum is not a native PHP enum, the jetbrains stubs use it only internally to improve type inference, it should _not_ be used by external code, because:

1) It is marked as `@internal`, thus it is explicitly forbidden to use it in code outside of the phpstorm-stubs repo: https://github.com/JetBrains/phpstorm-stubs/blob/e2da5a96182370065cfcb0ea5f03a6e2519a7641/Core/Core_c.php#L964
2) It is not autoloadable and will cause runtime errors when used:

```
[daniil@daniil-arch a]$ cat composer.json a.php; php a.php
{
    "require": {
        "jetbrains/phpstorm-stubs": "^2022.3"
    }
}
<?php

require 'vendor/autoload.php';

var_dump(interface_exists(\BackedEnum::class));
var_dump(interface_exists(\StringBackedEnum::class));

bool(true)
bool(false)
```

**Comment by RSickenberg** [comment]
Ok my bad, thank you for the precision @danog !
