### ISSUE TITLE
UnevaluatedCode for `declare` with `return`

### ISSUE THREAD

**Issue by ElisDN** [vimeo/psalm#8892]
It works in global namespace:

https://psalm.dev/r/d4d61a5673

but it throws error with namespace:

https://psalm.dev/r/49ce4900b9

**Comment by orklah** [comment]
There's a fault in Psalm handling of statements in and out namespaces

What happens here is:
- Psalm sees a new file
- It first process the classes, interfaces, traits, and namespaces
- For each namespace, it also extracts classes, interfaces and traits
- It puts every leftover statement in the namespace in a list
- It analyze the list of leftover statement for each namespace (so here, the return) because return could contain an expression that needs to be analyzed from within the namespace
- Then Psalm analyze statements that were out of the namespaces (here, it's the declare). However, the return already flagged the whole file as having returned so it fails.

There's a reason to that though, because any statement in the file could use any symbol also declared in the file, no matter the order of the statements.

So I guess, we would need to first extract symbols, collect leftover statement for each namespace and then process statements in the correct context and in order(so declare first, then leftovers by namespace). This may be a big change to support a very unusual pattern though...

What I'm more worried about is the fact that the declare is analyzed at then end (after namespaces) so I'm not sure it's correctly processed when analyzing other statements

**Comment by weirdan** [comment]
> What I'm more worried about is the fact that the declare is analyzed at then end (after namespaces) so I'm not sure it's correctly processed when analyzing other statements

Indeed: https://psalm.dev/r/3a0287fa0f

**Comment by vudaltsov** [comment]
This issue can be now closed!

**Comment by orklah** [comment]
Yes, this specific issue has been fixed. For future reference, https://github.com/vimeo/psalm/issues/8892#issuecomment-1347412144 still holds and the way Psalm process this is not optimal (and lead to very marginal edge cases for files that would contain a strict type declaration and namespace that have expressions that need to be evaluated)
