### ISSUE TITLE
Need `object<K, V>` type

### ISSUE THREAD

**Issue by andraaspar** [vimeo/psalm#8906]
In JSON, you implement a map like this: `{"key":"value"}`. Through `json_decode` it becomes a `stdClass`. `stdClass` can be:

1. used like a map
2. cast to an array

In the first case, `object{key: string}` does not express a map. We need a new type, something like `object<K, V>`.

The second case results in loss of type info as it turns from `object` (the closest type) into `array<array-key, mixed>`.

https://psalm.dev/r/2b2bb1e23e

I think the conversion of `object` to `array` and back should keep type info. We already have `array<K, V>` and this would be the flip side, helping with JSON support in the absence of `$associative` and `JSON_OBJECT_AS_ARRAY`, which corrupt the JSON structure in edge cases.

**Comment by danog** [comment]
I really don't think this is a good idea.

The concept of an unnamed object is bad enough idea already, there really isn't any need to introduce yet another unnamed object type for something that is clearly an antipattern: using stdClass/unnamed objects/arrays instead of tailor-made, validated DTO classes, for example using [valinor](https://valinor.cuyz.io/latest/).

Psalm's main job is finding bugs and enforcing good coding practices: using stdClass is not a good coding practice in PHP.

**Comment by danog** [comment]
In your specific case, what you probably want is valinor+the following class:

```
class DTO {
    public readonly bool $a;
    public readonly bool $b;
}
```

**Comment by andraaspar** [comment]
I understand. Thank you for taking the time to respond and suggest solutions. Valinor sure looks interesting, I'll take a deeper look at it.
