### ISSUE TITLE
InvalidArgument with ArrayObject

### ISSUE THREAD

**Issue by matiux** [vimeo/psalm#8995]
I'm in this situation: https://psalm.dev/r/91da9e07e5

`useList` function accepts an `\ArrayObject<int, stdClass>`. But the parameter I'm passing doesn't seem to like it

**Comment by weirdan** [comment]
Add a docblock to tell Psalm any int key is ok: https://psalm.dev/r/d626a07070

**Comment by jack-worman** [comment]
Isn't this a bug because
`ArrayObject<int<0, 1>, stdClass>` is sub-type of `ArrayObject<int, stdClass>`,
because `int<0, 1>` is a sub-type of `int`?

**Comment by danog** [comment]
Not really, it's a valid covariance issue: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by matiux** [comment]
@weirdan what if i wanted to avoid the temporary variable?
https://psalm.dev/r/05eee081c9

**Comment by danog** [comment]
I would recommend completely avoiding ArrayObject and passing directly the array.
The error is triggered because passing an array object is equivalent to passing the array by reference: the function may modify it, but unlike for reference parameters, for arrayobjects there is no equivalent for the @param-out annotation.
