### ISSUE TITLE
restrictReturnTypes LessSpecificReturnType don't force array shapes

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9029]
When using the undocumented `restrictReturnTypes="true"` config option, psalm tries to force array shapes with error `LessSpecificReturnType` e.g.

>The inferred return type 'array{foo: 'bar', hello: 'world', ...<array-key, string>}' for my_func is more specific than the declared return type 'array<array-key, string>'

Not sure if this config is active on psalm.dev, but this is the code that creates the issue for me:
https://psalm.dev/r/189e3d07aa

I mean I get where it's coming from, however this isn't really practical in many cases, as it will create monstrous phpdoc declarations for lots of files.

**Comment by danog** [comment]
Well, that's precisely the point of that config option, I don't really think that this behavior is something that should be removed.

**Comment by orklah** [comment]
Note: the config is available on psalm.dev in settings: https://psalm.dev/r/189e3d07aa

This option is an option precisely because it's not made to be enabled at all times. This is not a "stricter" version of Psalm, it's a tool made to find places where you might want to better describe your types. This is not always a good idea though. Documentation now mention a place where it's even detrimental: https://psalm.dev/docs/running_psalm/configuration/#restrictreturntypes. Trying to fix the error here will lead to a new (and legitimate) error even without this option.

I wouldn't want to introduce arbitrary limits again (there will always be projects that will want more than your given strlen) for such an option.

> other obvious cases (e.g. very dumb example https://psalm.dev/r/746cc8d0fe) should give an error too to use bool (should I open a separate issue for this?)

I'd argue this is not the role of Psalm. this is a CS issue. It's the same as `int|string|bool` = `scalar` or `array|Traversable` = `iterable` this is just a matter of preferences
