### ISSUE TITLE
What exactly is --allow-backwards-incompatible-changes supposed to do?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9059]
https://psalm.dev/docs/manipulating_code/fixing/

>using --allow-backwards-incompatible-changes=false you can make sure to not create backwards incompatible changes

What exactly does this mean? Backwards incompatible with what? Pre PHP7/non-native type hints?
What is the difference to `--safe-types` then?

It's not clear from the docs, the code, issues or the tests what exactly this means/is supposed to do?

**Comment by orklah** [comment]
Command line documentation says `Allow Psalm modify method signatures that could break code outside the project`

Basically, it's used by psalter to know when it's safe to add signature types to existing code (instead of docblocks). It will check whether your class is final to know if it could be inherited and will not add types where it could be a BC break for third party code that could use yours.

safe-types in the other hand is used to tell Psalm to only make changes when it's certain of the types (i.e. where the type did not code only from a docblock)
