### ISSUE TITLE
`strlen`  wrongly narrows down string type

### ISSUE THREAD

**Issue by lptn** [vimeo/psalm#9205]
https://psalm.dev/r/f5d6d67011

It seems like Psalm think $lastLabel is a falsy-string (`$lastLabel: ''|'0'`) for some reason when I use a check like:
```php
if (strlen($lastLabel) === 2) {
        return $lastLabel;
    }
```

Not sure is it related to `strlen` other another part of this code

**Comment by LeoVie** [comment]
For the record: Here is an even more minimal example
https://psalm.dev/r/f89f94ef22

**Comment by LeoVie** [comment]
Ah, my example from above was not accurate, but this one is https://psalm.dev/r/7c0918485f

In `AssertionFinder` we have
```php
if ($var_name) {
    if ($strlen > 0) {
        $if_types[$var_name] = [[new Assertion\NonEmpty()]];
    } else {
        $if_types[$var_name] = [[new Empty_()]];
    }
}
```

This says: When we compare a `strlen($x)` with something above `0`, then we assume that `$x` is not empty. 

So in the example we have two branches:
```php
if (strlen($x) === 2) {
    // branch A
    return $x;
}

// branch B
return '';
```

For psalm, `$x` is a non-empty-string in branch A and due to this an `empty-string` in branch B (which is clearly not correct here). In fact, `$x` should be just a `string` in branch A and in branch B. The only thing we know in branch A is, that `$x` is 2 chars long. This does not imply that `$x` is 0 chars long in branch A ($x can be a string with any length but 2 there).

When I change the implementation in `AssertionFinder` to
```php
if ($var_name) {
    if ($strlen === 0) {
        $if_types[$var_name] = [[new Empty_()]];
    }
}
```
psalm seems to treat that case correctly, as the only correct assumption we can do is, that if we compare `strlen($x)` with `0` and this statement is true, then `$x` is an `empty-string`. For `count` assertions, there is the `HasExactCount` assertion. There should be a `HasExactStrlen` assertion, too.

I hope this does make any sense :) Will add some more test cases for that beviour and create another PR. Likely there should be similar changes to the other types of `strlen` statement checks from #8761.

**Comment by theodorejb** [comment]
I'm also seeing this issue on dev-master when I use `strlen` with a less than comparison:
https://psalm.dev/r/7968ba9d34

**Comment by LeoVie** [comment]
I've created https://github.com/vimeo/psalm/pull/9221 
Some tests are failing. I guess, there's something missing in the `SimpleAssertionReconciler`, but I'm far from fully understanding what exactly is happening there...
Maybe someonce could take a look at that part?
