### ISSUE TITLE
array(): Type is not a valid method in docblock for Type

### ISSUE THREAD

**Issue by widoz** [vimeo/psalm#9321]
Looks like having a magic method defined via the block type throws an error when the name of the method is `array`.

Link: https://psalm.dev/r/061d84b9d3

**Comment by weirdan** [comment]
Is it a valid docblock syntax, though? `@method` tag was introduced before PHP started supporting native return types, so the syntax the PHPDocumentor team chose differs.

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#58-method
https://docs.phpdoc.org/guide/references/phpdoc/tags/method.html#method

The correct form would be https://psalm.dev/r/f9a871f3e1 (though the issue is still there).

**Comment by othercorey** [comment]
I think the type-first format is pretty standard for @method.

**Comment by widoz** [comment]
@weirdan Thanks for pointing it out.
