### ISSUE TITLE
Enhancement: InvalidArgument: show callable-array param/return type like for non-class callables

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9432]
https://psalm.dev/r/0ddf1df1a9

I think it would be good if the error message would include the expected type (instead of just `list{...}`), like it already does for non-class callables:
https://psalm.dev/r/e1313ba8ed

**Comment by orklah** [comment]
I don't understand, both errors are structured the same way:
`Argument %num% of %method% expects %expected_type%, but %provided_type% provided`

Can you write the error as you expected it?

**Comment by orklah** [comment]
ooh, I get it now, you would like for Psalm to infer that your array is not just an array but a callable and show you what the callable expects

You can somewhat makes Psalm understand that the array you have is destined to be called like this: https://psalm.dev/r/b9ea335524

But when Psalm does that, it didn't yet checked that your array is really callable and what's behind. If you want a glimpse of what's going on, when Psalm tries to process the function call and see you have an array where a callable is expected, it does that:
https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/Comparator/AtomicTypeComparator.php#L646
At that point, we're already very deep in the comparison between two types, Psalm then generates what you would want here: https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php#L198
Then it goes even deeper by comparing the new callable type generated to the original callable type expected:
https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/Comparator/CallableTypeComparator.php#L201

At that point, it will realize that your two callables don't match and will go way back, to the place where it tried to compare your two types and it will just display the two types as they were inferred at first:
https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/Call/ArgumentAnalyzer.php#L1042

Trying to make something nice out of all this would be complicated and I'm bound to be picky about the result but if you want to try to make a PR for adding this info in the error message, we could discuss it.

In the meantime I'll close this because I won't be implementing that myself and I doubt others will

**Comment by weirdan** [comment]
Can't we attempt to reconcile the argument type with whatever assertion `assert(is_callable())` makes if the parameter type is callable? If reconciliation is successful, we can then use the resulting type in the error message.

**Comment by orklah** [comment]
That's what a potential PR would look like but it's gonna be a pain.
imagine the expected type is `array<string>|callable`, should you display the provided type as an array with wrong types or as a callable with wrong types?
For me, at the very least, we would only do that for already identified callable types (for example `callable-array{0: Bar&static, 1: 'xyz'}` in my previous snippet would be displayed as something like `callable-array{0: Bar&static, 1: 'xyz'} (resolved as : callable(int, mixed): void)`.) For display purposes, Atomic would need to be autonomous to display that but you can't put that in getId(), so we would need an Atomic::getExtraDetails() that would return `(resolved as : callable(int, mixed): void)`.)` for callable-array.

**Comment by weirdan** [comment]
> imagine the expected type is array<string>|callable, should you display the provided type as an array with wrong types or as a callable with wrong types?

I would only try to display the argument as callable if the parameter is single-typed and callable.

> For me, at the very least, we would only do that for already identified callable types

Sounds to me a bit restrictive. 

> in my previous snippet would be displayed as something like `callable-array{0: Bar&static, 1: 'xyz'} (resolved as : callable(int, mixed): void)`

That's a good format.

> For display purposes, Atomic would need to be autonomous

Why? We have tons of `if ($type->hasMixed()) { IssueBuffer::maybeAdd(new MixedIssue); } else { IssueBuffer::maybeAdd(NormalIssue); }`. Another `if` wouldn't hurt that much.

> I'm not a fan of replacing TCallableArray by a TCallable 

I don't think I ever proposed that.

**Comment by orklah** [comment]
> Sounds to me a bit restrictive.

I guess if you restrict to callable only parameters, it's sufficiently narrow to try to resolve any argument, fine by me :)

>  Another if wouldn't hurt that much.

Note that it would probably need to be extended to many (and potentially all) comparison that end up raising issues. If we do it for parameters, it makes no sense to not do it for returns, for param-out, for templates etc... It's such a narrow case that I'm wary we'll end up with personnalized errors for many other types in the future if we start to accept one

> I don't think I ever proposed that.

I read too much into your comment then. I added that part at the end when I went to re-read your comment and I started having doubts you wanted to just transform any callable-array{0: Bar&static, 1: 'xyz'} into a `callable(int, mixed): void` after we made the `assert(is_callable())`
