### ISSUE TITLE
ArrayIterator<int<0, 1>, DateTime> does not match ArrayIterator<int, DateTime>

### ISSUE THREAD

**Issue by VincentLanglet** [vimeo/psalm#9501]
https://psalm.dev/r/2ad2b3ab93

But it works fine with `array<int<0, 1>, DateTime>`,
and also works fine for PHPStan https://phpstan.org/r/e1003919-80f2-4bf2-a280-5c90f6e8df33

**Comment by weirdan** [comment]
That's expected, as `ArrayIterator` cannot be declared as covariant because it allows modifications to the underlying array. You can use a narrower interface like `Traversable` instead.

Unlike objects, arrays are returned by value, so modifications won't cause spooky action at a distance. Thus they have no such limitation.

**Comment by VincentLanglet** [comment]
Thanks for the explanation ; Traversable fix the issue indeed
