### ISSUE TITLE
Seperate `TypeDoesNotContainTypeGivenDocBlockType` from `TypeDoesNotContainType`

### ISSUE THREAD

**Issue by janopae** [vimeo/psalm#9578]
Consider the following example:

https://psalm.dev/r/089a593bda

Checking whether the array is `empty` is important in order to ensure type safety. However, we also want to inform to callers that they shouldn't even attempt to call the constructor with an empty array, and make Psalm check for such calls (unless suppressed by the baseline file). So we add `non-empty-array` as param type.

However, Psalm wants to forbid us doing so, saying `TypeDoesNotContainType`, in the vein of "The check is unnecessary, as it is clear that the parameter is not empty". But it is not clear, as we can't know wether the type is correct as long as we suppress any Psalm issues in our code base!

All possibilities to resolve the `TypeDoesNotContainType` issue lead to less type safety. Therefore, it is reasonable to suppress this issue with a codebase that has a baseline. But it is only reasonable to suppress this kind of issues for types inferred from DocBlocks. Therefore, it would make sense for Psalm to raise different issues depending wether the `TypeDoesNotContainType` has been raised of the basis of DocBlock types or actual runtime type checks.

This is a similar situation to `RedundantCondition`/`RedundantConditionGivenDocblockType`, where Psalm already raises a different issue in that case, so you can disable it specifically if it is raised on the basis of DocBlock types.

**Comment by weirdan** [comment]
Are you saying that two `if(empty($a))` in the following example should produce different errors?

https://psalm.dev/r/51de5994d4

**Comment by janopae** [comment]
@weirdan No, I rather thought the following ifs should produce different errors:

https://psalm.dev/r/da7da34bfd

**Comment by orklah** [comment]
It already exists, the alter ego of TypeDoesNotContainType is called DocblockTypeContradiction. See here for an example:
https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Analyzer/Statements/Expression/BinaryOpAnalyzer.php#L290

However, the "from docblock" flag is pretty dumb. It can only be true or false, but reality is more subtle. Here you want to get a DocblockTypeContradiction because Psalm can't know that `$array` is really not empty so Psalm should put "from docblock" flag to false for this type.

On the other hand, you'll also expect a `if(!is_array($array))` to raise a TypeDoesNotContainType because this time, the array was indeed strongly typed.

Those two cases can't be solved at the same time with a single from docblock flag. Going further would mean Psalm should store 2 different types, the one according to docblock and the one according to strong types. This is a very big overhaul to do

**Comment by janopae** [comment]
Oh thanks, I didn't know `TypeDoesNotContainType` already had such an alter-ego.

> Those two cases can't be solved at the same time with a single from docblock flag. Going further would mean Psalm should store 2 different types, the one according to docblock and the one according to strong types. This is a very big overhaul to do

Oh, I didn't know this. I indeed expected Psalm to know the 2 types.

Is there an issue for this big overhaul? Or is it considered out of scope for Psalm? In these cases, this issue should be closed.

**Comment by orklah** [comment]
Go for it :)

**Comment by janopae** [comment]
Closed in favor of #9688
