### ISSUE TITLE
"Unsealed array" and "InvalidArgument".

### ISSUE THREAD

**Issue by mj4444ru** [vimeo/psalm#9620]
1) PhpStorm doesn't understand the "Unsealed array" syntax, I wish Psalm5 could disable the check that outputs "InvalidArgument: Argument ... of ... expects ..., but ... with additional array shape fields (...) was provided".

2) What are the pitfalls of the "array{id: string}&array" construct? Is it possible to use such a solution to the problem instead of "array{id: string, ...}"?

**Comment by ygottschalk** [comment]
1. You can use a `@param/var/return array{foo: 'bar'}` for IDE and an additional `@psalm-param/psalm-var/psalm-return array{foo: 'bar', ...}` for psalm

2: You can use that, see https://psalm.dev/r/ea468e5b19

**Comment by orklah** [comment]
> What are the pitfalls of the "array{id: string}&array"

This syntax doesn't make sense and it will be an issue going forward. If you parse this type it means `an intersection between array{id: string} and an array`. An intersection between a super type and an narrower type will always be the narrower type (for example, `numeric-string&string` means `numeric-string`.

But you could have this syntax mean something. For example `array{id: string, ...}&array<string, string>`, this would mean `an array shape with a mandatory id offset of type string and then any other string offset but only with a string type`.

The `&array` can't be used to say "unsealed array" because it will be used for real intersections in the future.

And yeah, we know each new syntax we introduce will be unknown in PHPStorm. If that had stopped us before, Psalm and other static analysers wouldn't exist (PHPStorm introduced support for SA types only in the last year give or take)

**Comment by ygottschalk** [comment]
> This syntax doesn't make sense and it will be an issue going forward. If you parse this type it means `an intersection between array{id: string} and an array`. An intersection between a super type and an narrower type will always be the narrower type (for example, `numeric-string&string` means `numeric-string`.

I think that is a good ( /the right) definition of an intersection. Going with that definition, psalm currently parses the types wrong, see: https://psalm.dev/r/6cb0d8cc79

`$_1` and `$_2` should then be typed `array{key: string}`,
`$_3` and `$_4` should throw a TypeDoesNotContainType error, bcs `array{key: string} => array<string, string>` and `array<string, string>&array<int, string> => array<never, string>` which should be considered invalid,
`$_5` and `$_6` are typed correctly.

I did not know that psalm supports this syntax `array{key: string, ...}` and was always trying a syntax like the trace shows (`array{key: string, ...<string, string>`) which psalm can not parse to narrow the unseald type until I found out about the intersection "workaround". 

I think a good solution would be to "fix" the array intersection parsing to give results like described above (`$_1 - $_6`) and also add support for giving psalm the type of key/value in an unseald array with the syntax used in traces (`array{key: string, ...<string, string>`)

**Comment by orklah** [comment]
Yeah, we had to keep the &array somewhat compatible, but this will have to change too. basically when you do `array{key: string}&array<int, string>` it's almost the meaning we give to `array{key: string}|array<int, string>`. 

> I did not know that psalm supports this syntax array{key: string, ...} and was always trying a syntax like the trace shows (array{key: string, ...<string, string>}) which psalm can not parse to narrow the unseald type until I found out about the intersection "workaround".

Yeah, that's a future step we have to make too. Psalm should be able to parse this and this would become the final syntax. Maybe if @danog finds some time or some other contributor picks up the task :)

**Comment by danog** [comment]
Yeah I actually tried giving a go at it earlier, will give it another go once I have smore time :)

**Comment by orklah** [comment]
syntax for extra params on unsealed arrays have been implemented in https://github.com/vimeo/psalm/pull/9694
