### ISSUE TITLE
UnusedFunctionCall: false positive for void return

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9627]
https://psalm.dev/r/a5cd4e485a

When a function returns "void" psalm should not report `UnusedFunctionCall`, as there's nothing to validate
(this sometimes happens when 3rd party code/libs has leftover pure tags and the errors make no sense)

Similar if the return is "never" (or void|never), no error should be reported then either.

**Comment by orklah** [comment]
I don't get it, your function does nothing. Do you have a snippet that shows an issue?

**Comment by ygottschalk** [comment]
IMO there should be a PR to the 3rd party library in which there are these "wrong" pure annotations to fix those (or there should be a stub which corrects those).

I can not come up with a pure function with a return value of `void` or `never` which actually does anything...

**Comment by orklah** [comment]
Yeah, fixing upstream is always the first thing to do. Psalm is not here to nicely handle false information in 3rd party code.

About your comment about void/never, you could have a function that dies that could be pure. You could also have an assertion function like `function isStringNotEmpty($str):void{//throw an exception when $str is empty}`

I'm closing this since there is no answer and no issue identified
