### ISSUE TITLE
Empty require statement generates an error that is difficult to track down

### ISSUE THREAD

**Issue by fredericgboutin-yapla** [vimeo/psalm#9639]
Hi,
I cannot provide a test since `allowFileIncludes` flag is rightfully turned off on the test site, but basically,

```php
<?php

require ''; 

// ...
``` 

With `--debug-by-line` this will give you something like,

```sh
Finished registering autoloaded files
Visiting autoload files took 1.402s
Checking [...]
Target PHP version: [...]
Scanning files...
Initializing plugins...
Uncaught UnexpectedValueException: File [...]
Stack trace:
[...]
(Psalm 5.9.0@8b9ad1eb9e8b7d3101f949291da2b9f7767cd163 crashed due to an uncaught Throwable)
```

I had to manually pinpoint the exact file causing an issue and this is when I saw the empty `require` statement. Removing it fixed the issue.

I know this is VERY niche but it would have been nice to see the problematic file being reported right away.

Cheers,

**Comment by fredericgboutin-yapla** [comment]
> I cannot provide a test since allowFileIncludes flag is rightfully turned off on the test site, but basically,

**Comment by edsrzf** [comment]
It looks like what's happening here is that the include is resolved to a directory based on include paths. Then `FileProvider::fileExists` returns true, because the file technically does exist -- it's just a directory.

`FileProvider::getContents` tries to get the directory's contents and throws an `UnexpectedValueException`. The same behavior occurs if you try to include any other directory with a non-empty path.

So I'm not entirely sure what the correct fix is here. Possibilities:

* Modify `FileProvider::fileExists` to return false for directories. This doesn't seem entirely honest, and I'm not sure whether it might break other parts of the code.
* Add `FileProvider::isDirectory` and a call to that method inside `IncludeAnalyzer`
* Probably others?

Then is `MissingFile` still the correct issue to raise? I would say yes, probably, but I'm not 100% sure.
