### ISSUE TITLE
Whats happen with invariant template?

### ISSUE THREAD

**Issue by klimick** [vimeo/psalm#9684]
I expect errors in the both cases. But case with scalars silently hides mistakes.
```php
// No error here. But Wrapper<42> is not Wrapper<int>
acceptStringWrapper(new Wrapper(42));

// Eroror here as expected. Because Wrapper<MoreSpecificObj> is not Wrapper<Obj>
acceptObjWrapper(new Wrapper(new MoreSpecificObj()));
```
https://psalm.dev/r/ded731f803

**Comment by klimick** [comment]
Sorry. Previous example may be confusing.
https://psalm.dev/r/50bdd20919

**Comment by orklah** [comment]
Seems like it boils down to this code:
https://github.com/vimeo/psalm/blob/1c19260cddea29803cba2ef31c3a49189bcdeb0c/src/Psalm/Internal/Type/Comparator/GenericTypeComparator.php#L140-L172

Both checks end up here, but when the input type contains literal, it goes in the first if and don't say the comparison is false. When it doesn't contains literals, we check if the param is contained in the input (basically the two types are the same) and if they're not, we flag an error because of covariance

So there seems to be no check for covariance when dealing with literals. I'm not sure if it was on purpose, but I can definitely say we would probably get a lot more support issue if it was the case (for exactly the reason why you opened the other ticket: Psalm tries to infer the lowest possible template type for your input)

**Comment by klimick** [comment]
> but I can definitely say we would probably get a lot more support issue if it was the case

So you suppose to leave it as is?

**Comment by orklah** [comment]
I'd be inclined to yeah

Is there a practical case you have in mind that justifies that, for a template with literals, you want to inforce covariance?

**Comment by klimick** [comment]
> Is there a practical case you have in mind that justifies that, for a template with literals, you want to inforce covariance?

It's more about the type system consistency than the practical cases.
It's hard to explain some things that happen in Psalm to other folks.
I can explain how variance works here: [phpstan](https://phpstan.org/r/8819990f-fa4b-4cae-9172-436e3a4ea80f), [typescript](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD28A8BLAdteBXALtAKgHzQDeAvgFAUBmWawOK8GwYIIAtgKZJEAU1RAC44iJGiwcARlwBOhAJQiAbvBQATUpQqt23Pmi4B3UcgAsAJkUBuHW05cDx0+Mkz5C20A), [scala](https://scastie.scala-lang.org/HTXZKR2jSmibua8c9gJ59w) but I can't It do in Psalm.

Interesting issue https://github.com/vimeo/psalm/issues/8247 of AndrolGenhald.
He mentions about removing the special case for literals.

**Comment by orklah** [comment]
Oh I didn't remember that.

If PHPStan enforce it, we may as well do it too. You can submit a PR :)

**Comment by othercorey** [comment]
Why wouldn't `42` be an `int`?

**Comment by orklah** [comment]
42 is an int, the issue is with covariance

Imagine if you have a `Collection<42>` and you pass it to a method that expects a `Collection<int>`. Inside this method, I add `43` inside the collection
Psalm is unable to enforce the fact that you shouldn't have put 43 inside a Collection of 42.

That's why you need to declare your template `@template-covariant` for this to be accepted by Psalm. However, Psalm will then enforce other things to make sure you don't fall in the trap above

(Well, all of that would be true if it was actually enforced for literals. It does work right now with object though)

There's more on that here: https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance

**Comment by orklah** [comment]
Yeah, it makes little sense on surface, but that's often what Psalm will infer if you instantiate a `new Collection([self::CONST_WITH_42_VALUE]);` for example, so unless you make some move to go back to a `Collection<int>`, that's not what you'll get

**Comment by klimick** [comment]
> If PHPStan enforce it, we may as well do it too. You can submit a PR :)

OK! I will investigate it in the nearest future.
Surprisingly, there is a ticket https://github.com/vimeo/psalm/issues/4564 for that problem. 
So I gonna close current ticket.
