### ISSUE TITLE
Expanding constants from template parameter broken

### ISSUE THREAD

**Issue by provokateurin** [vimeo/psalm#9702]
https://psalm.dev/r/fc2f4fbda7

**Comment by danog** [comment]
This is actually not a bug, because doing something like this would already lead to an invalid default value in `B::$status`: https://psalm.dev/r/cf20085cdd

The same can be said for `setStatus`, which would allow assignment of a concrete type not matching the template type.

You probably need something like https://psalm.dev/r/3eb715e89c
