### ISSUE TITLE
[Bug] Consecutive @psalm-trace for different vars will only output the last one

### ISSUE THREAD

**Issue by dkarlovi** [vimeo/psalm#9762]
https://psalm.dev/r/df5b44df2f

**Comment by ygottschalk** [comment]
Try using the mighty semicolon: https://psalm.dev/r/8fc2f0cfc5
Or give all variables in one comment: https://psalm.dev/r/7a0ab7eb67

This happens due to how psalm looks at the code, analyzing every code instruction and looking at the comment before the instruction. Therefore the comment in your example in line 6 is never analyzed by psalm, because psalm finds the code at line 4 and analyzes that, looks at the next code instruction (line 9) and then looks at the comment right above (line 7). In the process, psalm skipps over line 6. by adding a `;` you add a no-op code instruction which psalm finds and then looks for a comment right before.

**Comment by dkarlovi** [comment]
@ygottschalk I understand what's causing it, which is why my example has both where it happens and where it doesn't happen (code in between).

**Comment by weirdan** [comment]
This is due to the limitations of `nikic/php-parser`. Not much can be done here.
