### ISSUE TITLE
Class property type is wrong when assigning value to it in method

### ISSUE THREAD

**Issue by M393** [vimeo/psalm#9775]
Initially an empty array is assigned, but after the call to `append` the array is no longer empty.
https://psalm.dev/r/adbe969f63

**Comment by M393** [comment]
As a workaround I added a function to clear `$x`
https://psalm.dev/r/0929db8520

**Comment by orklah** [comment]
Yeah, this doesn't have good solutions. In some pieces of code, you'll want to keep the value (when calling a method that doesn't relate to your property) but in others, you'll want the other way around.

Psalm has actually an option for this named "memoize property assignment" that fixes your snippet when disabled: https://psalm.dev/r/d3180b6f0c

But it's likely to trigger errors elsewhere due to what I said earlier. The best workaround currently is either having local variables or using methods consistently

You could also use assertions to describe the side effects of append but you can't describe everything with assertions (you can only narrow the type, never widen it or reset it)
