### ISSUE TITLE
$_SERVER['REQUEST_TIME_FLOAT'] is not recognized

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [vimeo/psalm#9786]
https://psalm.dev/r/f5145fba18

From [PHP docs](https://www.php.net/manual/en/function.microtime.php):

![image](https://github.com/vimeo/psalm/assets/15625235/90957c41-0dee-42cd-b99a-47e3382b9f29)

**Comment by orklah** [comment]
It is in there, `REQUEST_TIME_FLOAT?: float` but it is flagged as possibly undefined (because it may not always be there depending on your local environment I assume):
https://github.com/vimeo/psalm/blob/f7eaa5daec7af35025dc421958d5c21c671cff8c/src/Psalm/Internal/Analyzer/Statements/Expression/Fetch/VariableFetchAnalyzer.php#L684

So Psalm is indeed warning you that it may be missing, nothing more

I'll close this because as far as I can tell, it's working as expected
