### ISSUE TITLE
Cannot suppress UndefinedInterfaceMethod

### ISSUE THREAD

**Issue by ro0NL** [vimeo/psalm#9855]
Im trying to locally suppress `UndefinedInterfaceMethod`, but fail to do so:

```
ERROR: UndefinedInterfaceMethod - src/file.php:54:76 - Method Symfony\Component\Security\Core\Authentication\Token\TokenInterface::getProviderKey does not exist (see https://psalm.dev/181)
            /** @psalm-suppress UndefinedInterfaceMethod */$originalToken->getProviderKey(),
```

am i missing something?

**Comment by ro0NL** [comment]
https://psalm.dev/r/81804b1049 it's a scope issue :(

**Comment by orklah** [comment]
Suppression should be positionned before the statement:
https://psalm.dev/r/65dee60c64

**Comment by ro0NL** [comment]
@orklah seems ambigious with multiple args, but OK :)

**Comment by ro0NL** [comment]
basically getProviderKey() is available on any token, but not  per contract in `Symfony\Component\Security\Core\Authentication\Token\TokenInterface` :(

in my perfect little world `/** @psalm-suppress UndefinedInterfaceMethod */$originalToken->getProviderKey()` is exactly "positionned before the statement" :sweat_smile:

**Comment by orklah** [comment]
You should consider stubbing it instead of suppressing. Psalm is just blind on everything that happens if you don't

**Comment by ro0NL** [comment]
globally supressed it :shrug: 

IIUC it's not worth supporting

```php
func(
   /** @psalm-suppress UndefinedInterfaceMethod */$a->no(),
   $a->yes()
)
```

**Comment by orklah** [comment]
Basically, Psalm stores the suppression at statement level (a statement is everything that is contained between two semicolon to make it simple).
Meanwhile, for a method call, it analyze very arg at the same time and retrieves the list of undefined interfaces at the end.

Supporting suppression for an expression (here an argument), would be a pain to make it work just for this case but it would be way worse to support it consistently everywhere (because people won't expect it to work only here)

Though if you do want to do that work, you're very welcome :)
