### ISSUE TITLE
MoreSpecificReturnStatement missing?

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9861]
There's LessSpecificReturnStatement and MixedReturnStatement, but MoreSpecificReturnStatement is missing (only reports as `LessSpecificReturnType` when enabled via setting, which makes it hard to know which return statement actually has the issue)

**Comment by orklah** [comment]
Could you share a snippet to show where you would expect a MoreSpecificReturnStatement ?

At first glance, it seems perfectly fine to have return statements that are more specific than signature

**Comment by orklah** [comment]
Please provide a snippet, that makes no sense otherwise.

**Comment by orklah** [comment]
So what you're asking is that Psalm emits an error on "return 'a';' to say "You can't return "A" for a method that should return "string""?

What exactly do you expect as an error message here?

**Comment by orklah** [comment]
You're not getting it. The issue is not that it would be redundant, the issue is that it makes no sense.

Psalm points at things you can fix, there's no fix for a MoreSpecificReturnStatement because it's not an issue

https://psalm.dev/r/1fdaaaa513

For the snippet here:
- You can fix the line 4 by documenting `'B'|'a'` in the return docblock
- You can fix the line 16 by documenting `object` in the return docblock
- You can fix the line 20 by returning a stdClass instead of an object

There's no fix for line 8 here. It would be extremely confusing to report an issue at this position.

There's no symetry between LessSpecificReturnType and MoreSpecificReturnType/LessSpecificReturnStatement except for the naming scheme

**Comment by orklah** [comment]
because the signature may be good and the statement may be wrong OR the statement may be good and the return may be wrong. LessSpecificReturnType is different, only the signature (or docblock) may be changed. The statement is never wrong
