### ISSUE TITLE
GZIP - disable/set level because performance impact is bad

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9905]
https://github.com/vimeo/psalm/pull/9889 added between 10-15% of runtime for uncached runs and increases memory consumption for cached runs by ~20%.
SSD space is super cheap compared to RAM and machine/user time.

Please disable GZIP by default and make it optional (perhaps allow to set the compression level), if you really want to use it. But unless you are really space limited, it doesn't really make sense to enable it @orklah

**Comment by dkarlovi** [comment]
> it doesn't really make sense to enable it

For an almost 90% reduction saying it "doesn't make sense" is doubtful. I'm open to having it have a config, there's already a property in Config which can get exposed via schema pretty easily.

From my POV, the default should be on since the reduction is substantial vs the increase in uncached memory / runtime

The difference in cached runtime / memory is larger, but as @orklah mentioned, the absolute numbers there are small either way. I'll leave it to the project leads to decide about the default. 

While disk is cheap, it's still not free and there's cases where you still want this on, for example Gitlab CI allows you to store your cache dir, if it's smaller, the pipeline is faster both restoring and storing it after the run.

**Comment by dkarlovi** [comment]
Ah right, I forgot I actually profiled the cached run today 😃

It's slower because FileReferenceProvider will update the cache even if it's up-to-date, meaning it always deflates and writes to disk.

If we really care about this specific metric, we can make it no-op in that specific case to not have the "huge increase" in cached runs.

/cc @orklah

**Comment by dkarlovi** [comment]
> Space is never the bottleneck in CI/DevOps nowadays. It's always RAM/CPU and time.

That's incorrect, I gave you an example where you want to conserve space to get performance: Gitlab CI cache. While disk isn't the most important metric, it shouldn't be totally disregard.

**Comment by dkarlovi** [comment]
For example, PHPStan checking the same project as Psalm uses 16MB of cache vs Psalm's 400MB. While we can't directly do math with these numbers, they should give us an idea of scale here.
