### ISSUE TITLE
Issue with interface resolution when using templates

### ISSUE THREAD

**Issue by vuryss** [vimeo/psalm#9927]
I was using some Doctrine collection when I encountered that psalm fails to understand the returned Collection contains the right elements (implementing an interface).

Returned collection contains elements from a specific class, which correctly implements the expected interface.
But psalm says that the declared return type is incorrect.

As I'm struggling to describe this correctly, here is the example: https://psalm.dev/r/adc1e2d44d

**Comment by orklah** [comment]
If you say you return Type1, you need to actually return a Type1, not one of its child, unless you flag the template as covariant:
https://psalm.dev/r/0dd41fadea

Psalm need to check this because otherwise, you could end up with messed up Collections because Psalm can't check everything.

More on that subject here:
https://psalm.dev/docs/annotating_code/templated_annotations/#template-covariance
