### ISSUE TITLE
 Organizing Legacy Codebases Based on Error Levels

### ISSUE THREAD

**Issue by KharchenkoCody** [vimeo/psalm#9948]
Hi!

I have legacy codebases, and I'm currently refactoring the code. I would like to organize the folders based on specific error levels. I want to set error level 7 or 8 for some directories, while using error level 2 or 3 for new directories. How can I achieve this?

**Comment by ro0NL** [comment]
we used 2 psalm instances, thus psalm.xml + psalm-legacy.xml

it works great, except some cache could be shared still, but i didnt bother looking into it

**Comment by KharchenkoCody** [comment]
Thank! I have considered this approach, but I believed there might be another alternative...

**Comment by ro0NL** [comment]
well we use a 2nd instance mostly for separate issue handlers and project files

both instances run at level 2 and were initially suppressed, i see no reason new legacy code shouldnt follow level 2 ;)

**Comment by orklah** [comment]
You can use `issueHandlers` in the config. For each issue, you can choose to either "suppress" or "error" each issue.

So doing this should work:

`
<InvalidCatch>
    <errorLevel type="suppress">
        <directory name="path/" />
    </errorLevel>
    <errorLevel type="error">
        <directory name="path2/" />
    </errorLevel>
</InvalidCatch>
`
It takes some work so having two configs may still be the easiest way...

I'll close this because I don't think we'll go further to support that kind of use cases but feel free to continue discussing here :)
