### ISSUE TITLE
Some errors hide other errors in a function scope

### ISSUE THREAD

**Issue by lens0021** [vimeo/psalm#9962]
https://psalm.dev/r/2a2e8373c0

In the above example, the UndefinedVariable errors are hidden in `bar()` and `baz()` functions. There are UndefinedDocblockClass error and UndefinedClass error respectively.

In my actual code, there are UndefinedClass error and UndefinedVariable, but UndefinedClass is included in the baseline. So I cannot see any issues, though UndefinedClass exists.

**Comment by orklah** [comment]
Yeah.

Basically, UndefinedClass is very very bad.

When Psalm sees an undefined class, it will just give up on analyzing the whole scope because it can't infer anything properly in that case.

If you were to force the analysis, Psalm would start outputting a lot of noise that would hide the real error. So yeah, the solution is to fix the UndefinedClass first here

**Comment by lens0021** [comment]
@orklah Thank you for the information. I have another question, is there a list of the all "very very bad" errors, which are should be fixed and should not include in baseline?

**Comment by weirdan** [comment]
The first list on this page, basically: https://psalm.dev/docs/running_psalm/error_levels/
