### ISSUE TITLE
numeric-string should support numeric-string<0, max> syntax

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9985]
https://psalm.dev/r/d39edd2f68

to allow "> 0" checks to work correctly.
Alternatively a positive-numeric-string maybe?

**Comment by ygottschalk** [comment]
IMO it would be the right thing to set [strictBinaryOperands](https://psalm.dev/docs/running_psalm/configuration/#strictbinaryoperands) to true and just disallow such comparison.
Honestly I don't even know, what php will compare, the string length, the numerical ascii value or does php convert the number to a string and does a string > string compare...

That is why I am against having bounds on the numerical-string type.

**Comment by ygottschalk** [comment]
1. Odd. Maybe `BinaryOperands` does not include comparisson but just operators like `>>`, `|`, `xor`,...
2. Is it more verbose? https://psalm.dev/r/079a11d307. Admittedly, I hate assignements inside if conditions, but in cases like this (type validation / casting) I find myself doing them all the time...

**Comment by orklah** [comment]
That won't happen as is.

First because numeric-string is horrible: https://3v4l.org/Bc7vp
It supports math notation so it can have letters in them, it supports floats in string so `numeric-string<1,2>` is not fine enough to describe it. It also supports ints that doesn't even fit in PHP_INT_MAX so you'd have to redo everything that exists for int ranges an other way with `bc_` functions. Don't even get me started on what binary operation are supposed to do on a numeric-string but that will have to be handled specifically too.

Add to that the fact that int-ranges are barely functional and still full of bugs, in particular in loops and you get why trying to add support for numeric-string (or even float) ranges would be bad
