### ISSUE TITLE
DateInterval::$days false return isn't ignored

### ISSUE THREAD

**Issue by kkmuffme** [vimeo/psalm#9995]
https://psalm.dev/r/083ee5e953

But I guess it should be ignored https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Reflection.php#L157

I guess it's bc of https://github.com/vimeo/psalm/blob/master/dictionaries/ManualPropertyMap.php#L20 ? (and/or https://github.com/vimeo/psalm/blob/master/dictionaries/PropertyMap.php#L69) where the property map has precedence over things set in code? (which would be bad) @orklah

**Comment by ygottschalk** [comment]
One of those files is autogenerated from the other. I think changes must be in the Manual file. There was a comment on the top of the autogenerated file...

**Comment by orklah** [comment]
Reflection is there to get type from PHP core data. So in theory, it should pick up the correct type from what's in PHP but that property is weird enough that we have to make a PropertyMap to correct it's type so it's normal that the map is overriding Reflection.

However, this https://github.com/vimeo/psalm/blob/master/src/Psalm/Internal/Codebase/Reflection.php#L155 should be put in the PropertyMap parsing too (so, here: https://github.com/vimeo/psalm/blob/dd0d8300b1505cf909734215450ab6d75bf71d12/src/Psalm/Internal/Codebase/PropertyMap.php#L32) so that it behave as an ignorable false

**Comment by tscni** [comment]
Wouldn't that break cases where `DateInterval::$days` is actually `false`? (e.g. https://psalm.dev/r/f309122a6a might erroneously start working?)
I don't actually understand why `ignore_falsable_issues` would be set on it without verifying that it comes from a `DateTimeInterface::diff()` call. Unless it does and I'm missing something :P
